- README.md
@jmabille this is also testing the Travis CI webhook.
> Add RTD and Travis Badges

- .appveyor.yml
- test/CMakeLists.txt
> Setup appveyor build

- include/xtensor/xcontainer.hpp
- include/xtensor/xfunction.hpp
- test/test_common.hpp
- test/test_xarray.cpp
- test/test_xarray_adaptor.cpp
- test/test_xfunction.cpp
- test/test_xtensor.cpp
- test/test_xtensor_adaptor.cpp
@SylvainCorlay This PR implements a dynamic operator[] and closes #8.
> dynamic access operator

- include/xtensor/xcontainer.hpp
> Simplify xcontainer.data_offset

- include/xtensor/xiterator.hpp
- include/xtensor/xview.hpp
- test/test_xview.cpp
> fixing view on xtensor

- include/xtensor/xview.hpp
> Fix view iteration

- include/xtensor/xfunction.hpp
- include/xtensor/xiterator.hpp
- test/test_xview.cpp
> fixing iteration over view

- include/xtensor/xview.hpp
- test/test_xview.cpp
> fixing views on const containers

- include/xtensor/xfunction.hpp
- test/CMakeLists.txt
> fixing -Wreorder warning

- include/xtensor/xfunction.hpp
- test/test_xvectorize.cpp
@SylvainCorlay This PR allows xfunction with no arguments, needed for zeros and ones functions.
> xfunction with no arguments

- include/xtensor/xfunction.hpp
- include/xtensor/xutils.hpp
- test/test_xutils.cpp
@JohanMabille this seems to be working ok.
Check out my changes to `_or`, `_and` and the meta function for `promote_shape` and `promote_strides`.
Name proposals welcome.
> Promote shape

- include/xtensor/xview.hpp
This is my attempt for fixing #43
> fix printing of column view

- include/xtensor/xcontainer.hpp
- include/xtensor/xexception.hpp
- test/test_common.hpp
- test/test_xarray.cpp
- test/test_xio.cpp
- test/test_xtensor.cpp
Hi,
I have improved the transpose function and added a bunch of tests. 
Let me know if there is anything else you'd want to have before considering to merge this.
I also sneaked in a test for the fix I provided in the previous pull request.
> add transpose & transpose with axis permutation, tests

- .appveyor.yml
- .travis.yml
- CMakeLists.txt
- include/xtensor/xtensor_config.hpp
- include/xtensor/xutils.hpp
- test/CMakeLists.txt
- xtensorConfig.cmake.in
> cmake build files

- include/xtensor/xbroadcast.hpp
- test/test_xbroadcast.cpp
> fix #95 broadcast forward_shape and add test

- include/xtensor/xexpression.hpp
> derived_cast for rvalue reference

- include/xtensor/xgenerator.hpp
- include/xtensor/xindexview.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xview.hpp
> iterators and steppers default constructors

- include/xtensor/xview.hpp
- test/test_xio.cpp
Closes #115. Closes #114.
This includes the proposed failing test.
> Fix newaxis access

- include/xtensor/xcontainer.hpp
- include/xtensor/xutils.hpp
- test/test_common.hpp
> transpose argument is now a template

- CMakeLists.txt
- include/xtensor/xarray.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xslice.hpp
- include/xtensor/xtensor.hpp
- include/xtensor/xtensor_forward.hpp
- include/xtensor/xutils.hpp
- include/xtensor/xview.hpp
- include/xtensor/xview_utils.hpp
- test/test_xsemantic.hpp
- test/test_xview.cpp
> Temporary view

- include/xtensor/xassign.hpp
- include/xtensor/xview.hpp
- test/test_xview_semantic.cpp
> broadcasting shape in view assign

- include/xtensor/xview.hpp
- include/xtensor/xview_utils.hpp
- test/test_xio.cpp
- test/test_xview.cpp
This PR fixes #129 and the shape-bug indicated in #132.
> fix view and add tests

- include/xtensor/xscalar.hpp
- test/test_xscalar.cpp
> non const method for scalar and xref - xcref

- CMakeLists.txt
- benchmark/CMakeLists.txt
- benchmark/main.cpp
- include/xtensor/xutils.hpp
This PR adds some benchmarks which are not built by the CI.
> simple benchmark added

- include/xtensor/xbuilder.hpp
- include/xtensor/xoperation.hpp
- test/test_xbuilder.cpp
This adds the concatenate function. I have also left vstack and hstack, but vstack is a bit limited in functionality as it's currently not possible to vstack two 1D vectors. 
In another PR I'll implement the `stack` functionality. 
Happy about feedback for concatenate in it's current state!
> Concatenate

- docs/source/operator.rst
- docs/source/view.rst
Hi Guys,
I was going through some of the examples this morning as I am interested in employing xtensor in some of my work. I ran across a couple of bugs in the code samples. I did not go through everything, but, this PR reflects what I saw in `operator.rst` and `view.rst`
Best,
Tom
> Fixed some bugs in the operator and view docs

- docs/source/basic_usage.rst
- include/xtensor/xutils.hpp
- test/test_xutils.cpp
Not using closure types but forwarding real and imaginary parts.
> Forward real and imaginary parts

- include/xtensor/xbuilder.hpp
- test/test_xbuilder.cpp
I have rebased this and included fixes for comments on the old PR.
> Add functions diag, diagonal, tril, triu, fliplu, fliplr

- include/xtensor/xindexview.hpp
- test/test_xindexview.cpp
> xindexview assign operator added

- include/xtensor/xindexview.hpp
- include/xtensor/xiterator.hpp
This improves the performance of ``xindexview``.
> xindexview shape optimization

- README.md
- docs/source/compilers.rst
- docs/source/index.rst
> Add compiler workarounds page in documentation

- include/xtensor/xexception.hpp
> Include <iterator>

- docs/source/api/xcontainer.rst
- docs/source/api/xreducer.rst
- include/xtensor/xarray.hpp
- include/xtensor/xbroadcast.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xindexview.hpp
- include/xtensor/xiterable.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xtensor.hpp
- include/xtensor/xview.hpp
This should facilitate the writing of adaptors.
> Container refactoring

- docs/source/api/xarray.rst
- docs/source/api/xtensor.rst
- include/xtensor/xarray.hpp
- include/xtensor/xtensor.hpp
- include/xtensor/xtensor_config.hpp
- include/xtensor/xtensor_forward.hpp
This refactoring aims to make the plug of one dimensional containers into xtensor easier.
> xarray / xtensor refactoring

- docs/source/api/xeval.rst
- docs/source/container.rst
- docs/source/expression.rst
- docs/source/operator.rst
- docs/source/view.rst
and fix a bunch of `xt::array` -> `xt::xarray`
> add xeval to docs

- include/xtensor/xoperation.hpp
- test/test_xoperation.cpp
Not sure if they are correctly "categorized"...
> add amax, amin reducers

- docs/source/external-structures.rst
- docs/source/index.rst
tutorial on how to plug external data structures into xtensor
> adaptors tutorial

- include/xtensor/xoptional.hpp
- test/test_xoptional.cpp
- Adding operations on optionals.
- Fix an issue with how const and reference are added.
- Tests on operations.
> Add operations for optionals

- README.md
- docs/source/basic_usage.rst
- docs/source/closure-semantics.rst
- docs/source/missing.rst
- docs/source/numpy-differences.rst
A pass on documentation and readme issues.
> Documentation fixes on missing values.

- docs/source/related.rst
- include/xtensor/xbuilder.hpp
- include/xtensor/xstorage.hpp
Fixes some cling compilation warnings
> Cling compilation warnings

- CMakeLists.txt
- docs/source/api/xarray.rst
- docs/source/api/xarray_adaptor.rst
- docs/source/api/xtensor.rst
- docs/source/api/xtensor_adaptor.rst
- include/xtensor/xarray.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xcsv.hpp
- include/xtensor/xstorage.hpp
- include/xtensor/xtensor.hpp
- test/CMakeLists.txt
- test/test_xarray.cpp
- test/test_xarray_adaptor.cpp
- test/test_xcsv.cpp
- test/test_xtensor.cpp
- test/test_xtensor_adaptor.cpp
- test/test_xview.cpp
This also removes the `move_reshape`.
> Initial implementation for load_csv, and dump_csv

- .travis.yml
- test/CMakeLists.txt
> build of gtest fixed

- include/xtensor/xcontainer.hpp
- include/xtensor/xstorage.hpp
> Fix GCC-6 benchmark error

- include/xtensor/xarray.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xstrides.hpp
- include/xtensor/xtensor.hpp
- include/xtensor/xtensor_forward.hpp
- test/CMakeLists.txt
- test/test_common.hpp
- test/test_xadaptor_semantic.cpp
- test/test_xarray.cpp
- test/test_xarray_adaptor.cpp
- test/test_xfunction.cpp
- test/test_xiterator.cpp
- test/test_xlayout.cpp
- test/test_xscalar_semantic.cpp
- test/test_xsemantic.hpp
- test/test_xtensor.cpp
- test/test_xtensor_adaptor.cpp
- test/test_xview_semantic.cpp
> add layout as template parameter

- CMakeLists.txt
- include/xtensor/xcontainer.hpp
- include/xtensor/xeval.hpp
- include/xtensor/xstridedview.hpp
- include/xtensor/xtensor_forward.hpp
- test/CMakeLists.txt
- test/test_common.hpp
- test/test_xstridedview.cpp
I've seperated out the xstridedview. 
In this PR I've also left the inplace transpose functionality.
> add xstrideview

- test/CMakeLists.txt
- xtensorConfig.cmake.in
> Normalize cmake

- docs/source/related.rst
> Reflect new xtensor-cookiecutter name

- README.md
- docs/source/installation.rst
DONOTMERGE
For some reason, the one from quantstack.net randomly does not show.
> Use local logo image

- CMakeLists.txt
- include/xtensor/xaxis_iterator.hpp
- include/xtensor/xutils.hpp
- include/xtensor/xview.hpp
- test/CMakeLists.txt
- test/test_xaxis_iterator.cpp
> axis iterators

- include/xtensor/xbroadcast.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xfunctorview.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xindexview.hpp
- include/xtensor/xiterable.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xscalar.hpp
- include/xtensor/xstridedview.hpp
- include/xtensor/xview.hpp
- test/test_xiterator.cpp
- test/test_xlayout.cpp
- test/test_xview.cpp
> bidirectional xiterator

- docs/source/numpy.rst
> cheatsheet updated with iteratorlayout

- include/xtensor/xaxis_iterator.hpp
@JohanMabille Making the storage mutable.
> Fixup xaxis iterator

- benchmark/benchmark_container.hpp
- benchmark/benchmark_views.hpp
- benchmark/main.cpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xstridedview.hpp
- test/test_xreducer.cpp
> Stridedview

- CMakeLists.txt
- docs/source/api/xarray_adaptor.rst
- docs/source/api/xtensor_adaptor.rst
- include/xtensor/xadapt.hpp
- include/xtensor/xarray.hpp
- include/xtensor/xbuffer_adaptor.hpp
- include/xtensor/xtensor.hpp
- test/CMakeLists.txt
- test/test_xadapt.cpp
- test/test_xarray_adaptor.cpp
- test/test_xbuffer_adaptor.cpp
> buffer adaptor

- README.md
- docs/source/related.rst
Add xtensor-julia-cookiecutter project mention.
> Mentioning xtensor-julia-cookiecutter

- include/xtensor/xreducer.hpp
- include/xtensor/xview.hpp
- test/test_xview.cpp
> xview constructor fix

- include/xtensor/xassign.hpp
- include/xtensor/xoperation.hpp
- test/test_xadaptor_semantic.cpp
- test/test_xcontainer_semantic.cpp
- test/test_xiterator.cpp
- test/test_xnoalias.cpp
- test/test_xoperation.cpp
- test/test_xscalar_semantic.cpp
- test/test_xsemantic.hpp
- test/test_xview_semantic.cpp
> Many fixes for tensors

- include/xtensor/xcontainer.hpp
- test/test_xarray.cpp
> Leading stride optimization issue

- include/xtensor/xinfo.hpp
Without this, xinfo for pyarray doesn't compile.
> add const qualifier to xinfo shape/stride for loop

- include/xtensor/xcontainer.hpp
> Constexpr dimension

- README.md
- include/xtensor/xbroadcast.hpp
- include/xtensor/xbuilder.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xexception.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xfunctorview.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xindexview.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xstridedview.hpp
- include/xtensor/xstrides.hpp
- test/test_xbuilder.cpp
> Windows meshgrid

- .travis.yml
- docs/source/compilers.rst
- include/xtensor/xbuffer_adaptor.hpp
- include/xtensor/xstorage.hpp
- include/xtensor/xutils.hpp
> WIP Fixup has_trivial_default_constructor deprecation warning on clang

- docs/source/changelog.rst
- docs/source/index.rst
- docs/source/releasing.rst
> changelog added

- docs/source/changelog.rst
- include/xtensor/xview.hpp
- test/test_xview.cpp
Fixes errors when trying to assign a view to another view with the same type.
> xview semantic

- include/xtensor/xiterable.hpp
- include/xtensor/xoptional.hpp
- include/xtensor/xview.hpp
- test/test_xview.cpp
> Const iter

- include/xtensor/xcontainer.hpp
- include/xtensor/xstridedview.hpp
- include/xtensor/xstrides.hpp
- test/test_xarray.cpp
> transpose fixed

- docs/source/numpy-differences.rst
- docs/source/related.rst
Add `xtensor-r` example, and an item in the differences with numpy.
> Updates to documentation

- include/xtensor/xfunction.hpp
- include/xtensor/xtensor.hpp
- test/test_xtensor.cpp
> xtensor extended constructor fixed

- README.md
- docs/source/changelog.rst
- docs/source/installation.rst
> readme and changelogs updated

- README.md
- docs/source/changelog.rst
- include/xtensor/xaxis_iterator.hpp
- include/xtensor/xfunctorview.hpp
- include/xtensor/xview.hpp
- test/test_xaxis_iterator.cpp
> xproxy_wrapper / xclosure_pointer uused in proxy iterators

- include/xtensor/xassign.hpp
- include/xtensor/xexpression.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xoperation.hpp
> expression tag system

- include/xtensor/xoperation.hpp
- include/xtensor/xsemantic.hpp
- include/xtensor/xutils.hpp
- test/test_xcontainer_semantic.cpp
- test/test_xoperation.cpp
- test/test_xutils.cpp
> bitwise operation implemented

- CMakeLists.txt
- benchmark/CMakeLists.txt
- benchmark/benchmark_assign.hpp
- benchmark/benchmark_container.hpp
- benchmark/benchmark_math.hpp
- benchmark/benchmark_views.hpp
- benchmark/main.cpp
I hope I caught all the benchmarks we had. 
This should enable us to add new benchmarks easily in the future. Also comes with a fancy command line interface (e.g. `--benchmark_filter=sum_assign` and more) and JSON reporting.
> port benchmarks to google benchmark framework

- include/xtensor/xcomplex.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xoffsetview.hpp
There were a few functions left that previously depended on the complex functions in xutils that are now in xtl/complex.
> More from xtl::complex that was previously in xutils

- include/xtensor/xstridedview.hpp
> Fixup strided view

- include/xtensor/xadapt.hpp
- include/xtensor/xarray.hpp
- include/xtensor/xbuffer_adaptor.hpp
- include/xtensor/xinfo.hpp
- include/xtensor/xoptional.hpp
- include/xtensor/xtensor.hpp
- test/test_xbuffer_adaptor.cpp
Still marked as `WIP` because I have not added the helpers for adaptor types.
> Buffer adaptor acquires closure on passed pointer

- include/xtensor/xassign.hpp
- include/xtensor/xoptional.hpp
> Forward declaration of value and has_value in xassign.hpp

- .appveyor.yml
- CMakeLists.txt
- docs/source/api/container_index.rst
- docs/source/api/xarray.rst
- docs/source/api/xarray_adaptor.rst
- docs/source/api/xoptional_assembly.rst
- docs/source/api/xoptional_assembly_adaptor.rst
- docs/source/api/xoptional_assembly_base.rst
- docs/source/api/xtensor_adaptor.rst
- docs/source/missing.rst
- include/xtensor/xarray.hpp
- include/xtensor/xassign.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xoperation.hpp
- include/xtensor/xoptional.hpp
- include/xtensor/xoptional_assembly.hpp
- include/xtensor/xoptional_assembly_base.hpp
- test/CMakeLists.txt
- test/test_common.hpp
- test/test_xoptional_assembly.cpp
- test/test_xoptional_assembly_adaptor.cpp
> xoptional_assembly_base implementation

- .appveyor.yml
- .travis.yml
This replace #499 since a new xtl has been release.
> upgrade to xtl 0.3.3

- include/xtensor/xbuilder.hpp
- test/test_xbuilder.cpp
> fix linspace

- include/xtensor/Untitled.ipynb
- include/xtensor/xadapt.hpp
- include/xtensor/xbuffer_adaptor.hpp
- include/xtensor/xexpression.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xnorm.hpp
- include/xtensor/xnpy.hpp
- include/xtensor/xtensor_simd.hpp
- include/xtensor/xview.hpp
- test/test_xarray.cpp
- test/test_xbuffer_adaptor.cpp
- test/test_xbuilder.cpp
- test/test_xconcepts.cpp
- test/test_xcontainer_semantic.cpp
- test/test_xexception.cpp
- test/test_xindexview.cpp
- test/test_xiterator.cpp
- test/test_xlayout.cpp
- test/test_xnorm.cpp
- test/test_xnpy.cpp
- test/test_xoperation.cpp
- test/test_xoptional_assembly.cpp
- test/test_xoptional_assembly_adaptor.cpp
- test/test_xreducer.cpp
- test/test_xstorage.cpp
- test/test_xstridedview.cpp
- test/test_xtensor.cpp
- test/test_xtensor_semantic.cpp
- test/test_xview.cpp
Change `accept_ownership` to `acquire_ownership` in xadapt's documentation.
Also some formatting pass.
> Doc fixes and formatting

- include/xtensor/xreducer.hpp
- test/test_xreducer.cpp
Fixing issue originally reported by @rayglover-ibm .
> Fix in xreducer

- include/xtensor/xfunctorview.hpp
- include/xtensor/xio.hpp
- include/xtensor/xmath.hpp
- test/CMakeLists.txt
- test/test_xcomplex.cpp
- test/test_xmath.cpp
Test's fail currently locally for me, because of some changes required for xfunctorview, I think.
> Isclose complex

- include/xtensor/xinfo.hpp
- include/xtensor/xvectorize.hpp
- test/CMakeLists.txt
- test/test_xinfo.cpp
> Adding tests for xinfo, and fixing xinfo for MSVC 2015

- include/xtensor/xoptional_assembly.hpp
- test/test_xoptional_assembly.cpp
> xoptional_assembly constructor fixed

- include/xtensor/xassign.hpp
- include/xtensor/xbroadcast.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xfunctorview.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xindexview.hpp
- include/xtensor/xoptional.hpp
- include/xtensor/xoptional_assembly_base.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xscalar.hpp
- include/xtensor/xstridedview.hpp
- include/xtensor/xutils.hpp
- include/xtensor/xview.hpp
- test/test_common.hpp
- test/test_xbroadcast.cpp
- test/test_xbuilder.cpp
- test/test_xfunction.cpp
- test/test_xindexview.cpp
- test/test_xoptional.cpp
- test/test_xoptional_assembly.cpp
- test/test_xoptional_assembly_adaptor.cpp
- test/test_xreducer.cpp
- test/test_xscalar.cpp
Fixes #534 
Codacy report is a false positive.
> indexed access operator accepts arbitrary sequences

- docs/source/api/xrandom.rst
- include/xtensor/xrandom.hpp
- test/test_xrandom.cpp
This might be the last PR for tonight ...
> add random::choice

- include/xtensor/xtensor_config.hpp
- include/xtensor/xtensor_forward.hpp
- test/test_common.hpp
- test/test_xstorage.cpp
> clean up default allocator

- include/xtensor/xview.hpp
- test/test_xview.cpp
> return types of xview::strides fixed

- include/xtensor/xstrides.hpp
- test/CMakeLists.txt
- test/test_xoptional_assembly.cpp
- test/test_xstrides.cpp
> unravel function

- include/xtensor/xcontainer.hpp
- include/xtensor/xexception.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xstrided_view.hpp
And add an XTENSOR_ASSERT as it would be expected (checking a condition).
> rename XTENSOR_ASSERT to XTENSOR_TRY

- docs/source/view.rst
> Fix a typo in the documentation of View

- benchmark/benchmark_assign.hpp
- benchmark/benchmark_container.hpp
- benchmark/benchmark_math.hpp
- benchmark/benchmark_views.hpp
- docs/source/changelog.rst
- docs/source/container.rst
- docs/source/external-structures.rst
- include/xtensor/xarray.hpp
- include/xtensor/xassign.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xlayout.hpp
- include/xtensor/xoptional_assembly.hpp
- include/xtensor/xoptional_assembly_base.hpp
- include/xtensor/xrandom.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xsort.hpp
- include/xtensor/xtensor.hpp
- test/test_common.hpp
- test/test_xarray.cpp
- test/test_xarray_adaptor.cpp
- test/test_xbuilder.cpp
- test/test_xfunction.cpp
- test/test_xoptional_assembly.cpp
- test/test_xoptional_assembly_adaptor.cpp
- test/test_xreducer.cpp
- test/test_xsemantic.hpp
- test/test_xstrided_view.cpp
- test/test_xtensor.cpp
- test/test_xtensor_adaptor.cpp
> rename reshape to resize, add reshape function

- include/xtensor/xadapt.hpp
- include/xtensor/xarray.hpp
- include/xtensor/xbuffer_adaptor.hpp
- test/test_xadapt.cpp
Failing now, passing with `noalias` workaround.
Let me know if that's okay!
> Added a test for in-place assignment to xarray adaptor

- include/xtensor/xtensor.hpp
- test/test_xadapt.cpp
Same fix as in #619 but for tensor adapters
> xtensor adaptor fixed

- include/xtensor/xreducer.hpp
- test/test_xreducer.cpp
@egpbos this should fix your stddev function.
> reducer fixed

- docs/source/adaptor.rst
I replaced the pseudo-code with some actual code that can be run (I find it easier to understand). I also added an example of getting data out of a function which does some computation.
Let me know what you think.
> Improved adapter documentation

- include/xtensor/xcontainer.hpp
- test/test_xindex_view.cpp
> fix const reference in xcontainer for const container

- include/xtensor/xoperation.hpp
> expression tag is now computed on closure

- include/xtensor/xcontainer.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xiterator.hpp
- test/test_xbuilder.cpp
- test/test_xtensor.cpp
> handling broadcasting in generator access operators

- include/xtensor/xassign.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xshape.hpp
- test/test_xvectorize.cpp
Reverts QuantStack/xtensor#638
> Revert "Skip broadcasting if static dimensions known"

- .appveyor.yml
- .travis.yml
- include/xtensor/xfixed.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrides.hpp
- test/CMakeLists.txt
I think we might redefine compute_size in the detail namespace in xtensor-blas ...
> qualify namespace for compute_size

- include/xtensor/xio.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xview.hpp
That way we can get rid of the template recursion making compilation potentially faster (template recursion currently still in).
> Make xio use dynamic_view instead of view

- .appveyor.yml
- CMakeLists.txt
- test/test_xfixed.cpp
- test/test_xindex_view.cpp
> index view test assertion fixed

- docs/source/api/xstrided_view.rst
- docs/source/view.rst
- include/xtensor/xstorage.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrides.hpp
- test/test_xstrided_view.cpp
> Flatten view

- include/xtensor/xadapt.hpp
- include/xtensor/xarray.hpp
- include/xtensor/xassign.hpp
- include/xtensor/xaxis_iterator.hpp
- include/xtensor/xbroadcast.hpp
- include/xtensor/xbuffer_adaptor.hpp
- include/xtensor/xbuilder.hpp
- include/xtensor/xcomplex.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xexpression.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xfunctor_view.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xnpy.hpp
- include/xtensor/xoffset_view.hpp
- include/xtensor/xoperation.hpp
- include/xtensor/xoptional.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xscalar.hpp
- include/xtensor/xslice.hpp
- include/xtensor/xstorage.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xtensor_config.hpp
- include/xtensor/xtensor_forward.hpp
- include/xtensor/xtensor_simd.hpp
- include/xtensor/xutils.hpp
- include/xtensor/xview.hpp
> replacing  with <> in xtl includes

- include/xtensor/xstorage.hpp
- test/test_xshape.cpp
> additional constructors for svector

- README.md
- test/CMakeLists.txt
> Remove test_xsemantics from test CMakeLists

- docs/source/api/xbuilder.rst
- include/xtensor/xbuilder.hpp
- include/xtensor/xexception.hpp
- include/xtensor/xfixed.hpp
- include/xtensor/xgenerator.hpp
- test/test_xbuilder.cpp
> add zeros/ones/full/empty_like

- benchmark/CMakeLists.txt
- benchmark/benchmark_assign.hpp
- benchmark/benchmark_xshape.hpp
@HadrienG2 can you check if this works?
The problem wasn't the commas, but that we have renamed small_vector to `svector`.
Cheers,
Wolf
> fix benchmarks on master

- include/xtensor/xassign.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xfunctor_view.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xoptional_assembly_base.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xview.hpp
Using @wolfv 's benchmark, "fixes" #695 
Without this change:
```
--------------------------------------------------------------------------
Benchmark                                   Time           CPU Iterations
--------------------------------------------------------------------------
dynamic_iterator<float>                  5006 ns       5004 ns     100000
iterator<float>                           805 ns        804 ns     798540
loop<float>                               943 ns        942 ns     646645
loop_view<float>                          720 ns        719 ns     969972
loop_raw<float>                           725 ns        724 ns     975515
assign<float>                            4664 ns       4662 ns     157197
assign_view<float>                       8336 ns       8334 ns …
```
> Optimize stepper increment

- benchmark/CMakeLists.txt
- benchmark/benchmark_view_iteration.hpp
- benchmark/benchmark_views.hpp
- benchmark/main.cpp
> Xview iter bench

- include/xtensor/xfunction.hpp
- include/xtensor/xoperation.hpp
- include/xtensor/xutils.hpp
- test/test_xoperation.cpp
This fixes the problem identified in #703.
Some refactoring has to be done once xsimd has been released.
> where fix with xsimd

- include/xtensor/xfunction.hpp
- include/xtensor/xoperation.hpp
- test/test_xoperation.cpp
This actually may help to fix #712
> Mixed arithmetic

- include/xtensor/xstrided_view.hpp
> return types fixed in dynamic view helper

- include/xtensor/xstrided_view.hpp
- include/xtensor/xview.hpp
- test/test_xview.cpp
> xview on const expressions fixed

- include/xtensor/xstrided_view.hpp
- test/test_xdynamic_view.cpp
- test/test_xview.cpp
> fix iterator for const strided_view

- include/xtensor/xio.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xview_utils.hpp
fixing #726 and #725 
@ukoethe can you review this PR?
> add decays to make const value_type compile

- include/xtensor/xassign.hpp
- include/xtensor/xbroadcast.hpp
- include/xtensor/xsemantic.hpp
- include/xtensor/xstrides.hpp
- include/xtensor/xview.hpp
- test/test_xdynamic_view.cpp
- test/test_xiterator.cpp
- test/test_xview.cpp
> view semantic (broadcast on assign) fixed

- include/xtensor/xview.hpp
> compilation prevented when using ellipsis with xview

- include/xtensor/xiterator.hpp
- test/test_xdynamic_view.cpp
- test/test_xiterator.cpp
> index of xiterator set to shape when reaching the end

- include/xtensor/xscalar.hpp
> xscalar fix

- include/xtensor/xassign.hpp
> Missing include in xassign

- include/xtensor/xslice.hpp
- include/xtensor/xstrided_view.hpp
- test/test_xdynamic_view.cpp
i think we'll not officially support negative steps for the first iteration, because we need to figure out how to handle negative strides for the stridedview (i.e. do we have to switch to a signed integer type for the strides?).
maybe we can start with supporting a negative end.
> switch to ptrdiff_t for slices

- include/xtensor/xstrided_view.hpp
- include/xtensor/xutils.hpp
- test/test_xutils.cpp
> clean up has_raw_data in strided view

- include/xtensor/xio.hpp
- include/xtensor/xstrided_view.hpp
> Use default_assignable_layout for strided view.

- environment.yml
- include/xtensor/xaccumulator.hpp
- include/xtensor/xaxis_iterator.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xslice.hpp
- include/xtensor/xsort.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrides.hpp
- include/xtensor/xutils.hpp
And include some automatic formatting.
> Update xtensor-blas in binder

- include/xtensor/xcontainer.hpp
- test/test_xtensor_semantic.cpp
> fixed uninitialized backstrides

- include/xtensor/xfunction.hpp
- include/xtensor/xoptional.hpp
- test/test_xfunction.cpp
> copy constructor of xfunction fixed

- include/xtensor/xslice.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrides.hpp
- include/xtensor/xview.hpp
- test/test_xdynamic_view.cpp
- test/test_xview.cpp
I am going to iterate on this PR.
> add dynamic view unwrapping

- include/xtensor/xbuilder.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xexception.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xslice.hpp
- include/xtensor/xstrided_view.hpp
- test/test_xbroadcast.cpp
- test/test_xnan_functions.cpp
> Fix warnings

- docs/source/api/xstrided_view.rst
- docs/source/developer/concepts.rst
- docs/source/developer/implementation_classes.rst
- docs/source/developer/xtensor_internals.rst
- docs/source/operator.rst
still need to update the xtensor internals for the new assign branch.
> update docs for data -> storage

- include/xtensor/xexception.hpp
- include/xtensor/xscalar.hpp
- test/test_xfunction.cpp
- test/test_xscalar.cpp
> scalar stepper fixed

- include/xtensor/xstrided_view.hpp
> add layout template parameter to strided view

- include/xtensor/xmath.hpp
- include/xtensor/xreducer.hpp
- test/test_xmath.cpp
- test/test_xreducer.cpp
This adds a new reducer (count_nonzeros) -- just like in numpy.
And adds an exception if axis is out of bounds. 
For testing the exception (and in general) i had to remove many noexcepts, as the exception doesn't bubble up with noexcept.
Alternatively we could change the exception to assert...
> add count_nonzeros, and remove noexcept

- include/xtensor/xadapt.hpp
- test/test_xadapt.cpp
Using the approach suggested by @JohanMabille.
> Allow xadapt with dynamic layout

- README.md
- docs/source/_static/main_stylesheet.css
- docs/source/conf.py
Full-width documentation + explicit link in readme (in addition to the link).
> Add custom css to documentation and explicit link

- include/xtensor/xfixed.hpp
- test/test_xfixed.cpp
> add xtensorf initialization from C array

- docs/source/container.rst
- include/xtensor/xbuilder.hpp
- include/xtensor/xfixed.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xtensor_forward.hpp
- test/test_xbuilder.cpp
- test/test_xfixed.cpp
- test/test_xreducer.cpp
- test/test_xutils.cpp
- test/test_xview.cpp
> xtensorf renamed in xtensor_fixed

- include/xtensor/xiterator.hpp
- include/xtensor/xjson.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xslice.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrides.hpp
- test/test_xmath.cpp
There are a couple more warnings regarding the slices and signed/unsigned types!
> WIP initial warnings pass

- include/xtensor/xarray.hpp
- include/xtensor/xtensor.hpp
Like it is already the case in xtensor
> Rename m_data to m_storage

- include/xtensor/xview.hpp
- test/test_xview.cpp
Just a slightly modified version of #862. (Fixes #856. Closes #862).
Commit still credited to @wolfv.
> fix random access stepping

- include/xtensor/xmath.hpp
- test/test_xmath.cpp
@wolfv this should fix the benchmarks
> simd on mathematical functions fixed

- include/xtensor/xcontainer.hpp
- include/xtensor/xtensor_config.hpp
- include/xtensor/xtensor_forward.hpp
- test/test_common.hpp
- test/test_xarray.cpp
- test/test_xarray_adaptor.cpp
- test/test_xtensor.cpp
- test/test_xtensor_adaptor.cpp
> fill method added to xcontainer

- include/xtensor/xbroadcast.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xfunctor_view.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xindex_view.hpp
- include/xtensor/xoptional_assembly_base.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xscalar.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrides.hpp
- include/xtensor/xview.hpp
- test/test_common.hpp
- test/test_xarray.cpp
- test/test_xarray_adaptor.cpp
- test/test_xbuilder.cpp
- test/test_xfunction.cpp
- test/test_xindex_view.cpp
- test/test_xoptional_assembly.cpp
- test/test_xreducer.cpp
- test/test_xstrided_view.cpp
- test/test_xtensor.cpp
- test/test_xtensor_adaptor.cpp
- test/test_xview.cpp
> unchecked method implemented

- include/xtensor/xio.hpp
- include/xtensor/xslice.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrides.hpp
- test/CMakeLists.txt
- test/files/cppy_source/test_xstrided_view_extended.cppy
- test/files/preprocess.py
- test/test_xstrided_view.cpp
- test/test_xstrided_view_extended.cpp
> Xnegative slice

- include/xtensor/xview.hpp
- test/test_xview.cpp
Fixes #872
EDIT: this actually also fixes #897 , there is an error in the code snippet leading to a legit segfault.
> xview_stepper with implicit xt::all bug fix

- docs/source/changelog.rst
- docs/source/view.rst
> docs and changelog updated

- include/xtensor/xoperation.hpp
- test/test_xoperation.cpp
@wolfv this should fix the problem in `step_simd` too.
> simd activated for conditional ternary functor

- docs/source/external-structures.rst
Documentation only, CI can be skipped.
> extended xtensor doc fixed

- benchmark/CMakeLists.txt
- benchmark/benchmark_random.cpp
- include/xtensor/xassign.hpp
- include/xtensor/xbuilder.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xrandom.hpp
- include/xtensor/xutils.hpp
Random can make use of the faster `assign_to` mechanism as well.
> Faster random

- include/xtensor/xnorm.hpp
- test/test_xnorm.cpp
Add the immediate reducer stuff to the norms.
Needs tests + docs.
> Norm immediate reducer

- CMakeLists.txt
- include/xtensor/xoptional_assembly.hpp
- include/xtensor/xoptional_assembly_base.hpp
- include/xtensor/xoptional_assembly_storage.hpp
- test/CMakeLists.txt
- test/test_xoptional_assembly.cpp
- test/test_xoptional_assembly_storage.cpp
> xoptional_assembly_base storage type

- include/xtensor/xfixed.hpp
- include/xtensor/xreducer.hpp
- test/test_xfixed.cpp
- test/test_xreducer.cpp
And improve  fix xtensor fixed stride computation
> fix immediate reducers with 0 strides,

- docs/source/changelog.rst
- include/xtensor/xstrided_view.hpp
documentation and typedef added for backward compatibility.
> changelog updated

- test/CMakeLists.txt
> cmake fix for Intel compiler on Windows

- include/xtensor/xnoalias.hpp
- include/xtensor/xsemantic.hpp
- test/test_xnoalias.cpp
> add missing operators to noalias

- include/xtensor/xslice.hpp
- test/test_xview.cpp
@JohanMabille @gte620v 
fixes https://github.com/QuantStack/xtensor/issues/941
and https://github.com/QuantStack/xtensor/issues/944
> add ability to use negative indices in keep slice

- include/xtensor/xfixed.hpp
- test/test_xfixed.cpp
We could make a benchmark to check if we're loosing performance with this change.
> homogenize xfixed constructors

- docs/source/numpy.rst
- include/xtensor/xmath.hpp
- test/test_xmath.cpp
> Renaming count_nonzeros in count_nonzero

- include/xtensor/xslice.hpp
Was not compiling on linux without
> add missing <map> include

- include/xtensor/xview.hpp
> added missing include in xview.hpp

- CMakeLists.txt
- include/xtensor/xfunction.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xoperation.hpp
- include/xtensor/xoptional.hpp
- include/xtensor/xtensor_simd.hpp
- test/test_xmath.cpp
> simd refactoring

- docs/source/api/xstrided_view.rst
- docs/source/api/xview.rst
- docs/source/view.rst
- include/xtensor/xcontainer.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xstrides.hpp
- include/xtensor/xview.hpp
> code cleanup and doc

- docs/source/api/xexpression.rst
- docs/source/api/xfunction.rst
- docs/source/closure-semantics.rst
- include/xtensor/xexpression.hpp
- include/xtensor/xmath.hpp
- test/CMakeLists.txt
- test/test_xexpression.cpp
This enables easy sharing of xexpressions
> Shared xexpression + automatic xclosure detection

- include/xtensor/xdynamic_view.hpp
- include/xtensor/xexpression.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xindex_view.hpp
- include/xtensor/xstrided_view_base.hpp
- include/xtensor/xview.hpp
- test/test_xexpression.cpp
> xshared_expression fix

- include/xtensor/xfunction.hpp
- include/xtensor/xoperation.hpp
- include/xtensor/xoptional.hpp
- test/test_xoptional.cpp
This requires a patch in xsimd to build.
> functor return value fixed

- include/xtensor/xutils.hpp
Small change. Saw it while looking at code.
> [xutils] forward a universal reference

- include/xtensor/xassign.hpp
- include/xtensor/xbroadcast.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xshape.hpp
Will describe this in detail tomorrow!
> Static broadcasting check for fixed sizes 

- include/xtensor/xcomplex.hpp
- include/xtensor/xmath.hpp
- test/test_xcomplex.cpp
> add simd apply to some complex functors

- include/xtensor/xsort.hpp
- include/xtensor/xstorage.hpp
- test/test_xsort.cpp
Some small-ish issues that came up.
> fix shape type in argmin, and svector growth

- benchmark/benchmark_view_access.cpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xstrides.hpp
needs benchmark.
I'll try to justify this change with the GooseFEM benchmark.
> add layout to unchecked data offset

- include/xtensor/xoptional.hpp
> perfect forwarding in xoptional_function constructor

- include/xtensor/xfixed.hpp
- test/test_xfixed.cpp
> XTENSOR_ASSERT fixed on Windows

- test/test_xsort.cpp
> Added test-case for setdiff1d

- include/xtensor/xmath.hpp
- test/test_xmath.cpp
Addresses issue: https://github.com/QuantStack/xtensor/issues/1106
> Allow multiple return type reducer functions

- include/xtensor/xoptional_assembly_base.hpp
fixes https://github.com/QuantStack/xtensor/issues/1083
> remove data_element from xoptional

- include/xtensor/xcontainer.hpp
- include/xtensor/xtensor.hpp
- test/test_xtensor.cpp
> xtensor default constructor and scalar assign fixed

- include/xtensor/xstrided_view.hpp
- test/test_xview.cpp
@hajdugabesz this should fix your issue
> inner_strides_type imported in xstrided_view

- docs/source/closure-semantics.rst
> Reflect XTL renaming

- include/xtensor/xassign.hpp
- include/xtensor/xbroadcast.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xdynamic_view.hpp
- include/xtensor/xexpression.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xfunctor_view.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xindex_view.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xoptional_assembly_base.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xscalar.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrided_view_base.hpp
- include/xtensor/xview.hpp
This is basically method renaming and code homogeneization, however this is a backward incompatible change, so when this is merged, we are on the rails for 0.18.0
> Assign and trivial_broadcast refactoring

- .travis.yml
Fixes the failures we saw with TBB in CI
> use tbb-devel requirement for CI

- docs/source/developer/implementation_classes.rst
> Type shpae -> shape

- include/xtensor/xdynamic_view.hpp
- include/xtensor/xslice.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrided_view_base.hpp
- test/test_xdynamic_view.cpp
Fixes #1167 and adds required features for xframe.
> slices improvement

- include/xtensor/xslice.hpp
- test/test_xview.cpp
> Fixed xdrop_slice

- include/xtensor/xoptional_assembly_storage.hpp
@martinRenou you might want to review this ?
> fix call of const overload in assembly storage

- include/xtensor/xsort.hpp
- test/test_xsort.cpp
> argmax on axis with single element fixed

- include/xtensor/xstrided_view.hpp
- test/test_xstrided_view.cpp
> Added missing assign operator in xstrided_view

- include/xtensor/xview.hpp
- test/test_xview.cpp
> Fixup xview assignment

- docs/source/api/io_index.rst
- docs/source/api/xcsv.rst
- docs/source/api/xio.rst
- docs/source/api/xjson.rst
- docs/source/api/xnpy.rst
- docs/source/numpy.rst
> add xio docs

- docs/source/installation.rst
> adde precisions to the installation instructions

- docs/source/api/xtensor.rst
- include/xtensor/xoperation.hpp
- include/xtensor/xtensor.hpp
Let me know what you think!
Fixes #1236
> Implemented 'from_indices'

- include/xtensor/xbuilder.hpp
- include/xtensor/xrandom.hpp
- test/test_xview.cpp
> Replaces auto& with auto&& in assign_to

- include/xtensor/xmanipulation.hpp
- test/test_xmanipulation.cpp
> default layout parameter for ravel function

- include/xtensor/xview.hpp
- test/test_xview.cpp
checking which compilers are having trouble.
> add view_view assignment test to see where it fails

- docs/source/file_loading.rst
- docs/source/getting_started.rst
- docs/source/index.rst
- docs/source/indices.rst
- docs/source/numpy-differences.rst
- docs/source/numpy.rst
- docs/source/operator.rst
- docs/source/related.rst
- docs/source/view.rst
Started documentation of indices, fixes #1309, see PR #1300. 
I could use help, in terms of general feedback, but also because I have never really understand why a ``std::vector`` is used.
> [docs] indices

- docs/source/numpy-differences.rst
> Updated differences with numpy section

- docs/source/build-options.rst
- docs/source/developer/concepts.rst
- docs/source/expression.rst
- include/xtensor/xaccumulator.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xfunctor_view.hpp
- include/xtensor/xiterable.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xmanipulation.hpp
- include/xtensor/xoptional_assembly_base.hpp
- include/xtensor/xscalar.hpp
- include/xtensor/xsort.hpp
- include/xtensor/xstrided_view_base.hpp
- include/xtensor/xtensor_config.hpp
- include/xtensor/xtensor_forward.hpp
- include/xtensor/xview.hpp
- test/test_extended_xmath_reducers.cpp
- test/test_xaccumulator.cpp
- test/test_xfunctor_adaptor.cpp
- test/test_xsort.cpp
- test/test_xview.cpp
> Decouple XTENSOR_DEFAULT_LAYOUT from XTENSOR_DEFAULT_TRAVERSAL

- include/xtensor/xstrided_view_base.hpp
- test/test_xdynamic_view.cpp
Hi @hajdugabesz, could you check if this fixes https://github.com/QuantStack/xtensor/issues/1349 for you? 
It did for me!
> fix dynamic_view on view keep_slice issue

- include/xtensor/xview.hpp
- test/test_xview.cpp
> fix xview on xtensor_fixed

- include/xtensor/xmime.hpp
> Fix rich display

- docs/source/adaptor.rst
- docs/source/api/xarray_adaptor.rst
- docs/source/api/xtensor_adaptor.rst
- docs/source/numpy-differences.rst
- include/xtensor/xadapt.hpp
- test/test_xadapt.cpp
> Adaptors for C stack-allocated arrays

- docs/source/operator.rst
- include/xtensor/xreducer.hpp
- test/test_xreducer.cpp
> reduce now accepts a single reducing function

- include/xtensor/xindex_view.hpp
This might fix #1390 @JohanMabille
> add xsemantic include to index_view

- include/xtensor/xbuilder.hpp
Correction for issue #1405.
I just tested that the program given there works, not the full testsuite.
> Correct eye with negative index.

- docs/source/adaptor.rst
- docs/source/api/xarray_adaptor.rst
- include/xtensor/xadapt.hpp
> add documentation for smart ptr adapt

- include/xtensor/xshape.hpp
- test/test_xshape.cpp
Not sure if the tests would be better suited elsewhere but I'm open to suggestions!
> Implemented xcommon_tensor_t with tests

- include/xtensor/xcontainer.hpp
- include/xtensor/xoptional_assembly_base.hpp
- test/test_common.hpp
> reshape now accepts initializer_list parameter

- .appveyor.yml
- include/xtensor/xutils.hpp
- include/xtensor/xview.hpp
- test/test_xfunction.cpp
- test/test_xutils.cpp
> Fixed noexcept specifier

- include/xtensor/xslice.hpp
- test/test_xview.cpp
> view now accepts lvalue slices

- docs/source/developer/concepts.rst
- docs/source/expression.rst
- include/xtensor/xcontainer.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xstrided_view_base.hpp
- include/xtensor/xstrides.hpp
- include/xtensor/xtensor.hpp
- include/xtensor/xutils.hpp
- include/xtensor/xview.hpp
- test/test_xarray.cpp
- test/test_xfunction.cpp
- test/test_xtensor.cpp
- test/test_xview.cpp
Does anybody have time to give me some initial feedback?
> Added periodic indices

- include/xtensor/xbuilder.hpp
- test/test_xbuilder.cpp
> fixed linspace corner case

- CMakeLists.txt
- docs/source/quickref/basic.rst
- include/xtensor/xcontainer.hpp
> Added warning in resize documentation

- docs/source/expression.rst
- include/xtensor/xcontainer.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xstrided_view_base.hpp
- include/xtensor/xstrides.hpp
- include/xtensor/xview.hpp
- test/test_xarray.cpp
- test/test_xfunction.cpp
- test/test_xtensor.cpp
- test/test_xview.cpp
> Added `in_bounds`

- CMakeLists.txt
- include/xtensor/xaccessible.hpp
- include/xtensor/xarray.hpp
- include/xtensor/xbroadcast.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xdynamic_view.hpp
- include/xtensor/xfixed.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xfunctor_view.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xmasked_view.hpp
- include/xtensor/xreducer.hpp
- include/xtensor/xscalar.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrided_view_base.hpp
- include/xtensor/xstrides.hpp
- include/xtensor/xtensor.hpp
- include/xtensor/xview.hpp
> Added xaccesible base class

- include/xtensor/xstrided_view.hpp
> Removed deprecated type slice_vector

- include/xtensor/xbuilder.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xview.hpp
- test/test_extended_xsort.cpp
- test/test_xnpy.cpp
- test/test_xrandom.cpp
- test/test_xreducer.cpp
- test/test_xsort.cpp
> Removed warnings

- include/xtensor/xaccessible.hpp
- include/xtensor/xoptional_assembly_base.hpp
> Added periodic and in_bounds methods in xoptional_assembly_base

- docs/source/changelog.rst
> Updated changelog

- include/xtensor/xsort.hpp
- test/test_xsort.cpp
> Fixed flatten_sort_result_type

- include/xtensor/xsort.hpp
- test/test_xsort.cpp
> Fixed unique with expressions not defining temporary_type

- include/xtensor/xdynamic_view.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrided_view_base.hpp
@tdegeus Can you confirm this PR fixes the problem introduced by the commit f34e1c2?
> Fixed xstrided_view_base constructor

- include/xtensor/xstrided_view_base.hpp
- include/xtensor/xstrides.hpp
- include/xtensor/xview.hpp
- test/test_xstrides.cpp
> do_match_strides now accepts base stride value

- include/xtensor/xstrided_view.hpp
- include/xtensor/xview.hpp
> Fixed xview::inner_backstrides_type

- include/xtensor/xslice.hpp
> slice_implementation_getter now forwards its slice argument

- include/xtensor/xmime.hpp
- test/CMakeLists.txt
- test/test_xmime.cpp
> Fixup forward declaration for xreducer

- include/xtensor/xsemantic.hpp
- include/xtensor/xview.hpp
- test/test_xview.cpp
> fix special case of view iteration

- include/xtensor/xassign.hpp
- include/xtensor/xbroadcast.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xscalar.hpp
- test/test_xbroadcast.cpp
Fixes #1492.
Fixes https://github.com/QuantStack/xtensor-r/issues/103
> Fix xbroadcast linear assign

- include/xtensor/xmanipulation.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrided_view_base.hpp
- test/files/xio_expected_results.hpp
- test/test_xio.cpp
- test/test_xmanipulation.cpp
- test/test_xstrided_view.cpp
> Strided view fixes

- docs/source/view.rst
- include/xtensor/xslice.hpp
> Improved range documentation

- include/xtensor/xbuffer_adaptor.hpp
- include/xtensor/xmanipulation.hpp
- include/xtensor/xutils.hpp
- test/test_xmanipulation.cpp
- test/test_xstrided_view.cpp
- test/test_xview.cpp
> Fixed ravel and flatten implementations

- include/xtensor/xfixed.hpp
- test/test_xfixed.cpp
> Fixed xfixed_adaptor temporary assign

- include/xtensor/xsort.hpp
- test/test_xsort.cpp
> Fixed argmax for expressions with strides 0

- include/xtensor/xbuffer_adaptor.hpp
Fixes xfile issue with default constructor not found.
> Buffer adaptor default constructor

- include/xtensor/xmath.hpp
- test/test_xmath.cpp
> Bugfix: amax

- include/xtensor/xfunction.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xscalar.hpp
> Removed return value from step_leading

- include/xtensor/xbuilder.hpp
- test/test_xbuilder.cpp
> Fixed assign_to for arange on double

- include/xtensor/xcontainer.hpp
- include/xtensor/xsort.hpp
- test/test_xsort.cpp
> Fixed argsort in column_major

- .appveyor.yml
- .travis.yml
- include/xtensor/xbuilder.hpp
- include/xtensor/xcomplex.hpp
- include/xtensor/xfunctor_view.hpp
- include/xtensor/xoffset_view.hpp
- test/test_xcomplex.cpp
- test/test_xoptional.cpp
> Fixed real, imag and functor_view

- include/xtensor/xdynamic_view.hpp
- include/xtensor/xmanipulation.hpp
- include/xtensor/xoptional.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrided_view_base.hpp
- test/test_xmanipulation.cpp
- test/test_xstrided_view.cpp
> Strided views refactoring

- test/test_xcomplex.cpp
> Added complex exponential test

- include/xtensor/xiterator.hpp
- test/test_xstrided_view.cpp
> Fixed iterator incremented or decremented by 0

- include/xtensor/xnorm.hpp
- test/test_xcomplex.cpp
- test/test_xnorm.cpp
> Fixed norm return type for complex

- include/xtensor/xassign.hpp
- include/xtensor/xfunction.hpp
- include/xtensor/xsemantic.hpp
- include/xtensor/xstrides.hpp
- test/test_xfunction.cpp
- test/test_xstrides.cpp
> Fixed broadcasting of shape containing 0-sized dimensions

- include/xtensor/xview.hpp
- test/test_xview.cpp
> Fixed xview::element for range with more elements than view's dimension

- include/xtensor/xreducer.hpp
- test/test_xreducer.cpp
> Fixed reducers on expression with shape containing 1 as first elements

- include/xtensor/xstrided_view_base.hpp
- test/test_xstrided_view.cpp
> Fixed return type of data in xstrided_view

- include/xtensor/xreducer.hpp
- test/test_xreducer.cpp
> Fixed reducers with empty list of axes

- include/xtensor/xstrided_view.hpp
> Remove unused type alias

- include/xtensor/xdynamic_view.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrided_view_base.hpp
- test/test_xstrided_view.cpp
> strided views constructors forward shape argument

- docs/source/build-options.rst
- docs/source/getting_started.rst
candidate fix for https://github.com/QuantStack/xtensor/issues/1531
> add find_package(xsimd) in cmakelists for introductory documentation

- .appveyor.yml
- test/CMakeLists.txt
> tests can be built in debug mode

- include/xtensor/xcontainer.hpp
- include/xtensor/xtensor.hpp
This PR adds only very very minor spell checks in two places. Please feel free to ignore if its not worthwhile to add :-)
> Very minor spelling checks in comments

- include/xtensor/xstorage.hpp
- test/test_xreducer.cpp
> Added missing comparison operators for const_array

- include/xtensor/xdynamic_view.hpp
- include/xtensor/xexpression.hpp
- include/xtensor/xmanipulation.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xmime.hpp
- include/xtensor/xstrided_view.hpp
- include/xtensor/xstrided_view_base.hpp
- test/test_xmanipulation.cpp
- test/test_xstrided_view.cpp
> Reshape view assign

- docs/source/related.rst
> add z5 to related projects

- include/xtensor/xexpression.hpp
See https://github.com/QuantStack/Xtensor.R/issues/21
> Replace `auto` with explicit return type in `make_xshared()`

- include/xtensor/xpad.hpp
- include/xtensor/xview.hpp
- test/test_xview.cpp
> Made xconst_accessible::shape(size_type) visible in xview

- docs/source/api/xrandom.rst
- docs/source/builder.rst
- docs/source/pitfall.rst
> add warnings for random number generation

- include/xtensor/xbuilder.hpp
- test/test_xbuilder.cpp
> Fixed reverse arange

- include/xtensor/xassign.hpp
- test/test_xview.cpp
> Added overload of is_linear for expressions without strides method

- include/xtensor/xstorage.hpp
- test/test_xview.cpp
> Made sequence_view convertible to arbitrary sequence type providing iterators

- docs/source/view.rst
- include/xtensor/xshape.hpp
> Improved index_view examples

- include/xtensor/xbuilder.hpp
- include/xtensor/xexception.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xstrided_view_base.hpp
- test/test_xbuilder.cpp
> Error case handling in concatenate

- include/xtensor/xexception.hpp
correction : detial to detail.
> Fixing a typo

- include/xtensor/xindex_view.hpp
- include/xtensor/xoperation.hpp
- test/test_xindex_view.cpp
> Added traversal order to argwhere and filter

- include/xtensor/xio.hpp
- test/test_xio.cpp
> Reset stream's flags after output operation

- include/xtensor/xaccumulator.hpp
- test/test_xaccumulator.cpp
> Fixed accumulator for empty arrays

- include/xtensor/xmath.hpp
- test/test_xmath.cpp
> Use temporary_type in implementation of xt::diff

- include/xtensor/xmath.hpp
- include/xtensor/xreducer.hpp
- test/test_xreducer.cpp
> Fixed reducers on empty arrays

- .vscode/settings.json
- docs/source/api/xrandom.rst
- docs/source/builder.rst
- include/xtensor/xrandom.hpp
- test/test_xrandom.cpp
Implemented xtensor wrapper to distributions in <random> as requested in Issue https://github.com/QuantStack/xtensor/issues/1449
> Distributions

- include/xtensor/xreducer.hpp
- test/test_xaccumulator.cpp
- test/test_xreducer.cpp
> Fixed reducers: passing the same axis many times now throws

- include/xtensor/xmath.hpp
This is meant to solve #1743. 
Now the implementation is based on my original proposal. I will change it once we conclude the discussion.
> Improve return_value type for nanmean

- include/xtensor/xassign.hpp
- include/xtensor/xtensor_simd.hpp
- test/CMakeLists.txt
- test/test_xview.cpp
> Fixed container_simd_return_type

- include/xtensor/xtensor_simd.hpp
- test/test_xoperation.cpp
> Fixed has_simd_interface for non existing simd_return_type

- include/xtensor/xmath.hpp
Compliance with NumPy's default. Fixes #1770
> Added average overload for default equal weights

- include/xtensor/xassign.hpp
- test/test_xoperation.cpp
> Disabled simd assignment when bool conversion occurs

- include/xtensor/xassign.hpp
- test/test_xcomplex.cpp
Fixes #1827 
cc @emmenlau @shekharshank
> Fixed assignment of scalar to complex

- include/xtensor/xmasked_view.hpp
- test/test_xmasked_view.cpp
> Added missing assign operator in xmasked_view

- docs/source/api/xmanipulation.rst
- include/xtensor/xmanipulation.hpp
- include/xtensor/xoperation.hpp
- include/xtensor/xreducer.hpp
- test/test_xaccumulator.cpp
- test/test_xmanipulation.cpp
- test/test_xoperation.cpp
> Removed circular dependencies

- .travis.yml
- include/xtensor/xstorage.hpp
> Removed allocator deprecated calls

- .github/PULL_REQUEST_TEMPLATE.md
- include/xtensor/xcontainer.hpp
- test/test_common.hpp
- test/test_xarray.cpp
- test/test_xtensor.cpp
> Fixed reshape with signed integers

- README.md
- benchmark/benchmark_views.cpp
> Fixup URLs

- docs/source/view.rst
> Fixup typo in documentation

- include/xtensor/xmath.hpp
- test/test_xmath.cpp
I'm not sure where to group the documentation to.
> add covariance function

- include/xtensor/xstrided_view_base.hpp
Should fix #1900 
@emmenlau do you have the opportunity to test this branch?
> Fixed issue due to thread_local storage on some architectures

- include/xtensor/xutils.hpp
> Fixed cxx11 lib guard

- include/xtensor/xutils.hpp
Fixes #1926.
@tort-dla-psa can you confirm this fixes the issue?
> Fixed CXX11 ABI when _GLIBCXX_USE_DUAL_ABI is set to 0

- include/xtensor/xstorage.hpp
> Enabling array-bounds warning

- include/xtensor/xaxis_iterator.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xmime.hpp
- include/xtensor/xpad.hpp
- include/xtensor/xstorage.hpp
- test/test_xaxis_iterator.cpp
- test/test_xpad.cpp
> Fixed warnings

- include/xtensor/xbroadcast.hpp
- include/xtensor/xshape.hpp
- test/test_xbroadcast.cpp
> broadcast function now accepts fixed shapes

- include/xtensor/xio.hpp
> Don't print decimal point after inf or nan

- include/xtensor/xpad.hpp
> Improved performance of xt::tile

- docs/environment.yml
> Switched to channel QuantStack

- .appveyor.yml
- .azure-pipelines/azure-pipelines-win.yml
- include/xtensor/xbuilder.hpp
- test/test_xadaptor_semantic.cpp
- test/test_xcontainer_semantic.cpp
- test/test_xiterator.cpp
- test/test_xnoalias.cpp
- test/test_xoperation.cpp
- test/test_xscalar_semantic.cpp
- test/test_xview_semantic.cpp
> Removed warnings due to gtest upgrade

- include/xtensor/xbuffer_adaptor.hpp
- include/xtensor/xmanipulation.hpp
- test/test_xmanipulation.cpp
> Fixed flatten view of view

- docs/source/expression.rst
- docs/source/operator.rst
Improved documentation based on feddbacks from #1955 
Only the documentation is changed, no need to wait for the CI.
> Improved narrative documentation of reducers

- test/test_xio.cpp
> Add test for printing xarray of type size_t

- include/xtensor/xreducer.hpp
- test/test_xreducer.cpp
Should fix some use cases from #1955
> Fixed element method of xreducer

- include/xtensor/xfunction.hpp
- test/test_xoperation.cpp
> Fixed cast for third-party types

- include/xtensor/xfunction.hpp
- include/xtensor/xoperation.hpp
- test/CMakeLists.txt
- test/test_xfunc_on_xexpression.cpp
fix https://github.com/xtensor-stack/xtensor/issues/1694
> fix xoperation

- docs/source/installation.rst
> Added installation instruction with MinGW

- include/xtensor/xsort.hpp
- test/test_xsort.cpp
> Fixed argpartition leading axis test

- .travis.yml
- CMakeLists.txt
- test/CMakeLists.txt
> Added tests with C++20 enabled

- docs/source/api/container_index.rst
- docs/source/api/xmanipulation.rst
- docs/source/api/xrepeat.rst
- docs/source/quickref/manipulation.rst
- include/xtensor/xmanipulation.hpp
- include/xtensor/xrepeat.hpp
> Added documentation for repeat

- include/xtensor/xsort.hpp
- test/test_xsort.cpp
> Fixed sort and partition

- docs/source/api/xview.rst
- docs/source/view.rst
- include/xtensor/xindex_view.hpp
- include/xtensor/xslice.hpp
- include/xtensor/xview.hpp
- test/test_xview.cpp
> xt::view now supports negative indices

- docs/source/quickref/basic.rst
Fix wrong value in documentation code example.
> Fix typo in doc

- .azure-pipelines/azure-pipelines-win.yml
> Upgraded azure-pipelines to vs2017-win2016

- include/xtensor/xbroadcast.hpp
- include/xtensor/xoptional.hpp
- include/xtensor/xrepeat.hpp
> Added extension base to repeat and cleaned up xbroadcast

- docs/source/quickref/iterator.rst
> (docs) Fix wrong output in `iterator` page.

- CMakeLists.txt
This fixes the issue mentionned in #2008
> Added missing header to CMakeLists.txt

- docs/source/quickref/basic.rst
- include/xtensor/xview.hpp
- test/test_xview.cpp
> Fixed xview on const keep and const drop slices

- docs/source/api/reducing_functions.rst
- docs/source/pitfall.rst
- include/xtensor/xmath.hpp
According to what was said in #2005
> Improved reducer function documentation

- include/xtensor/xadapt.hpp
> Added static_assert to adapt methods

- include/xtensor/xstorage.hpp
- test/test_xstorage.cpp
> Added missing overload of push_back

- .azure-pipelines/azure-pipelines-osx.yml
> Fixed azure-pipelines

- include/xtensor/xfunction.hpp
> Fixing compiler warning

- include/xtensor/xrepeat.hpp
> Removing unused parameter

- CMakeLists.txt
> Writing single include header

- docs/source/api/xrandom.rst
- docs/source/histogram.rst
- docs/source/index.rst
- docs/source/numpy.rst
- docs/source/random.rst
> Adding details for xt::random to docs

- include/xtensor/xfunction.hpp
- include/xtensor/xmath.hpp
> Fixing compiler warnings

- .azure-pipelines/azure-pipelines-win.yml
- .gitignore
> Fixed build with clang-cl

- docs/source/api/xarray_adaptor.rst
- docs/source/api/xtensor_adaptor.rst
- include/xtensor/xadapt.hpp
- test/test_xadapt.cpp
> adapt_smart_ptr overlads accepting STL-like container as shape

- docs/source/container.rst
> Typo fix: "whis" -> "this"

- include/xtensor/xtensor_forward.hpp
> Typo fix: "tnesor" -> "tensor" and "Wether" -> "Whether".

- docs/source/related.rst
> Removing spurious "Python code" from a code block.

- include/xtensor/xbuilder.hpp
Fix the second example described in **#2059**.
> Fix xt::arange for unsigned step size

- include/xtensor/xmath.hpp
> Improved var and stddev performance

- docs/source/pitfall.rst
Documentation only, no need to wait for the CI.
> Documented fixed_shape weird bug on Windows

- include/xtensor/xbuilder.hpp
Some examples in the code were not commented out.
Removed some trailing spaces.
> Add comments

- docs/source/getting_started.rst
> How to print shape

- docs/source/container.rst
Documentation only, no need to wait for CI.
> Improved aliasing documentation

- include/xtensor/xscalar.hpp
> Added missing typedef in xscalar_stepper

- include/xtensor/xchunked_array.hpp
- test/test_xchunked_array.cpp
> Inherit xaccessible

- include/xtensor/xchunked_array.hpp
- test/test_xchunked_array.cpp
> Inherit xiterable

- include/xtensor/xchunked_array.hpp
- test/test_xchunked_array.cpp
> Fix assignment operator

- include/xtensor/xchunked_array.hpp
> Add constructor from xexpression and chunk_shape

- include/xtensor/xchunked_array.hpp
- test/test_xchunked_array.cpp
This test reveals a bug in the "chunked constructor".
> Fix chunk layout

- docs/source/closure-semantics.rst
> fix typo in the documentation of closure semantics

- include/xtensor/xchunk_store_manager.hpp
- include/xtensor/xchunked_array.hpp
- include/xtensor/xdisk_io_handler.hpp
- include/xtensor/xfile_array.hpp
- test/test_xchunked_array.cpp
> Implement chunk pool in xchunk_store_manager

- include/xtensor/xchunked_array.hpp
> xchunked_array code cleanup

- include/xtensor/xchunk_store_manager.hpp
- include/xtensor/xchunked_array.hpp
> xchunk_store_manager code cleanup

- docs/source/bindings.rst
> fixed sturct typo in bindings.rst doc

- include/xtensor/xchunk_store_manager.hpp
- include/xtensor/xchunked_array.hpp
- include/xtensor/xfile_array.hpp
> Refactored xfile_array.hpp

- include/xtensor/xfile_array.hpp
> Added simd accessors to xfile_array_container

- include/xtensor/xchunk_store_manager.hpp
- include/xtensor/xcsv.hpp
- include/xtensor/xdisk_io_handler.hpp
- include/xtensor/xfile_array.hpp
- test/test_xchunked_array.cpp
> Abstract file format through a format class

- include/xtensor/xchunked_array.hpp
> Add xchunked_array extension template

- include/xtensor/xcsv.hpp
- include/xtensor/xdisk_io_handler.hpp
> Refactored xdisk_io_handler

- include/xtensor/xchunk_store_manager.hpp
- include/xtensor/xdisk_io_handler.hpp
- include/xtensor/xfile_array.hpp
- test/test_xchunked_array.cpp
> Fix exception for file write operation

- .azure-pipelines/azure-pipelines-win.yml
- CMakeLists.txt
- environment-dev.yml
- include/xtensor/zarray.hpp
- test/CMakeLists.txt
- test/test_zarray.cpp
> Implemented xdyn_array

- CMakeLists.txt
- include/xtensor/zarray.hpp
- include/xtensor/zarray_impl.hpp
- include/xtensor/zdispatcher.hpp
- include/xtensor/zfunction.hpp
- include/xtensor/zmath.hpp
- test/test_zarray.cpp
> Skeleton of the dynamic expression system

- include/xtensor/zdispatcher.hpp
- include/xtensor/zfunction.hpp
- test/test_zarray.cpp
> Implemented allocate_result in zfunction

- include/xtensor/xchunk_store_manager.hpp
> Add new class to deal with indexes to path transformation

- include/xtensor/zdispatcher.hpp
- include/xtensor/zfunction.hpp
- include/xtensor/zmath.hpp
- test/test_zarray.cpp
> zfunction refactoring

- docs/source/bindings.rst
- docs/source/builder.rst
- docs/source/closure-semantics.rst
- docs/source/compilers.rst
- docs/source/container.rst
- docs/source/dev-build-options.rst
- docs/source/expression.rst
- docs/source/histogram.rst
- docs/source/indices.rst
- docs/source/view.rst
> [docs] Running spell-check

- docs/source/index.rst
- docs/source/sfinae.rst
- include/xtensor/xarray.hpp
- include/xtensor/xfixed.hpp
- include/xtensor/xtensor.hpp
- include/xtensor/xutils.hpp
- include/xtensor/xview.hpp
- test/CMakeLists.txt
- test/test_sfinae.cpp
> Adding static const rank to allow sfinae based on rank

- include/xtensor/xchunk_store_manager.hpp
> Remove leftover

- include/xtensor/xaxis_slice_iterator.hpp
- include/xtensor/xchunk_store_manager.hpp
- include/xtensor/xchunked_array.hpp
- include/xtensor/xslice.hpp
- test/test_xmath_result_type.cpp
- test/test_xnan_functions.cpp
- test/test_xreducer.cpp
- test/test_xview.cpp
> Removed conversion and initialization warnings

- include/xtensor/zarray.hpp
- include/xtensor/zarray_impl.hpp
- include/xtensor/zassign.hpp
- include/xtensor/zdispatcher.hpp
- include/xtensor/zfunction.hpp
- include/xtensor/zmath.hpp
- test/CMakeLists.txt
- test/test_zarray.cpp
> zfiles namespace renamed

- CMakeLists.txt
> Removed zheaders from single header

- include/xtensor/xstorage.hpp
- test/test_xstorage.cpp
> Implemented insertion of range and intializer list in svector

- CMakeLists.txt
- include/xtensor/zarray.hpp
- include/xtensor/zarray_impl.hpp
- include/xtensor/zassign.hpp
- include/xtensor/zdispatcher.hpp
- include/xtensor/zdispatching_types.hpp
- include/xtensor/zfunction.hpp
- include/xtensor/zmath.hpp
- test/CMakeLists.txt
- test/test_zarray.cpp
> Zrefactoring

- docs/source/random.rst
> [docs] Extending docs random

- include/xtensor/zarray.hpp
- test/test_xfunction.cpp
> Fix zarray initialization from zarray

- include/xtensor/xnpy.hpp
No need to have it non-portable just for the sake of being constexpr, especially
as both gcc and clang fold the result at -O2.
> Portable and generic implementation of endianess detection

- include/xtensor/xchunk_store_manager.hpp
- include/xtensor/xchunked_array.hpp
- test/test_xchunked_array.cpp
> Add specific xchunked_array constructor for xchunk_store_manager

- include/xtensor/xchunked_array.hpp
> Fixed constructors of xchunked_array

- include/xtensor/xchunked_array.hpp
- include/xtensor/xfile_array.hpp
> Don't mark dirty a resized or reshaped xfile_array

- include/xtensor/zarray.hpp
> Replaced catch-all constructor of zarray with more restrictive ones

- include/xtensor/xchunked_array.hpp
> Fixed SFINAE based on xchunked_store_manager

- include/xtensor/xchunk_store_manager.hpp
- include/xtensor/xchunked_array.hpp
> Add set_chunk_shape to the first chunk of the pool

- include/xtensor/xchunked_array.hpp
- include/xtensor/xsemantic.hpp
- test/test_xchunked_array.cpp
> Refactored xchunked_array semantic

- include/xtensor/xcontainer.hpp
- test/CMakeLists.txt
- test/test_xcomplex.cpp
> Fixed load_simd for xcomplex

- include/xtensor/xadapt.hpp
- include/xtensor/xassign.hpp
- include/xtensor/xbuilder.hpp
- include/xtensor/xcontainer.hpp
- include/xtensor/xgenerator.hpp
- include/xtensor/xhistogram.hpp
- include/xtensor/xio.hpp
- include/xtensor/xmanipulation.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xnorm.hpp
- include/xtensor/xpad.hpp
- include/xtensor/xrandom.hpp
- include/xtensor/xslice.hpp
- include/xtensor/xsort.hpp
- include/xtensor/xstrides.hpp
- include/xtensor/xutils.hpp
- include/xtensor/xview.hpp
- include/xtensor/xview_utils.hpp
Added xtl traits to keep up with pull request in [xtl](https://github.com/xtensor-stack/xtl/pull/218)
> changed std traits to new xtl::xtraits

- docs/source/index.rst
- docs/source/sfinae.rst
- docs/source/xsimd.rst
- include/xtensor/xstorage.hpp
- include/xtensor/xtensor_config.hpp
- test/CMakeLists.txt
- test/test_xsimd.cpp
> Adding macro XTENSOR_SELECT_ALIGN

- include/xtensor/xchunked_array.hpp
> Add chunk_memory_layout to chunked_array factory

- include/xtensor/xchunked_array.hpp
> Fix call to resize of chunk container

- docs/source/api/chunked_array.rst
- docs/source/api/container_index.rst
- docs/source/index.rst
- docs/source/quickref/basic.rst
- docs/source/quickref/chunked_arrays.rst
- include/xtensor/xchunked_array.hpp
> Document chunked arrays

- docs/environment.yml
> Fixup docs build

- include/xtensor/xmasked_view.hpp
- include/xtensor/xmath.hpp
- include/xtensor/xview.hpp
- test/test_xnpy.cpp
Fix a bunch of warnings that pollute the output when compiling xtensor ;-)
> Fix various warnings

- include/xtensor/xfixed.hpp
Found this heuristically, would be good to check!
> Added missing header in xfixed

- docs/environment.yml
> Pins breathe 4.16.0 in docs/environment.yml

- test/test_xreducer.cpp
Add tests on reducers.
Focus on optional arrays, including `xt::xarray<xtl::xoptional<T>>`,  `xt::xoptional<T>` and `xt::xoptional_assembly<xt::xarray<T>, xt::xarray<bool>>`.
The tests that are currently failing, mainly due to assignment issue, are commented.
> Add reducers tests

- include/xtensor/xchunked_array.hpp
- test/test_xcomplex.cpp
Nothing really important here :-)
> Fix minor warnings detected by clang

- include/xtensor/xeval.hpp
- include/xtensor/xlayout.hpp
> Moved layout_remove_any to xlayout.hpp

- docs/source/operator.rst
- docs/source/quickref/reducer.rst
Documentation only, no need to wait for the CI.
> Updated reducer docs according to recent changes

- .github/workflows/gh-pages.yml
- .gitignore
- README.md
- docs/Doxyfile
- docs/environment.yaml
Fixes https://github.com/xtensor-stack/xtensor/issues/2301
> Publishing doxygen docs to GitHub pages

- README.md
> Update readme to recommend conda over conan

- include/xtensor/xexpression.hpp
- include/xtensor/xiterator.hpp
- include/xtensor/xstrided_view.hpp
- test/test_xstrided_view.cpp
> Added can_assign and enable_assignable_expression

- test/CMakeLists.txt
- test/files/cppy_source/test_extended_xmath_reducers.cppy
- test/files/cppy_source/test_extended_xsort.cppy
- test/files/preprocess.py
- test/test_extended_broadcast_view.cpp
- test/test_extended_xhistogram.cpp
- test/test_extended_xmath_interp.cpp
- test/test_extended_xmath_reducers.cpp
- test/test_extended_xsort.cpp
- Fix the XTENSOR_PREPROCESS_FILES.
- Add a warning in the CMakeLists.text file.
- Fix manually modified tests.
As discussed in #2298. I regenerated all the test files to add the warning, and it is apparently that some of them have been manually modified in the past.
> Fix automatically generated tests.

- cmake/FindTBB.cmake
@zhujun98 Do you have the opportunity to test this on a system where an old version of TBB is already installed?
> Added fallback to old behavior in FindTBB.cmake

- docs/source/api/nan_functions.rst
- include/xtensor/xmath.hpp
- test/test_xnan_functions.cpp
Implemented `nanmin` and `nanmax`.
> Implement nanmin and nanmax

- include/xtensor/xmath.hpp
- test/test_xnan_functions.cpp
- Remove the leftover macro;
- Add more tests for return type check;
- Improve documentation.
A follow up for #2314
> Clean up and add more tests for nanmin and nanmax

- include/xtensor/xpad.hpp
- test/test_xpad.cpp
> Fixed ambiguous call of tile

- docs/source/api/nan_functions.rst
- include/xtensor/xmath.hpp
> Add missing API RTD for nan functions

- include/xtensor/xtensor.hpp
- test/test_xmanipulation.cpp
> xtensor_view assignment

- include/xtensor/xcontainer.hpp
- test/test_xadapt.cpp
- test/test_xview.cpp
> Fixed return type of data method

- include/xtensor/xbuffer_adaptor.hpp
- test/test_xmanipulation.cpp
> Fixed assignment to flatten view

- include/xtensor/xfunctor_view.hpp
- include/xtensor/xview.hpp
- test/test_xcomplex.cpp
> Fixed xfunctor_view

- include/xtensor/xchunked_array.hpp
> Fix edge chunk assignment

- environment.yml
> No need to explicitly install blas anymore with latest xtensor-blas

- include/xtensor/xstrides.hpp
- test/test_xstrides.cpp
Fixes xtensor-stack/xtl/issues/245, added a test.
> FIX for xtensor-stack/xtl/issues/245

- .azure-pipelines/azure-pipelines-linux-gcc.yml
Thie PR fixes the issue on Azure due to the recente changes described [here](https://github.com/actions/virtual-environments/issues/2950)
> Explicitely install gcc7 and gcc8 on Azure

- CMakeLists.txt
- include/xtensor/xchunked_array.hpp
- include/xtensor/xchunked_assign.hpp
- include/xtensor/xchunked_view.hpp
- test/test_xchunked_view.cpp
> Refactoring of xchunked_view

- README.md
- docs/source/installation.rst
> Update installation instructions to mention mamba

- include/xtensor/xchunked_array.hpp
- include/xtensor/xchunked_assign.hpp
- include/xtensor/xchunked_view.hpp
- test/test_xchunked_array.cpp
> Added const chunk iterators

- include/xtensor/xchunked_assign.hpp
- test/test_xchunked_array.cpp
> Fixed chunk assignment

- include/xtensor/xchunked_assign.hpp
> Fixed chunked_iterator

- include/xtensor/xchunked_array.hpp
- include/xtensor/xchunked_view.hpp
> Specialize operator= when RHS is chunked

- include/xtensor/xexception.hpp
- test/test_xview.cpp
> Fixed check_index function

- include/xtensor/xhistogram.hpp
> Fixing `&` -> `&&` in histogram

- docs/source/index.rst
- docs/source/indices.rst
Fixes https://github.com/xtensor-stack/xtensor/issues/2375
> Adding description of index operators

- docs/source/api/xmath.rst
- include/xtensor/xmath.hpp
- test/test_xmath.cpp
> average: fixing overload issue for axis argument

- include/xtensor/xsort.hpp
> Updating docs argmin and argmax

- docs/source/quickref/builder.rst
> Update builder.rst : mistake in Diag Output

- test/CMakeLists.txt
- test/test_common_macros.hpp
- test/test_utils.hpp
- test/test_xbuilder.cpp
- test/test_xfunction.cpp
- test/test_xnan_functions.cpp
Fixes #2435 
@drew-parsons I don't have the time to go through the whole test suite and replace the comparisons. This PR should fix the issue you experience on i386, let's fix other problems when they appear. In the meanwhile, I will open another PR and fix them progressively.
> Fixed comparison of double in some tests

- xtensorConfig.cmake.in
Export link interface to `tbb`
Add target link to `tbb` in cmake config when `XTENSOR_USE_TBB` is set
> Export link interface to `tbb`

- CMakeLists.txt
> Added missing headers in CMake

- include/xtensor/xexception.hpp
> Silence unused variable warning GCC

- include/xtensor/xbuilder.hpp
- include/xtensor/xrepeat.hpp
- include/xtensor/xsort.hpp
Fixes all compiler warnings I was getting on mac/clang.
> Fixing internal types

- include/xtensor/xcontainer.hpp
- test/test_xarray.cpp
- test/test_xtensor.cpp
> Adding size assertion `.flat(i)` + adding a few tests on size assertions

- docs/source/api/xstrides.rst
- docs/source/numpy-differences.rst
- include/xtensor/xstrides.hpp
- test/test_xstrides.cpp
I don't know if I add to the docs correctly. See https://github.com/xtensor-stack/xtensor/issues/2480
Fixes https://github.com/xtensor-stack/xtensor/issues/2477
> Adding free function `xt::strides`

- include/xtensor/xmath.hpp
> Resolved compile warning for convolve. Missed it in the original pr

- include/xtensor/xadapt.hpp
This request fixes pointer type traits in `xt::adapt` method.
> fixing pointer type traits in xadapt.

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- CMakeLists.txt
- environment-dev.yml
> Upgraded to xsimd 9.0.1

- docs/environment.yml
> Removed pinning of breathe in docs configuration

- .azure-pipelines/azure-pipelines-osx.yml
> Migrated to the bash homebrew uninstaller

- xtensorConfig.cmake.in
> Fix `TBB` target in `CMake` exported interface

- benchmark/benchmark_creation.cpp
> Fix license comment format

- test/files/cppy_source/test_extended_broadcast_view.cppy
- test/files/cppy_source/test_extended_xhistogram.cppy
- test/files/cppy_source/test_extended_xmath_interp.cppy
- test/files/cppy_source/test_extended_xmath_reducers.cppy
- test/files/cppy_source/test_extended_xsort.cppy
> Change extended tests test header

- .azure-pipelines/azure-pipelines-win.yml
- CMakeLists.txt
- environment-dev.yml
> Upgraded to xsimd 10.0.0

- CMakeLists.txt
> Fixed xtl requirement

- include/xtensor/xstorage.hpp
> Add space before pragma diagnostic

- .pre-commit-config.yaml
- docs/source/changelog.rst
> Fix and update pre-commit

- docs/source/api/shape.rst
- docs/source/index.rst
- include/xtensor/xstrides.hpp
Fixes https://github.com/xtensor-stack/xtensor/issues/2662
We should still document the rest of the functions
> [docs] Improving documentation `xstrides`

- .github/workflows/issue-close.yml
> CI: fixing typos

- .github/workflows/issue-close.yml
> CI: Adding `Stale?` label to autoclose

- include/xtensor/xmath.hpp
- test/test_xmath.cpp
> Added unwrap

- .github/workflows/ci_extended.yaml
> Removed repeated work from ci-extra build

- CMakeLists.txt
- docs/rtd_environment.yml
- environment-dev.yml
- readthedocs.yml
> Upraded to xsimd 11

- .github/workflows/osx.yml
- environment-dev.yml
> Bump OSX Version 12 -> 13 to avoid deprecated environment

- readthedocs.yml
> Added missing configuration key for RTD
