xtensor-stack/xtensor

.travis.yml
This should not be necessary since https://github.com/conda/conda/issues/3784 was fixed.
=> Remove unnecessary pyyaml

include/xtensor/xiterator.hpp
@SylvainCorlay Using iterator_traits instead of direct typedef access is more standard compliant and allows to use raw pointers as iterators.
=> using iterator_traits

include/xtensor/xcontainer.hpp, include/xtensor/xexpression.hpp, include/xtensor/xfunction.hpp, include/xtensor/xscalar.hpp, test/test_common.hpp, test/test_xfunction.cpp
- Single `index_type` over entire library.
- xscalar's `shape_type` is an `array`.
=> Single index type

docs/source/index.rst, docs/source/xview.rst, include/xtensor/xslice.hpp, include/xtensor/xtensor.hpp, include/xtensor/xview.hpp, test/test_xview.cpp
This PR fixes the problem of xall slice whose constructor requires the dimension of the underlying array.
=> xall() implementation

include/xtensor/xarray.hpp, include/xtensor/xassign.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xexception.hpp, include/xtensor/xfunction.hpp, include/xtensor/xiterator.hpp, include/xtensor/xnoalias.hpp, include/xtensor/xoperation.hpp, include/xtensor/xscalar.hpp, include/xtensor/xslice.hpp, include/xtensor/xtensor.hpp, include/xtensor/xutils.hpp, include/xtensor/xview.hpp, test/test_common.hpp, test/test_xfunction.cpp, test/test_xview.cpp
TODO:
`is_nothrow_constructible`
`is_nothrow_copy_constructible`
`is_nothrow_move_constructible`
(Next PR)
Please check changes to `xutils`.
=> More noexcept

include/xtensor/xview.hpp
Slight modification on the top of #44, which should be functionally equivalent.
This replaces SFINAE with template resolution.
Ping @wolfv
=> Remove uses of SFINAE in xview accessor

docs/source/xbroadcast.rst, include/xtensor/xbroadcast.hpp, include/xtensor/xbuilder.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xexpression.hpp, include/xtensor/xfunction.hpp, include/xtensor/xiterator.hpp, include/xtensor/xscalar.hpp, include/xtensor/xview.hpp, test/CMakeLists.txt, test/test_xbroadcast.cpp, test/test_xbuilder.cpp, test/test_xiterator.cpp
Adding more details here for the record now that we have new contributors (ping @wolfv )
1. On shape types
- The `shape_type` of `xarray` has a runtime-determined length and is heap-allocated. Currently it is `std::vector`.
The `shape_type` of `xtensor` has compile-time determined length and is stack-allocated. Currently it is `std::array`. This makes xtensor slightly more efficient than xarray.
- Hence, for efficiency reasons, anytime the dimension can be known at compile time, the shape type is actually std::array. We do this for `xfunction`, `xscalar`, and now `xbroadcast` using the *`promote_shape` mechanism*:
The promoted shape type of `n` shapes of type std::array is std::array. As soon as there is anything else than an std::array, we promote it to `std::vector`. Here, in …
=> Add xbroadcast expression and broadcast helper.

.travis.yml, include/xtensor/xbroadcast.hpp
Notes on this change:
- `std::cbegin` is missing in `gcc 4.9`, so using `std::begin`
- This triggers the clang bug which we have discussed.
- I added clang 3.8 to the test suite to show that this work with clang 3.8 onward.
=> Make broadcast more efficient in case of initializer lists

include/xtensor/xbroadcast.hpp, include/xtensor/xfunction.hpp, include/xtensor/xscalar.hpp, include/xtensor/xview.hpp
- removed strides_type and related methods in expressions where they don't make sense.
- use underlying expression's `shape_type` in `xview`
=> `promote_shape` on xview

include/xtensor/xassign.hpp, include/xtensor/xiterator.hpp, include/xtensor/xview.hpp
There is one outstanding instance `make_sequence` that should be converted in xview (for the index of the underlying expression for `operator[]`). Although it should probably not be called `index_type`.
=> WIP: separate `index_type` from `shape_type` in xassign and xiterator

include/xtensor/xbuilder.hpp, include/xtensor/xgenerator.hpp, test/test_xbuilder.cpp
As discussed, renamed xindex_function to xgenerator. 
Removed all functions except for `arange`, `linspace` and `logspace`.
=> xgenerator

CMakeLists.txt
@SylvainCorlay using `-D BUILD_TESTS=OFF` should fix the conda recipe for gcc builds.
=> option to disable test build

CMakeLists.txt, include/xtensor/xbuilder.hpp, include/xtensor/xgenerator.hpp, include/xtensor/xrandom.hpp, test/CMakeLists.txt, test/test_xrandom.cpp
As discussed in the random xarrays PR, this version utilizes the new xgenerator :)
Unfortunately, resetting the random number engine seems to work only once, which really puzzles me. If you got any insights why the test is failing I'd be happy to hear it.
=> xgenerator for random arrays

.dir-locals.el, include/xtensor/xarray.hpp, include/xtensor/xtensor.hpp, test/test_xmath.cpp
Adds the ability to specify an allocator type for the elements and shape of an `xarray` and the ability to specify and allocator for the elements of an `xtensor`
=> Support allocators for STL containers owned by xarray and xtensor

include/xtensor/xbuilder.hpp, test/test_xbuilder.cpp
Hi,
I've implemented the eye function through xgenerator. This time I tried to use a generic std::function that works on iterators. 
However, I faced a difficulty when using the static array + std::begin/end() combination @SylvainCorlay demonstrated in the last PR. I didn't find any way to keep the std::function as a function template. 
Do you have ideas / is it necessary?
I think if this works well, the fn_impl could get some nice helper-wrapper to initialize a xgenerator from a lambda function, or the mechanism could be integrated directly into xgenerator.
=> Eye function

include/xtensor/xmath.hpp, include/xtensor/xoperation.hpp, test/test_xmath.cpp, test/test_xoperation.cpp
This PR implements a bunch of boolean ops, and adds tests. Also for logical_or/and/not.
I fixed a bug in which the return type wasn't correctly determined in get_xfunction_type.
Also, identity and conditional_ternary structs are moved to the `detail` namespace. This way, `xt::identity` could be an overload for `xt::eye` as in numpy.
=> Implement <, >, <=, >=, equals_to, clip, and fix bug in boolean ops

include/xtensor/xmath.hpp, include/xtensor/xutils.hpp, test/test_xmath.cpp
Behaves equivalent to numpy's sign function.
=> sign function

CMakeLists.txt, include/xtensor/xgenerator.hpp, include/xtensor/xindexview.hpp, include/xtensor/xoperation.hpp, include/xtensor/xutils.hpp, test/CMakeLists.txt, test/test_xindexview.cpp, test/test_xoperation.cpp
I hope this doesn't come across as spam :) but I have attempted an implementation for an "index view". ie. one can provide a list of indices and those will be selected into a linear view.
Essentially, it allows for numpys advanced indexing like so:
```
xt::xarray<double> rn = xt::random::rand<double>({3, 3}, 0, 1);
auto v = xt::make_xindexview(rn, {{1,1}, {2,2}});
auto v2 = xt::make_boolview(rn, (rn > 0.2));
std::cout << v << std::endl;
std::cout << v2 << std::endl;
v += 2.0;
v2 += 15;
std::cout << rn << std::endl;
```
With corresponding output:
```
{{0.135477, 0.835009, 0.968868},
{0.221034, 0.308167, 0.547221},
{0.188382, 0.992881, 0.996461}}
{0.308167, 0.996461}
{0.835009, 0.968868, 0.221034, 0.308167, 0.547221, 0.992881, 0.996461}
{{0.135477, 15.835, 15.9689},
{15.221, 17.3082, …
```
=> xindexview function for advanced indexing

include/xtensor/xbuilder.hpp, include/xtensor/xexpression.hpp, include/xtensor/xfunction.hpp, include/xtensor/xmath.hpp, include/xtensor/xscalar.hpp
The ` xscalar` wrapper now holds a const reference on the underlying scalar when possible.
This required factoring out the closure mechanism used for xclosure in a `detail` namespace.
=> Make use of closure_type in xscalar

include/xtensor/xbroadcast.hpp, include/xtensor/xexpression.hpp, include/xtensor/xfunction.hpp, include/xtensor/xmath.hpp, include/xtensor/xoperation.hpp, include/xtensor/xscalar.hpp, include/xtensor/xvectorize.hpp
To support the editing `xviews` on `xscalar`, we need to have non-const accessors on xscalar, in the case of a non-const closure type.
=> WIP Cleanup meta functions

docs/source/expression.rst, include/xtensor/xassign.hpp, include/xtensor/xbroadcast.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xfunction.hpp, include/xtensor/xgenerator.hpp, include/xtensor/xindexview.hpp, include/xtensor/xiterator.hpp, include/xtensor/xoperation.hpp, include/xtensor/xscalar.hpp, include/xtensor/xsemantic.hpp, include/xtensor/xview.hpp, test/test_common.hpp, test/test_xarray.cpp, test/test_xarray_adaptor.cpp, test/test_xbroadcast.cpp, test/test_xfunction.cpp, test/test_xindexview.cpp, test/test_xiterator.cpp, test/test_xoperation.cpp, test/test_xscalar.cpp, test/test_xtensor.cpp, test/test_xtensor_adaptor.cpp, test/test_xview.cpp
Fixes #135.
Improved ``xiterator`` perofrmance by avoiding the copy of the shape when it is possible.
@nbecker you might be interested in this, although it doesn't fix *all* the performances issues.
You can now use the range for loop syntax and achieve the same performance than with the ``storage_begin``/``storage_end`` methods (which have been renamed in ``begin``/``end``).
=> iterator performance

include/xtensor/xslice.hpp, test/test_xrandom.cpp, test/test_xview.cpp
=> added xrange adaptor and fix for xstepped_range size

docs/source/numpy.rst, include/xtensor/xbuilder.hpp, include/xtensor/xexpression.hpp, include/xtensor/xmath.hpp, include/xtensor/xreducer.hpp, include/xtensor/xutils.hpp, test/test_xreducer.cpp
- Now storing a closure type on the axes sequence.
- The list of axes now must be sorted.
=> Move semantic with xreducer axes

docs/source/numpy.rst, include/xtensor/xbroadcast.hpp, include/xtensor/xbuilder.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xfunction.hpp, include/xtensor/xgenerator.hpp, include/xtensor/xindexview.hpp, include/xtensor/xmath.hpp, include/xtensor/xoffsetview.hpp, include/xtensor/xrandom.hpp, include/xtensor/xreducer.hpp, include/xtensor/xscalar.hpp, include/xtensor/xview.hpp, test/test_xreducer.cpp
This is an experiment for reducer with no specified axes that use `arange(dimension())` as a list of axes, i.e. use a 1-D tensor expression with no storage instead of traditional sequence.
The two blockers are
- the need for a `size()` method (added here in xgenerator but which should be added everywhere). The containers already have it.
- the need for `operator[]` with an integral type.
This shows that people could start using e.g. `linspace` instead of an std::vector for many use cases.
=> Enable reduce-all

CMakeLists.txt
This PR makes the resulting CMake packaging for `xtensor` architecture-independent. Without this known hack (used in other header-only libs such as Eigen or pybind11), a build of `xtensor` made on a 64-bit machine cannot be used on a 32-bit architecture because the `find_package` mechanism will fail.
=> Arch-indep CMake packaging

CMakeLists.txt, docs/source/missing.rst, include/xtensor/xmissing.hpp, include/xtensor/xoptional.hpp, include/xtensor/xoptional_sequence.hpp, include/xtensor/xtensor_forward.hpp, test/CMakeLists.txt, test/test_xoptional.cpp
**Prerequisite 1:** One interesting fact in the STL, is that `std::vector` template is specialized for `bool` so that` std::vector<bool>` is *actually coalescing vector elements such that each element occupies a single bit instead of `sizeof(bool)` bytes*. This is a first feature that we are going to take advantage of in the following.
**Prerequisite 2:** Also, the return type of `operator[]` for `std::vector<bool>` is not a reference on a boolean, but an instance of **reference proxy** to which one can assign a boolean. Reference proxies occur in other places in the STL, and we are going to use this sort of things in the missing value support.
**Initial goals:**
- create a specialized container, whose value type behaves very much like C++17's `std::optional` but such that the actual …
=> Initial missing value support, xoptional

include/xtensor/xcontainer.hpp, include/xtensor/xview.hpp, test/test_xview.cpp
This adds `strides()`, `data()`, and `offset()` to the xview class as well as `offset()` to the xcontainer class.
Maybe it would be useful to have a `data_pointer()` API? 
Also, maybe `data_offset()` would be a better name. 
What do you think?
In my opinion, with this PR, integration with external BLAS libraries should be fairly straight forward.
=> Add data API (xview, xcontainer)

benchmark/CMakeLists.txt
This PR provides a similar setup as [pybind11](https://github.com/pybind/pybind11/blob/master/tests/CMakeLists.txt) to enable building the benchmarks standalone using a system installed version of `xtensor`.
This is a desirable feature for CI purposes (for example on Debian), whereby the packaged `xtensor` library could be tested for each supported C++ compilers or on each CMake update for instance. Ideally, I'd also want the test suite to be made standalone, but #187 should probably be solved first.
=> Make benchmark a standalone project

.appveyor.yml, .travis.yml, CMakeLists.txt, README.md, benchmark/CMakeLists.txt, docs/source/build-options.rst, docs/source/index.rst, test/CMakeLists.txt, test/CMakeLists.txt.in
`gtest` can be downloaded and built as part of the build of `xtensor`. This can be enabled with:
```bash
cmake -DDOWNLOAD_GTEST=ON ../
```
=> gtest downloaded and compiled

docs/source/index.rst, docs/source/related.rst, include/xtensor/xbuilder.hpp, include/xtensor/xfunctorview.hpp, include/xtensor/xindexview.hpp
- Moving the `related projects` section to miscelaneous.
- Expanding on `xtensor-python` and `xtensor-cookiecutter`.
=> Expand on related projects

include/xtensor/xutils.hpp
In the case of numpy arrays, the size_type is different from `std::size_t`, which caused this to warn at build time.
=> Resolve xtensor-python compilation warning

CMakeLists.txt, docs/source/build-options.rst, test/CMakeLists.txt, test/copyGTest.cmake.in, test/downloadGTest.cmake.in
@ghisvail This should allow you to use local source of gtest with the following cmake command:
```bash
cmake -DGTEST_SRC_DIR=full_path_to_source ../
make xtest
```
Please note you don't need to pass `-DBUILD_TESTS=ON` anymore, it is activated by default if either `DOWNLOAD_GTEST` or `GTEST_SRC_DIR` is set.
=> gtest build from local sources

docs/Makefile
Remove the additional `xml` folder generated by `doxygen`
=> Fixup docs clean target

include/xtensor/xview.hpp
This is really important to avoid problems that have been experienced while implementing axis iterators.
=> xview constructor is now explicit

include/xtensor/xio.hpp
=> use precision_type for element_width

include/xtensor/xslice.hpp, include/xtensor/xstridedview.hpp, include/xtensor/xview.hpp, test/CMakeLists.txt, test/test_xdynamicview.cpp
This adds a new class, the slices_vector. A container type that can be initialized with a shape or xexpression. Then one can append xslice's, or range_adaptors, or xall_tags/xnewaxis_tags and the corresponding `{offset, n_elements, step_size}` arrays are calculated which can be used in the dynamic_view.
=> Dynamic view (on top of the strided view)

include/xtensor/xbuilder.hpp
This is apparently needed. I think I removed it sometime earlier ... 
Is this the correct way to implement it?
=> add empty fn access operator

include/xtensor/xmath.hpp
Just inverted ``lo`` and ``hi`` parameter in ``clip`` (this is for the documentation only, the implementation is correct, even is misleading).
=> api and doc fix

.gitignore, CMakeLists.txt, xtensor.pc.in
pkg-config is a tool to get build flags.
If xtensor supports pkg-config, users can set build flags easily.
For example, CMake supports pkg-config.
To support pkg-config, we just install .pc file that includes build
flags information.
=> Support pkg-config

include/xtensor/xarray.hpp, include/xtensor/xassign.hpp, include/xtensor/xfunctorview.hpp, include/xtensor/xindexview.hpp, include/xtensor/xsemantic.hpp, include/xtensor/xstridedview.hpp, include/xtensor/xtensor.hpp, include/xtensor/xview.hpp
This does two things:
- makes the `assign_temporary` and `assign_temporary_impl` take rvalue references.
- Move the members of temporaries to the adaptors.
I decided to not restrict to the second item, because otherwise it is not clear that the temporary may be destroyed.
=> Move semantics for assign-temporary

include/xtensor/xarray.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xiterable.hpp, include/xtensor/xiterator.hpp, include/xtensor/xscalar.hpp, include/xtensor/xtensor.hpp
This includes some bug fixes
- The assignment operator from an `initializer_list` for `xtensor` and `xarray` was making the assumption that `xbegin` always gives a row-major iterator.
- xiterator's increment stepper for column-major was buggy in the 0-D case.
=> Fixes in reverse broadcasting iterators

CMakeLists.txt
To be consistent with the recently introduced pkgconfig files. It also simplifies the Debian packaging slightly, since only `CMAKE_INSTALL_LIBDIR` needs to be modified to install everything under a (non-)multiarch path.
=> Install the cmake config files under libdir

include/xtensor/xcontainer.hpp, include/xtensor/xstridedview.hpp
- make `data_xbegin` and `data_xend` protected...
=> begin / end behavior on strided containers

README.md, include/xtensor/xoptional.hpp, test/test_xoptional.cpp
This enables conversions such as
`const char* -> xoptional<std::string>`
=> Enable casting to xoptional

include/xtensor/xutils.hpp
- corrected emscripten compilation issue related to is_trivially_default_constructible declaration: the emscripten case is now managed apart from the clang/linux case, the same way as for clang/apple.
- compilation tested with emscripten sdk under Linux & Mac OSX, but not on Windows.
- this fix is related to this *tiny-dnn* issue [#854](https://github.com/tiny-dnn/tiny-dnn/issues/854)
=> Fix build error with Emscripten

include/xtensor/xview.hpp
This seems to be the only unused variable, apart from some in the tests.
=> Remove unused variable

test/CMakeLists.txt
This should not be necessary anymore with the recent fixes in the gtest conda-forge package.
=> Fixup gtest link

docs/source/compilers.rst, include/xtensor/xutils.hpp
Better means of detecting if we are using the STL of an old GCC with clang. `_GLIBCXX_USE_CXX11_ABI` is only defined as of gcc 5.0.
=> Use _GLIBCXX_USE_CXX11_ABI for detecting gcc >= 5.0

include/xtensor/xinfo.hpp
`std::string` cannot be constexpr.
=> Constexpr string

include/xtensor/xbuilder.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xeval.hpp, include/xtensor/xexception.hpp, include/xtensor/xexpression.hpp, include/xtensor/xfunction.hpp, include/xtensor/xiterable.hpp, include/xtensor/xiterator.hpp, include/xtensor/xmath.hpp, include/xtensor/xoptional.hpp, include/xtensor/xscalar.hpp, include/xtensor/xstorage.hpp, include/xtensor/xstridedview.hpp, include/xtensor/xstrides.hpp, include/xtensor/xutils.hpp, test/test_xmath.cpp, test/test_xscalar.cpp
Fixes #412 
- Even when universal functions are only called with scalar arguments, they continue returning a xfunction object.
- This preserves the laziness. 
- When universal functions are called with scalar arguments only, a cast operator to the underlying scalar return type is made available, so that you can assign the value to a scalar.
1. In this example, close is an xfunction, just like when arguments are arrays
```cpp
auto close = xt::isclose(1.0, 1.0);
```
2. However, it is convertible to bool,  triggering the evaluation, so that you can do
```cpp
bool close = xt::isclose(1.0, 1.0);
```
=> Add `value_type()` cast operator to xfunction when all arguments are of type xscalar

CMakeLists.txt, docs/source/build-options.rst, docs/source/expression.rst, include/xtensor/xbroadcast.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xexception.hpp, include/xtensor/xfunction.hpp, include/xtensor/xfunctorview.hpp, include/xtensor/xgenerator.hpp, include/xtensor/xreducer.hpp, include/xtensor/xstridedview.hpp, include/xtensor/xview.hpp, test/test_common.hpp, test/test_xarray.cpp, test/test_xarray_adaptor.cpp, test/test_xbroadcast.cpp, test/test_xexception.cpp, test/test_xfunction.cpp, test/test_xreducer.cpp, test/test_xstridedview.cpp, test/test_xtensor.cpp, test/test_xtensor_adaptor.cpp, test/test_xview.cpp
=> safe access method

include/xtensor/xscalar.hpp, test/test_xscalar.cpp
``xscalar::at`` is missing in #420 .
=> at method added to xscalar

CMakeLists.txt, include/xtensor/xassign.hpp, include/xtensor/xbuilder.hpp, include/xtensor/xcomplex.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xfunction.hpp, include/xtensor/xmath.hpp, include/xtensor/xoperation.hpp, include/xtensor/xoptional.hpp, include/xtensor/xscalar.hpp, include/xtensor/xtensor_forward.hpp, include/xtensor/xtensor_simd.hpp, include/xtensor/xutils.hpp
simd acceleration is disabled by default. To enable it, one needs to add `-DXTENSOR_USE_XSIMD` to the cmake command line. This requires `xsimd` to be installed.
=> xsimd plugged

include/xtensor/xassign.hpp, include/xtensor/xconcepts.hpp, include/xtensor/xutils.hpp, test/test_xbuilder.cpp, test/test_xconcepts.cpp, test/test_xutils.cpp
When compiling an expression like
```c++
xarray<uint8_t> c = ones<uint32_t>({100});
```
compilers issue a "possible loss of data" warning. This PR assumes that users know what they are doing and adds a conditional type cast for narrowing conversions of built-in types to `data_assigner::run()` (other conversions remain untouched).
While the above example looks contrived, warnings for narrowing casts are quite common in mixed-type expressions and will be exposed in my upcoming fix for #429 and related issues.
=> Added conditional cast in assigments

include/xtensor/xmath.hpp, include/xtensor/xoperation.hpp, include/xtensor/xreducer.hpp, include/xtensor/xutils.hpp, test/test_xmath.cpp, test/test_xreducer.cpp, test/test_xutils.cpp
same as #433, but rebased on latest master (including xtl migration)
fixes #429 
Summary of the changes:
* xutils.hpp: add `big_promote_type_t` to find the biggest type of the same kind
* xmath.hpp: use `decltype()` to determine the result type of algebraic functions
* xmath.hpp: use `big_promote_type_t` as result type of `sum()` and `prod()`
* xmath.hpp: enforce floating-point results in `mean()`
* xreducer.hpp: determine an xreducer's value_type from the result type of the reduce functor
* additional tests
=> V2: Improved result type inference for xexpressions

include/xtensor/xexpression.hpp
I was always wondering why declarations with forwarding references to xexpressions didn't match as I expected. After some painful debugging, I finally found out: The concept check `is_xexpression_impl` was broken. Here is the fix.
=> fixed is_xexpression_impl

include/xtensor/xmath.hpp, include/xtensor/xnorm.hpp, include/xtensor/xreducer.hpp, include/xtensor/xutils.hpp, test/CMakeLists.txt, test/test_xnorm.cpp, test/test_xreducer.cpp, test/test_xutils.cpp
implements #417, supersedes #436 
Summary of changes:
* lifted `identity_functor` from namespace `xt::static_if_detail` to namespace `xt` (it is of general interest)
* added class `xreducer_functors` and factory `make_xreducer_functor()`
* changed `xreducer` to use up to three different functors for the three steps of the computation (cf. https://github.com/QuantStack/xtensor/issues/417#issuecomment-332524710)
* adapted existing reducing functions to these changes
* implemented norm functions and tests
=> Implementation of norm functions

include/xtensor/xstridedview.hpp
There was a xbegin left in strided_view. 
Not sure if this is the correct fix @JohanMabille
=> change xbegin -> begin

.appveyor.yml, .travis.yml, include/xtensor/xbroadcast.hpp, include/xtensor/xbuilder.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xexception.hpp, include/xtensor/xfunction.hpp, include/xtensor/xnorm.hpp, include/xtensor/xreducer.hpp, include/xtensor/xslice.hpp, include/xtensor/xstridedview.hpp, include/xtensor/xutils.hpp, include/xtensor/xview.hpp, test/test_xnorm.cpp, test/test_xreducer.cpp
Some warnings remain in xview/xutils, the main reason is we're converting int to long unsigned int, so two conversions actually happen: int => long and then signed => unsigned.
Getting rid of them requires additional work (it implies adding casters depending on the source type and the destination type).
=> some warnings removed

include/xtensor/xassign.hpp, test/test_xtensor_semantic.cpp
This should fix one of the issue described [here](https://github.com/QuantStack/xtensor-python/issues/116). So now the following should work:
```cpp
inline xt::pyarray<uint8_t> example2(xt::pyarray<uint8_t> &m)
{
return m + 2;
}
```
However this will issue a warning (just like assigning an int value to a uint8_t value issues a warning). The `xcast` function proposed in the issue is a good way to explicitly get rid of the warning.
@stuarteberg this fix should be available in the next release of the xtensor stack, which should be done by the end of this week. Are you interested in opening a PR for the `xcast` stuff ?
=> ability to cast in the assignment

.appveyor.yml, docs/source/compilers.rst, include/xtensor/xcontainer.hpp
Cf VS 2013 bug [here](https://connect.microsoft.com/VisualStudio/feedback/details/808130/alias-template-issue-involving-non-type-template-parameter-and-two-levels-of-template-aliasing).
Fixes #375.
=> Workaround MSVC alias template bug

include/xtensor/xexception.hpp, include/xtensor/xfunctorview.hpp, include/xtensor/xinfo.hpp
This fixes 3/4 codacity warnings. 
Last one is a xconcepts struct that is never used, I think.
=> fix codacity warnings

include/xtensor/xmath.hpp
Remove unused type alias in `xt::mean()`. (Now unused after #435.)
Eliminates a warning from clang.
=> Remove unused type alias 'value_type' in xt::mean()

include/xtensor/xbuilder.hpp
In case people use xtensor with arbitrary precision floating point types (such as MPFR), they probably don't want to use `double` here.
So taking the common type with double to handle the case of integral types.
=> Use more general fp_type

include/xtensor/xreducer.hpp, test/test_xreducer.cpp
There is a minor but unnecessary subtlety in the `xt::reduce` API. Given an arbitrary `xreducer_functors` object such as the following:
```c++
auto sum = [](auto const & left, auto const & right){ return left + right; };
auto sum_functor = xt::make_xreducer_functor(sum);
```
...one can use `xt::reduce` as follows:
```c++
xt::xarray<int> a_sums = xt::reduce(std::move(sum_functor), a, {1});
```
But without `std::move`, it doesn't compile:
```c++
xt::xarray<int> a_sums2 = xt::reduce(sum_functor, a, {1});
```
```
In file included from /workspace/xtensor/include/xtensor/xmath.hpp:21:
/workspace/xtensor/include/xtensor/xreducer.hpp:152:46: error: type 'xt::xreducer_functors<(lambda at
/workspace/xtensor/test/test_xreducer.cpp:45:20), xt::identity_functor, (lambda at …
```
=> xreducer: Don't require functor to be passed via rvalue reference

docs/source/adaptor.rst, docs/source/index.rst
As suggested in #543 , this adds a short narrative documentation about the `xt::adapt` function.
=> Narrative documentation about adapt

docs/source/operator.rst, include/xtensor/xindexview.hpp, include/xtensor/xnoalias.hpp, include/xtensor/xoperation.hpp, include/xtensor/xsemantic.hpp, test/test_xoperation.cpp
I think it would be nice if `xtensor` supported `operator%` for `xexpression`s.  This requires a slightly more complicated implementation than the other arithmetic operators, since one can't use `%` with non-integer operands.
My first attempt at implementing this PR failed.  I had attempted to selectively disable the modulus function in `xsemantic.hpp` (and elsewhere) for non-integer types via `enable_if`, but it turns out that doesn't work.  The `xexpression_type` is "incomplete" (since the `xsemantic` hierarchy employs the CRTP), so `enable_if` can't be used at that level.  (Unless I'm missing something... I'm not an expert.)
Instead, this PR uses a simpler solution.  The `modulus` operation exists for all `xexpression` (even non-integer ones), but the implementation for non-integer …
=> Modulus operator

include/xtensor/xadapt.hpp, test/test_xadapt.cpp
The `xadapt()` function requires a `shape` argument, which is unnecessarily tedious if you wanted a 1D `xtensor`.  (For instance, when doing arithmetic with array shapes.)  Is there any reason not to just adapt containers to a 1D array by default?  If not, here's a little PR that adds the necessary overloads.
=> xadapt: default overload for 1D arrays

docs/source/api/xarray_adaptor.rst, docs/source/api/xtensor_adaptor.rst, include/xtensor/xadapt.hpp, include/xtensor/xnpy.hpp, test/test_xadapt.cpp
Fixes #546
Technically, this is a breaking change, albeit a small one.  Does that mean it should wait until the next major release?
cc @constantinpape
<details>
<summary>details</summary>
```bash
$ git grep -l xadapt | xargs sed -i '' 's/xadapt\([^a-zA-Z.]\)/adapt\1/g'
$ git grep xadapt
CMakeLists.txt:    ${XTENSOR_INCLUDE_DIR}/xtensor/xadapt.hpp
docs/source/adaptor.rst:    #include "xtensor/xadapt.hpp"
docs/source/adaptor.rst:    #include "xtensor/xadapt.hpp"
docs/source/adaptor.rst:    #include "xtensor/xadapt.hpp"
docs/source/api/xarray_adaptor.rst:Defined in ``xtensor/xadapt.hpp``
docs/source/api/xtensor_adaptor.rst:Defined in ``xtensor/xadapt.hpp``
docs/source/external-structures.rst:``xadaptor_semantic`` instead.
include/xtensor/xnpy.hpp:#include "xtensor/xadapt.hpp" …
```
=> Rename xadapt() -> adapt()

environment.yml
for any packages not provided by QuantStack.
This is instead of opting out of defaults, which results in unsatisfiable dependencies without a provider for the missing packages.
conda env create -f environment.yml
fails with this file right now, because not all dependencies of the environment are on the QuantStack channel.
Channel priority keeps defaults-channel or conda-forge updates from being used in favor QuantStack-provided packages, regardless of version.
This file is being used on Binder and I'm investigating right now because the quantstack binders are pinning an old version of `notebook` (5.0.0) as a result of packaging `notebook` on the QuantStack channel, which is treated as higher priority than conda-forge.
Because of channel priority, even after this change quantstack notebook …
=> allow conda-forge as fallback channel

include/xtensor/xexpression.hpp, include/xtensor/xoperation.hpp, include/xtensor/xscalar.hpp
This allows to mix scalar and any expression type in expression systems built upon the one of xtensor. Without this, a new expression system that wants to mix expressions and scalars has to define tags logic involving the new expression tag and `xtensor_expression_tag`, which is the default tag for `xscalar`.
=> xscalar_expression_tag added

benchmark/downloadGBenchmark.cmake.in
... because version 1.2.0 doesn't properly recognize C++11 in Visual Studio 2015 and therefore fails to compile benchmark_xtensor
=> upgraded to google/benchmark version 1.3.0

.appveyor.yml, .travis.yml, include/xtensor/xassign.hpp, include/xtensor/xfunction.hpp, include/xtensor/xiterable.hpp, include/xtensor/xiterator.hpp, include/xtensor/xoptional_assembly_base.hpp, include/xtensor/xscalar.hpp, test/test_common.hpp, test/test_xfunction.cpp, test/test_xiterator.cpp
Fixes #542.
Do not squash the commits, we must be able to retrieve each of the changes in the history.
=> random access iterators

include/xtensor/xcontainer.hpp
=> protected xcontainer::derived_cast

test/test_xindex_view.cpp
Checks the compilation of `xt::filter(a, cond1) += xt::filter(b, cond2)` where `b` is a const array.
=> filter test added

README.md, docs/source/basic_usage.rst
Add index access examples to README and basic usage in docs, as this is where most people land.
Coming from python, some people (including me...) might try to access indices with `someXArray [0]`, `someXArray[0][0]` etc.
=> Add index access example

README.md, include/xtensor/xstorage.hpp
Getting 
`xstorage.hpp:1110:15: error: assert was not declared in this scope`
in the `xtensor-r` checks.
One fix would be to do `#include <cassert>`. But we use the XTENSOR_ASSERT macro in most other places.
=> Assert undefined

include/xtensor/xassign.hpp, include/xtensor/xbroadcast.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xcsv.hpp, include/xtensor/xfixed.hpp, include/xtensor/xfunction.hpp, include/xtensor/xfunctor_view.hpp, include/xtensor/xgenerator.hpp, include/xtensor/xindex_view.hpp, include/xtensor/xoptional_assembly_base.hpp, include/xtensor/xreducer.hpp, include/xtensor/xscalar.hpp, include/xtensor/xstrided_view.hpp, include/xtensor/xview.hpp, test/test_xshape.cpp
@wolfv This avoids duplicated calls to ``broadcast``, and skips strides comparison when layouts can be compared at compile time.
This should remove the remaining overhead in the assign mechanism, let me know if you still see some overhead in your benchmarks.
=> assign functions optimized

include/xtensor/xview.hpp, test/test_xview.cpp
=> add caching for view strides

include/xtensor/xassign.hpp, include/xtensor/xfunction.hpp, include/xtensor/xstrides.hpp, test/test_xfunction.cpp, test/test_xtensor.cpp
Fixes #715 
Besides, this really cleans the `broadcast_shape` mechanism.
=> broadcast fixed

include/xtensor/xaccumulator.hpp, include/xtensor/xgenerator.hpp, include/xtensor/xindex_view.hpp, include/xtensor/xiterator.hpp, include/xtensor/xreducer.hpp, include/xtensor/xsort.hpp, include/xtensor/xstorage.hpp, include/xtensor/xstrided_view.hpp, test/test_xview.cpp, test/test_xview_semantic.cpp
Now removing the `CD` template argument from `xstrided_view`, which can be determined as a typedef, and the constructor taking the `data`, which can be computed from the expression in the constructor with `get_data`.
=> Fixes in strided views

include/xtensor/xfixed.hpp, test/test_xfixed.cpp
We / I should really never again test with quadratic shapes :/
=> fix stride computation for xtensorf

.gitignore, include/xtensor/xsort.hpp
Found a typo in the documentation to say maximal for `include/xtensor/xsort.hpp::argmax`
=> updated documenation to say maximal for xsort.hpp::argmax

include/xtensor/xadapt.hpp, test/test_xadapt.cpp
This is meant to prevent wrong overload resolution between
`adapt(C&& container, const SC& shape, layout_type l = L);`
and the catch-all
`adapt(C&& container, SC&& shape, SS&& strides)`
in the case where a layout is specified for the first function.
Another similar issue solved is for the pair
`adapt(P&& pointer, size_type size, const SC& shape, layout_type l = L);`
and the catch-all
`adapt(P&& pointer, size_type size, SC&& shape, SS&& strides)`
in the case when a layout is specified for the fist function.
=> More fixes in xadapt

include/xtensor/xassign.hpp
this should not only speed up the assigment, but it is also in preparation of *removing* all comparison functions of steppers.
Comparison will only be implemented in the iterators.
That will allow us to fix cornercases with reverse iterators and such (e.g. #821 , nicer fix for #802 etc.)
=> remove comparison of steppers in assign loop

include/xtensor/xvectorize.hpp
Fixes #857 
Visual studio 2017 does not like forward declarations.
=> Workaround msvc 15.7 bug

docs/source/compilers.rst, include/xtensor/xexception.hpp, include/xtensor/xfunction.hpp, include/xtensor/xmath.hpp, include/xtensor/xnorm.hpp, include/xtensor/xrandom.hpp, include/xtensor/xstorage.hpp, include/xtensor/xstrided_view.hpp, include/xtensor/xstrides.hpp
I had this issue with Xtensor.jl including `windows.h`.
In xtensor, if we wrap calls to `std::min` and `std::max` with parenthesis, the macros will not be expanded. This will allow client code to use xtensor without having to add the `NOMINMAX` definition.
=> Prevent expansion of min and max macros on windows

docs/source/changelog.rst, include/xtensor/xaccumulator.hpp, include/xtensor/xmath.hpp, include/xtensor/xreducer.hpp
On Solaris, we have
```
#define CS 15
#define DS 3
#define ES 2
```
coming from `sys/regset.h` which is the reason for the `xtensor-r` CRAN failure on solaris.
=> Remove use of CS, DS and ES qualifiers for Solaris builds

.appveyor.yml, .travis.yml, CMakeLists.txt, test/CMakeLists.txt
=> make json tests optional, bump xtl/xsimd versions

.travis.yml, CMakeLists.txt, include/xtensor/xfunction.hpp, include/xtensor/xoperation.hpp, include/xtensor/xutils.hpp, test/test_xoperation.cpp
Comes on the top of #873. (closes #873)
We still need to use a promote trait for the return type for non-boolean functors.
=> Forbid simd bis

include/xtensor/xtensor_simd.hpp
Came up while testing with `mingw`.
=> Add missing batch_bool typedef

include/xtensor/xscalar.hpp, test/test_xreducer.cpp
This completes #879.
The dimension check is done with the macro `XTENSOR_CHECK_DIMENSION` which is never activated in the CI, so the test `xreducer.wrong_number_of_indices` should always be run.
=> Removing test guard and dimension check in xscalar

README.md
Fix
```
error: no member named 'view' in namespace 'xt'
```
Necessary as of 0.16.0
=> README: add include of xview.hpp in example

include/xtensor/xstrided_view.hpp, include/xtensor/xtensor_forward.hpp
Another solaris build issue. There is a `FS` macro on solaris.
I could find all the namespace polution in an LLVM header: https://llvm.org/doxygen/regset_8h_source.html
So there should not be other.
=> Remove FS identifier

include/xtensor/xstrides.hpp, test/test_xview_semantic.cpp
=> Assigning an expression to a view throws if it has more dimensions

docs/source/view.rst
Simple example to use islice.  This took me a couple hours to figure out and would probably be a useful snippet for others.
=> add islice example to view docs

include/xtensor/xslice.hpp, include/xtensor/xview.hpp, test/test_xrandom.cpp, test/test_xview.cpp
- xislice => xkeep_slice
- xislice is now templated by the `value_type` instead of the `container_type`
- the container type is now svector (hardcoded)
=> This allow to put `xislice` in a variant and keep the same creation syntax of `xkeep_slice` for both `xview` and `xdynamic_view`.
=> xislice refactoring

include/xtensor/xnoalias.hpp, test/test_xnoalias.cpp
This allows for direct noalias creation on xviews etc.
```
xt::noalias(view(a, 1)) += 123; 
```
will work now
=> Noalias rvalue

environment.yml
I guess `mime_bundle_repr` doesn't work in mybinder because of the version of xeus-cling, what do you think @SylvainCorlay ?
=> Update xeus-cling version

include/xtensor/xaccumulator.hpp, include/xtensor/xassign.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xeval.hpp, include/xtensor/xfixed.hpp, include/xtensor/xfunction.hpp, include/xtensor/xiterable.hpp, include/xtensor/xiterator.hpp, include/xtensor/xrandom.hpp, include/xtensor/xreducer.hpp, include/xtensor/xscalar.hpp, include/xtensor/xshape.hpp, include/xtensor/xstorage.hpp, include/xtensor/xstrided_view.hpp, include/xtensor/xtensor_config.hpp, include/xtensor/xutils.hpp, include/xtensor/xview.hpp, test/test_xaccumulator.cpp, test/test_xfixed.cpp, test/test_xmath.cpp, test/test_xreducer.cpp, test/test_xstrided_view.cpp, test/test_xtensor_semantic.cpp
With this PR we're able to:
- statically compute the extents of a reduction (if axes are supplied as a xshape (TODO add another typedef xaxes?)
- statically allocate memory for accumulators if accumulating over an xfixed
- statically broadcast xfunctions if all leaf nodes are fixed -- note: this might still be broken and WIP.
=> Propagate fixed shape

include/xtensor/xmath.hpp, include/xtensor/xstrided_view.hpp, include/xtensor/xstrided_view_base.hpp, include/xtensor/xutils.hpp, test/test_xreducer.cpp
I think we need shared xexpressions for xt::average with weights. 
That's why I had to start this stuff :)
=> add xt::average / refactor strided view copy + move constructor

CMakeLists.txt
=> Avoided installation failure in absence of nlohmann_json

CMakeLists.txt, include/xtensor/xassign.hpp, test/test_xmath.cpp, test/test_xoperation.cpp
=> convertible types instead of same type

include/xtensor/xrandom.hpp, test/test_xrandom.cpp
This PR corresponds to the following fixes:
1. The garbage values produced by [this issue](https://github.com/QuantStack/xtensor/issues/1009) is due to an optional assert. We throw `std::runtime_error` instead.
2. Previously, we performed a Fisher Yates shuffle on the array and then copied the shuffle. As @wolfv has pointed out, the stdlib implements it using reservoir sampling, which we implement here.
3. We also add an option to perform sample with replacement, and make it true by default, since that is [numpy's behavior](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.choice.html)
=> [xrandom] Improve `random::choice`

include/xtensor/xexpression.hpp, test/test_xexpression.cpp
Previously, `shared_xexpressions` cannot be evaluated, reproduced from [this issue](https://github.com/QuantStack/xtensor/issues/1018).
We needed to expose more forwarding methods for this to work, namely the `element()` function and the `layout` function.
I added tests in the `test_xexpression.cpp` to check that the results of output is correct.
=> [xexpression] Add inspection into shared_expressions

include/xtensor/xnpy.hpp
`signed int` and `int` are the same datatype, but upon doing `std::is_same<char, signed_char>::value`, we can see that it is not. Therefore, we need to add `signed char` as a member into `xnpy`'s deserialization step.
Why do we need `signed char`? Because `std::int8_t` aliases to `signed char` and people may use `int8_t` as a data type in a xtensor array in the future.
=> [xnpy] Add `signed char` to deserialization format

include/xtensor/xexpression.hpp
Fixes a small bug in `make_xshared` where it wasn't performing perfect forwarding and requires a derived_cast to create the correct xexpression.
=> [xexpression] - Fix make_xshared

include/xtensor/xadapt.hpp, include/xtensor/xfixed.hpp, include/xtensor/xutils.hpp, test/test_xadapt.cpp
This adds adapt overloads for 
- fixed shape type
- unowned pointer + shape (without the size parameter)
This can produce super charged views and is more similar to @tdegeus view implementation.
@tdegeus with this change you could write `xt::adapt(&arr(1, 2, 0, 0), xshape<3, 3>())` to get something as fast as the cppmat view.
=> Add more adapt functions

include/xtensor/xslice.hpp, include/xtensor/xstrided_view_base.hpp, test/test_xview.cpp
@tdegeus these were the two places where you pointed me in your issue about warnings for older versions on clang on OS X.
Hope that catches all!?
=> fix warnings for braces on old clang

include/xtensor/xexpression.hpp, include/xtensor/xscalar.hpp, include/xtensor/xsemantic.hpp
The `master` branch, at the time of writing, offers type trait support for enabling or disabling certain classes in its `xexpression` hierarchy via SFINE (causing template substitution errors). This partially involves a _bare hands_ template meta-programming implementation, as the following problem is not addressed in the standard library:
**How does one detect if _any_ instantiation of a templated class is an ancestor of a given class?**
In our case, the templated class is always a CRTP class whose only template parameter takes the value of the most derived class in the hierarchy. For example, for the most universal CRPT class in the library, `xexpression`, we have the following code:
```
template <class E>
struct is_xexpression_impl : std::is_base_of<xexpression<std::decay_t<E>>, …
```
=> Improved CRTP base class detection

include/xtensor/xslice.hpp, include/xtensor/xstrided_view.hpp
Add some missing parenthesis around `std::min` and `std::max` necessary to compile with
MSVC without the `NOMINMAX` definition, see https://github.com/QuantStack/xtensor/blob/0f636b08eb7618744867396e04dc7fda179cfb8d/docs/source/compilers.rst#visual-studio-and-min-and-max-macros.
=> add missing parenthesis around std::min and std::max

include/xtensor/xstrided_view_base.hpp
Fixes the following issue in clang:
```
In file included from /Users/ray_zhang/anaconda3/envs/idp3/include/xtensor/xarray.hpp:19:
In file included from /Users/ray_zhang/anaconda3/envs/idp3/include/xtensor/xcontainer.hpp:23:
In file included from /Users/ray_zhang/anaconda3/envs/idp3/include/xtensor/xmath.hpp:27:
In file included from /Users/ray_zhang/anaconda3/envs/idp3/include/xtensor/xstrided_view.hpp:26:
/Users/ray_zhang/anaconda3/envs/idp3/include/xtensor/xstrided_view_base.hpp:878:55: error: cannot compile this aggregate expression yet
return std::array<std::ptrdiff_t, 3>({0, 0, 0});
```
=> Replace parens with braces to compile aggregate

include/xtensor/xbuffer_adaptor.hpp, include/xtensor/xnpy.hpp, include/xtensor/xstorage.hpp, test/test_xadapt.cpp, test/test_xbuffer_adaptor.cpp, test/test_xmasked_view.cpp, test/test_xoptional_assembly.cpp, test/test_xoptional_assembly_adaptor.cpp, test/test_xview.cpp
With these changes valgrind stops complaining.
The big ones: not using realloc in svector anymore. This might hit performance somewhat but I think it's better to have a clean valgrind output.
Use the std::allocator to allocate memory for the owning buffer. That one is a bit annoying but I think warranted for library functions. Otherwise you get an error because of a mismatch between `free` and `new ... []` where valgrind wants one to use the corresponding `delete[]` instead of `free` or whatever the allocator is using.
The workaround would be to write a shim allocator that calls dealloc with `delete[]`
There was also some tiny bugs in the tests as well as one memory leak with move assignment on owning buffers.
=> Fixing valgrind notifications

include/xtensor/xstorage.hpp, include/xtensor/xutils.hpp
When compiling with GCC7 and C++17 we see the same issues at GCC8 w/ rebind_container. 
Tested w/ GCC7 C++17 and this changeset still works.
=> Apply #1038 also to GCC7

test/CMakeLists.txt
Add flag SYSTEM to `include_directories` for gtest
This omits warnings generated in gtest code-base
Reference: https://cmake.org/cmake/help/latest/command/include_directories.html
=> cmake: Remove warnings for gtest

include/xtensor/xtensor_simd.hpp, include/xtensor/xutils.hpp
When including xutils.hpp,  we were getting an error ```aligned_mode is not declared in this scope```
=> Fix issue with has_simd_interface

docs/source/api/reducing_functions.rst, docs/source/api/xmath.rst
I was looking through the code to see if there were any reducing min/max functions and found `amax` and `amin` in the code but not the documentation.
=> Add amax/amin to documentation

.appveyor.yml, .travis.yml, CMakeLists.txt
`llvm-toolchain-precise-x.y` have been recently [removed ](https://github.com/travis-ci/apt-source-safelist/commit/e9d632eb79c7b733b3bfe722356e892ab8e06059#diff-18834b11de5fbd14772e186aecd6c14b) from apt source safelist, so testing with clang on precise environment is no longer possible.
A solution would be to switch to trusty environment, but clang 3.6, 3.7 and 3.8 are not available in [apt source safelist](https://github.com/travis-ci/apt-source-safelist) on trusty environment, thus we would drop support for these compilers (I'm fine with that, we could remove a lot of workarounds for old clang)
For clang 3.9, 4.0 and 5.0 we face the issue described [here](https://github.com/QuantStack/xtensor/pull/384), however forcing the use of gcc 4.9 fixes the problem.
cc @SylvainCorlay @wolfv
=> upgrade to xsimd 6.2.0, switch to trusty and fix appveyor

include/xtensor/xrandom.hpp, test/test_xrandom.cpp
For reasons unknown at the moment, `std::uniform_int_distribution` generates different sequences for linux and non-linux environments while `std::shuffle` generates identical permutations. In order to produce identical permutations for arrays of arbitrary rank the one-dimension specialization should execute an algorithm analogous to the multi-dimension specialization. This code should have little if any compromise on performance (as it should pretty much be what the STL implements).
Additions to the test code were made to compare the results of shuffling arrays with the same leading dimensions.
=> Modify shuffle to use identical algorithms for any number of dimensions

include/xtensor/xfixed.hpp, test/test_xfixed.cpp
@tdegeus this fixes the issue #1144 for the version with `xt::noalias`. 
In order to fix the version without noalias, we'll have to do a release of `xtl` unfortunately.
=> add resize / reshape to xfixed_adaptor

include/xtensor/xiterable.hpp, test/test_common.hpp, test/test_xbroadcast.cpp, test/test_xoptional_assembly.cpp, test/test_xoptional_assembly_adaptor.cpp
Currently we have to do:
```cpp
shape_type shape = something;
auto iter = a.begin<shape_type, layout_type::column_major>(shape);
```
This PR simplifies this into
```cpp
shape_type shape = something;
auto iter = a.begin<layout_type::column_major>(shape);
```
=> iterator API improved

docs/source/numpy.rst
Trivial change to include ``xt::`` for consistency.
=> Update example in the numpy cheatsheet to use the xt namespace

include/xtensor/xslice.hpp, include/xtensor/xstrided_view.hpp, test/files/cppy_source/test_extended_broadcast_view.cppy, test/files/cppy_source/test_extended_xhistogram.cppy, test/test_extended_broadcast_view.cpp, test/test_extended_xhistogram.cpp, test/test_xdynamic_view.cpp, test/test_xexpression.cpp, test/test_xfixed.cpp, test/test_xhistogram.cpp, test/test_xmanipulation.cpp, test/test_xoptional_assembly_storage.cpp, test/test_xreducer.cpp, test/test_xshape.cpp, test/test_xsort.cpp, test/test_xstrided_view.cpp, test/test_xview.cpp
Remaining warnings are the normal_distribution member not initialized and the conversion due to operator/.
=> warnings removed

CMakeLists.txt, docs/source/releasing.rst, xtensorConfig.cmake.in
Invoking `find_package(xtensor)` now also automatically invokes `find_package(xtl)` using the `find_dependency` macro in the export config file. In addition it adds far better diagnostics. Prior to this PR if you forgot to link against xtl you get a "can not find include file" compiler warning. With this change you already get an error on the initial CMake configuration run, i.e. before you are even able to compile the code.
Remember that future releases must also adjust the package version in the `xtensorConfig.cmake.in`. I know it adds boilerplate code, but the benefits outweigh this.
=> Config.cmake now invokes the find_dependency / find_package macro.

include/xtensor/xdynamic_view.hpp, test/test_xio.cpp
These methods prevent the print of `dynamic_view`.
=> removing data interface from dynamic view

benchmark/CMakeLists.txt, benchmark/benchmark_view_adapt.cpp
The results on my system:
```none
----------------------------------------------------
Benchmark             Time           CPU Iterations
----------------------------------------------------
random_view       94813 ns      94420 ns       6044
random_adapt      63446 ns      63190 ns       9011
```
=> Added view vs. adapt benchmark

docs/source/api/xio.rst, docs/source/histogram.rst, include/xtensor/xio.hpp, test/test_xio.cpp
With this PR it is possible to locally overwrite print options "a la STL":
```cpp
using po = xt::print_options;
xt::xarray<double> a = xt::rand::rand<double>({2000, 2000});
std::cout << po::line_width(150)
<< po::edge_items(10)
<< po::precision(10)
<< po::threshold(100)
<< a
<< std::endl;
```
=> print_options io manipulators

include/xtensor/xstrides.hpp
I think that these defaults make sense as the rest of `xtensor` also abides to these defaults.
=> Proposal: default layout-type for `unravel_from_strides` and `unravel_index`

test/test_xfunction.cpp
SFINAE is somehow broken on MSVC when `xutils.hpp` is included, fixing it needs further investigations.
=> Disabled tests generating wrong code with MSVC

include/xtensor/xeval.hpp, include/xtensor/xexpression.hpp, include/xtensor/xlayout.hpp, include/xtensor/xmanipulation.hpp, include/xtensor/xshape.hpp, include/xtensor/xstorage.hpp, include/xtensor/xtensor_config.hpp, include/xtensor/xtensor_forward.hpp, include/xtensor/xtensor_simd.hpp, test/test_xfixed.cpp
This PRs removes includes and move some definitions to more appropriated files.
=> xtensor_forward.hpp cleanup

CMakeLists.txt, include/xtensor/xio.hpp, include/xtensor/xjson.hpp, include/xtensor/xmime.hpp
- make use of `nlohmann::json` instead of `xeus::xjson`. nlohmann_json is already an optional dependency.
- Separate mime bundle rendering in separate header, `xmime.hpp`
- For backward compatibility, it `xmime.hpp` is included by `xio.hpp` if `__CLING__` is defined.
=> Include nlohmann_json in xio for mime bundle repr

CMakeLists.txt, xtensorConfig.cmake.in
This allows to enable `XTENSOR_USE_XSIMD` in packages depending on `xtensor` without changing their `CMakeLists.txt`.
=> Exporting optional dependencies

include/xtensor/xcsv.hpp
This fixes a bug when loading CSV files as strings (#1280 ).
=> add string specialization to lexical_cast

include/xtensor/xview.hpp, include/xtensor/xview_utils.hpp, test/test_xview.cpp
The index computation is clearer when advancing the index in the loop instead of the accessor that's called from the lambda, and this also prevents issues with a view like `all, newaxis, all, all, all` where `advance` was called on every iteration with the newaxis offset.
=> fix view index remap issue

include/xtensor/xreducer.hpp, include/xtensor/xstorage.hpp, test/test_xreducer.cpp
Fixes #1291.
The fix of `check_element_index` will be done in a separate PR because it requires another fix in the reducers that are unrelated to this bug.
=> fixed reducer for 0D input

include/xtensor/xfunctor_view.hpp, include/xtensor/xoptional_assembly_storage.hpp
@JohanMabille I have to use forward in the move constructor because otherwise lvalue references are wrongfully casted to rvalues.
=> make functor adaptor stepper work for proxy specializations

docs/source/api/xtensor.rst, include/xtensor/xstrides.hpp, include/xtensor/xtensor.hpp, test/test_xtensor.cpp
Allows 
```cpp
#define XTENSOR_ENABLE_ASSERT 1
#include <xtensor/xtensor.hpp>
#include <xtensor/xarray.hpp>
#include <xtensor/xrandom.hpp>
#include <xtensor/xmath.hpp>
#include <xtensor/xio.hpp>
int main()
{
xt::xtensor<int, 1> a = {0,1,0,0,1};
auto idx = xt::flatten_indices(xt::argwhere(xt::equal(a,1)));
std::cout << idx << std::endl;
}
```
which gives
```none
{1, 4}
```
=> Introducing flatten_indices

include/xtensor/xsort.hpp, test/test_xsort.cpp
See https://github.com/QuantStack/xtensor-r/issues/89
CC @SylvainCorlay 
This PR:
- Adds a layout template argument to `argmin()` and `argmax()`
- Defaults it to `row_major`
Question:
- For `argmin(const xexpression<E>& e)` this is definitely necessary. For `argmin(const xexpression<E>& e, std::size_t axis)` I do not think it is necessary, but have included it for consistency. It get's passed through when the dimension of `e` is `1`, but otherwise is not used. When the dimension is `1`, the layout probably doesn't matter, right? Making this potentially unnecessary. I can remove if needed.
I've recompiled `rray` with this and all seems well and it seems to work fine!
=> Allow argmax() and argmin() to specify the layout. QuantStack/xtensor-r#89

include/xtensor/xexpression.hpp, test/CMakeLists.txt, test/test_xdatesupport.cpp
As in https://github.com/QuantStack/xtensor/pull/1329 and https://travis-ci.org/QuantStack/xtensor/jobs/477792952#L843.
`make` run command
`/usr/bin/g++-7  -DXTENSOR_USE_XSIMD -I/home/travis/build/QuantStack/xtensor/include -isystem /home/travis/miniconda/include  -march=native -Wunused-parameter -Wextra -Wreorder -Wconversion -Wsign-conversion -Wold-style-cast -Wunused-variable -std=c++17 -O3 -DNDEBUG   -std=gnu++14 -o CMakeFiles/test_xtensor_lib.dir/main.cpp.o -c /home/travis/build/QuantStack/xtensor/test/main.cpp`
There are both `-std=c++17` and `-std=gnu++14`. The latter override the former.
=> Set CMAKE_CXX_STANDARD instead of CMAKE_CXX_FLAGS

test/CMakeLists.txt
cc @JohanMabille 
This prevents gtest and gmock from being installed with xtensor when using `DOWNLOAD_GTEST=ON`.
=> Prevent installation of test artifacts

docs/source/closure-semantics.rst, include/xtensor/xexpression.hpp, test/test_xexpression.cpp
With this PR, it is now possible to write things like:
```cpp
template <class E>
auto sin_plus_cos(xexpression<E>&& e)
{
return xt::sin(xt::share(e)) + xt::cos(xt::share(e));
}
```
=> Implemented share method

include/xtensor/xoperation.hpp, test/test_xoperation.cpp
This will allow having a mix of `xoptional<T, B>` and `T` as parameters for the `where` function
```C++
using opt_type = xoptional_assembly<xarray<double>, xarray<bool>>;
auto missing = xtl::missing<double>();
opt_type a = { { 1, missing, 3 },{ 0, 1, 0 },{ missing, 4, 1 } };
double b = 1.0;
opt_type res = where(a > b, b, a); // { { 1, missing, 1 },{ 0, 1, 0 },{ missing, 1, 1 } }
```
This is now possible, even if `b` is not an `xoptional`.
=> Improve xoptional support in ternary op

include/xtensor/xfunctor_view.hpp
`xfunctor_adaptor` has a xcontainer semantics and needs a `strides()` method.
=> xfunctor_adaptor needs a strides() method to be on the lhs of an assignment

include/xtensor/xstorage.hpp, include/xtensor/xstrided_view_base.hpp, include/xtensor/xutils.hpp, test/test_xfixed.cpp
Fixes #1392.
This changes the signness of the `flat_expression_adaptor` storage and causes lots of sign conversion warnings. Needs some polish.
=> Test io on xfixed

include/xtensor/xslice.hpp
See issue #1397.
The primary goal of the patch is to add accessors to the 3 members of xrange_adaptor.
A a collateral "damage", I also converted the normalize and get_stepped_range as static private methods. All tests passed:
[==========] 879 tests from 71 test cases ran. (88 ms total)
[ PASSED ] 879 tests.
xtensor-blas tested too.
This is the other possible replacement for PR #1399, whithout any const.
I'm letting you choose which version you prefer !!!
=> Added accessors for xrange_adaptor members. Made internal methods static and private.

docs/source/missing.rst, include/xtensor/xadapt.hpp, include/xtensor/xbuffer_adaptor.hpp, include/xtensor/xfunction.hpp, include/xtensor/xutils.hpp, test/test_xadapt.cpp, test/test_xfixed.cpp
This PR allows for adaptors on shared pointers. Lifetimes of custom wrappers can be extended by copying into lambdas, as detailed in the docs.
=> shared pointer adaptor

include/xtensor/xgenerator.hpp
I want to fix #1233. But honestly I'm too deep to even know if I'm working in the right direction. Can anybody help me in the right direction?
Currently 
```cpp
#include <xtensor/xarray.hpp>
#include <xtensor/xio.hpp>
int main()
{
size_t n = 3;
xt::xarray<size_t> a = xt::arange<size_t>(n*n).reshape({n,n});
std::cout << a << std::endl;
}
```
fails to compile:
```bash
In file included from test.cpp:1:
In file included from ./xarray.hpp:18:
In file included from ./xbuffer_adaptor.hpp:20:
In file included from ./xstorage.hpp:21:
In file included from ./xtensor_simd.hpp:14:
./xutils.hpp:889:31: error: implicit instantiation of undefined template 'xt::rebind_container<long, std::initializer_list<unsigned long> >'
using type = typename rebind_container<std::ptrdiff_t, S>::type;
^ …
```
=> Added 'reshape' member to 'xgenerator' to make 'arange' more flexible

include/xtensor/xgenerator.hpp, test/test_xbuilder.cpp
This slightly improves the `reshape` method of `xgenerator` so it now accepts `std::initializer_list` arguments, handles signed integers and `-1` value, and can be called on rvalues:
```cpp
auto gen = xt::arange<double>(50).reshape({-1, 10});
//gen.shape() is {5, 10}
```
=> generic reshape for xgenerator

docs/source/api/function_index.rst, docs/source/api/xpad.rst, include/xtensor/xpad.hpp, test/CMakeLists.txt, test/test_xpad.cpp
I have started to work on  `xt::pad`. Before I add more cases maybe you can share your feedback?
Example:
```cpp
#include "xtensor.hpp"
#include "xarray.hpp"
#include "xio.hpp"
#include "xpad.hpp"
int main()
{
xt::xarray<size_t> a = xt::arange<size_t>(2*3).reshape({-1,3});
auto b = xt::pad(a, {2,3}, xt::pad_mode::periodic);
std::cout << a << std::endl;
std::cout << b << std::endl;
return 0;
}
```
=> Added `xt::pad`

include/xtensor/xmath.hpp, test/test_xnan_functions.cpp
As with the standard `variance` and `stddev` functions, these are not yet specialized for complex numbers. `nanmean` is also updated to used a `shared_forward` rather than explicit `make_xshared`. `axes` are also no longer shared in `nanmean` to match the standard calling convention of not using xcontainers as axes.
Made some small docs fixes too
=> Implemented nanvar and nanstd with tests.

include/xtensor/xio.hpp
The following code triggers signed integer overflow:
```cpp
xtensor_fixed<int, xshape<1>> v({0});
std::cout << v;
```
In `detail::recurser_run`, the 0-D expression above will call `detail::printer<int>::update(0)`:
https://github.com/QuantStack/xtensor/blob/master/include/xtensor/xio.hpp#L262
This leaves the default initalized [`m_max = 0`](https://github.com/QuantStack/xtensor/blob/master/include/xtensor/xio.hpp#L478). Thus, [`printer<int>::init()`](https://github.com/QuantStack/xtensor/blob/master/include/xtensor/xio.hpp#L443) contains
```cpp
std::streamsize(std::log10(0))
```
Since `std::streamsize` is signed integer, this translates to `std::streamsize(-HUGE_VAL)`. 
Looking at other invocations of `std::log10`, it seems they guard, either explicitly or by class invariant, against this …
=> Avoid signed integer overflow in integer printer

include/xtensor/xbuilder.hpp, test/test_xbuilder.cpp
Fixes #1482 
This does not add the `reshape` method to `xfunction` (this is not possible since it would lead to circular includes) but rather moves the cast inside the `arange_generator` so now `linspace` and `logspace` return `xgenerator` objects instead of `xfunction` objects.
=> linspace can now be reshaped

include/xtensor/xarray.hpp, include/xtensor/xoptional.hpp, include/xtensor/xtensor.hpp, test/test_xoptional.cpp
=> Added extension base to adaptors

include/xtensor/xmanipulation.hpp
See: https://github.com/QuantStack/xtensor/issues/1517#issuecomment-482578195
This fixes the following warnings upon compilation:
```
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/xtensor/include/xtensor/xoperation.hpp:22:
/Library/Frameworks/R.framework/Versions/3.5/Resources/library/xtensor/include/xtensor/xmanipulation.hpp:213:5: warning: struct template 'xiterator_adaptor' was previously declared as a class template [-Wmismatched-tags]
struct xiterator_adaptor;
^
/Library/Frameworks/R.framework/Versions/3.5/Resources/library/xtensor/include/xtensor/xbuffer_adaptor.hpp:431:11: note: previous use is here
class xiterator_adaptor : public xbuffer_adaptor_base<xiterator_adaptor<I, CI>>
^
/Library/Frameworks/R.framework/Versions/3.5/Resources/library/xt …
```
=> Change struct -> class in xiterator_adaptor

include/xtensor/xdynamic_view.hpp, test/test_xdynamic_view.cpp
This is fixing the bug @DavisVaughan experienced in #1517 
I also think this is (much) more correct. The previous function shouldn't have worked IMO since it calles the strides() function which is deleted in the leaf class ...
=> add has_linear_assign function to dynamic_view

include/xtensor/xfixed.hpp
This was throwing the following warning:
```
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/xtensor/include/xtensor/xadapt.hpp:21:
/Library/Frameworks/R.framework/Versions/3.5/Resources/library/xtensor/include/xtensor/xfixed.hpp:783:15: warning: unused type alias 'origin_type' [-Wunused-local-typedef]
using origin_type = decltype(std::move(rhs.storage()));
^
1 warning generated.
```
=> Remove unused type alias

docs/source/container.rst
Fix the example code to xt::layout_type instead of xt::layout
=> Fix example code in container.rst

include/xtensor/xassign.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xdynamic_view.hpp, include/xtensor/xfunction.hpp, include/xtensor/xfunctor_view.hpp, include/xtensor/xiterator.hpp, include/xtensor/xmath.hpp, include/xtensor/xoffset_view.hpp, include/xtensor/xoperation.hpp, include/xtensor/xoptional_assembly_base.hpp, include/xtensor/xscalar.hpp, include/xtensor/xstorage.hpp, include/xtensor/xstrided_view.hpp, include/xtensor/xtensor_simd.hpp, include/xtensor/xview.hpp, test/test_xfunctor_adaptor.cpp
=> Allows to include xsimd without defining XTENSOR_USE_XSIMD

docs/source/quickref/builder.rst
full_like function examples were wrong
=> [docs] Fix number typo in builder docs

include/xtensor/xmath.hpp
Avoids a user for accidentally using a negative "n".
=> diff: added bounds-check on maximal 'recursion' (fixes #1639)

include/xtensor/xmanipulation.hpp, include/xtensor/xoptional.hpp, include/xtensor/xtensor.hpp, include/xtensor/xtensor_forward.hpp, test/test_xstrided_view.cpp
Fixes #1662 
@DavisVaughan with this PR, the type returned by `flatten` / `ravel` has `view_semantic`:
```cpp
xt::xarray<int> x = {{1, 2, 3}, {4, 5, 6}};
auto x_view2 = xt::strided_view(x, {xt::range(0, 1), xt::range(0, 2)});
auto x_flat2 = xt::flatten<xt::layout_type::column_major>(x_view2);
x_flat2 = 15;
// x is now {{15, 15, 3}, {4, 5, 6}};
```
=> flatten now returns new type xtensor_view

include/xtensor/xsemantic.hpp
This adds a convenience method to check for assignable container types. Please review and merge if useful.
=> adding alias to check if type is xsemantic_base.

include/xtensor/xindex_view.hpp
Required for argwhere(). This PR fixes for me the use of `xindex_view` on Ubuntu 18.04 x86_64.
=> added missing include xoperation.hpp

CMakeLists.txt, test/CMakeLists.txt
The linking of XSIMD and TBB should not be done for target `xtensor` but only for the tests. I've tried to add this in a clean way to `test/CMakeLists.txt`. Please review and let me know if this makes sense?
=> Moved XSIMD and TBB dependencies only to tests

include/xtensor/xcsv.hpp, test/test_xcsv.cpp
This pull request adds following numpy-like parameters in 'load_csv' to improve compatibility with 'numpy. loadtxt'. 
New parameters:
- 'comments': The string used to indicate the start of a comment. 
- 'delimiter': The character used to separate values.
- 'skip_rows': Skip the first skip_rows lines.
- 'max_rows': Read max_rows lines of content after skip_rows lines. The default is to read all the lines.
Please see ['numpy. loadtxt'](https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html ).
=> Add numpy-like parameters in 'load_csv'.

include/xtensor/xshape.hpp
This PR adds a shape() method that returns std::array of matching size. The benefit is a shorter syntax for the container construction:
This PR adds `xt::shape({10, 20, 30})` as a shorter drop-in-replacement for `xt::static_shape<std::size_t, 3>({10, 20, 30})`.
The code is not as nice as I would hope for, because it uses a `const T(&aList)[N]`. Please suggest improvements.
=> include/xtensor/xshape.hpp: add shape() method

docs/source/getting_started.rst
Based on the question in #1688.
However...
In stead of adding this tip to the docs, shouldn't we consider adding `<<` overloads to be able to do:
```cpp
xt::xarray<int> arr {1, 2, 3, 4, 5, 6, 7, 8, 9};
std::cout << arr.shape() << std::endl;
```
?
=> Added shape print tip to docs

include/xtensor/xnpy.hpp
std::allocator supports combine or optimize away heap allocations
beyond ::operator new, which means, they use the same heap only
when they use heap, but they may not be using heap.  So it's
reasonable for MSVC to require pairing new and delete, allocate
and deallocate.
fixes: QuantStack/xtensor-io#59
=> Fix lvalue npy_file heap corruption in MSVC (was Pair allocator allocation and deallocation)

include/xtensor/xbroadcast.hpp, include/xtensor/xbuilder.hpp, include/xtensor/xscalar.hpp
I get a surprising compiler error (see below) which is fixed by this change. I'm a bit surprised by the error because I think the previous syntax was legal.
---------------------
Error-stream:
```none
In file included from /usr/local/include/xtensor/xview.hpp:26:
In file included from /usr/local/include/xtensor/xcontainer.hpp:23:
In file included from /usr/local/include/xtensor/xmath.hpp:27:
In file included from /usr/local/include/xtensor/xreducer.hpp:28:
/usr/local/include/xtensor/xbuilder.hpp:652:70: error: too many arguments to function call, expected 0, have 1
res = res && (i == axis || new_shape[i] == arr.shape(i));
~~~~~~~~~ ^
/usr/local/include/xtensor/xutils.hpp:159:31: note: in instantiation of function template specialization …
```
=> Fixing compiler error

include/xtensor/xpad.hpp, test/test_xpad.cpp
Just like BORDER_REFLECT_101 in OpenCV
=> Added `reflect` mode to xt::pad, added OpenCV-to-xtensor documentation for xt::pad

include/xtensor/xjson.hpp
This is a response to #1690. The original implementation of `xt::to_json` and `xt::from_json` only allowed as the `json` type `nlohmann::basic_json<>` (specialized with the all default types), which did not work if the client code used custom specialized version (e.g. with a custom map).
The reason why I eventually chose the longer variant (as mentioned in #1690) was that the fully "despecialized" patch using following semantics:
```c++
template<class J, class E>
enable_xexpression<E> to_json(J&, const E&);
template<class J, class E>
enable_xcontainer_semantics<E> from_json(const J&, E&);
```
did not compile with the test code, because the compiler did not know how to instantiate the constructor for `nlohmann::basic_json` type in assignments, e.g.:
```c++
xt::xarray<double> t =
{{{1, 2}, …
```
=> Despecialized xt::to_json and xt::from_json

include/xtensor/xstorage.hpp
=> Removed usage of allocator's members that are deprecated in C++17

include/xtensor/xiterator.hpp, test/test_xstrided_view.cpp
=> Fixed step_simd when underlying iterator holds an xscalar_stepper

docs/source/adaptor.rst, docs/source/api/expression_index.rst, docs/source/build-options.rst, docs/source/builder.rst, docs/source/container.rst, docs/source/indices.rst, docs/source/missing.rst, docs/source/operator.rst, docs/source/quickref/basic.rst, docs/source/quickref/builder.rst, docs/source/scalar.rst, docs/source/view.rst
Hello, 
When I read the documentation, I found some typos and errors, which I corrected to the best of my ability. I didn't check every page or explicitly looked for them, so there are probably things I have missed.
=> Fix typos and wording in documentation

include/xtensor/xnpy.hpp, test/test_xnpy.cpp
- Implements an overload of `xt::dump_npy` which returns a
NumPy-formatted file as a bytestring.
- Implements an overload of `xt::load_npy` which returns an xexpression
from a NumPy-formatted input stream.
- Adds tests for both above methods, which are implemented in terms of
existing methods in the `xnpy.hpp` file.
Support for reading and writing directly to C++ strings and/or streams
is useful for moving NumPy-formatted files around in memory or via
file-like objects other than a normal on-disk file (such as a pipe or
socket).
=> Allows (de)serialization of xexpressions in NumPy formatted strings and streams

include/xtensor/xbuilder.hpp, include/xtensor/xshape.hpp, include/xtensor/xstorage.hpp, test/test_xbuilder.cpp
This PR addresses #1750 by implementing a `concatenate_fixed` method for tensors with fixed shapes. The output shape is calculated at compile time, with `axis` passed as a template parameter.
Not sure if this is a good way to handle the original issue -- feedback is very much welcome.
=> Implement concatenation of fixed-shape tensors.

include/xtensor/xbuilder.hpp, test/test_xbuilder.cpp
Following up with https://github.com/xtensor-stack/xtensor/pull/1793#issuecomment-550202252, this PR implements a single(-ish) interface for both fixed-shape and "general"  concatenation. If _all_ operands have fixed shapes, `axis` is a compile time parameter and the resulting shape is computed at compile time. If at least one operand has a non-fixed shape, those things happen at runtime (like before).
Happy to take any feedback!
=> Unify xt::concatenate and xt::concatenate_fixed.

include/xtensor/xcontainer.hpp, include/xtensor/xfixed.hpp, include/xtensor/xfunctor_view.hpp, include/xtensor/xoptional_assembly_base.hpp, test/test_common.hpp
This provides an API more consistent with Numpy usage.
Fix #1795
=> Have xtensor container reshape method return a reference to self

include/xtensor/xmanipulation.hpp, test/test_xmanipulation.cpp
=> Implement an equivalent to numpy.roll

xtensorConfig.cmake.in
I was under the impression that e.g. `target_link_libraries(...)` would overwrite what ever was already there. But in fact it seems that it appends. In the latter case the current implementation can be simplified. 
But I'd like someone to confirm this.
=> Simplifying CMake config

CMakeLists.txt
This is currently limited to just the `xtl` target as I hadn't gotten around to using `xsimd`, but it could perhaps be handled similarly.
In the notice about version checking, I couldn't find CMake's implementation for VERSION_GREATER_EQUAL and assume that `v1.0 > v0.6.9` evaluates true.
related #1692
=> Allow use of cmake add_subdirectory(xtensor) by checking for xtl target

CMakeLists.txt
The standard library of microsoft contains in the default debug configuration
a iterator-check. This check is not compatible with the iterator design choice
of xtensor. The check should be disabled for MSVC Debug.
The check is easily disabled with the define "_ITERATOR_DEBUG_LEVEL=0"
A new option "DISABLE_MSVC_ITERATOR_CHECK" is created to control this behaviour.
The default value of the option is "ON".
With this solution, the unittest can also be executed in debug mode on a windows
machine.
- If …
=> Pass all unittest in MSVC Debug

include/xtensor/xview.hpp, test/test_xview.cpp
This pull request is related to #1189.
Row and col shortcuts for two-dimensional containers make the code more  readable.
The implementation is straight forward. The row and col function can only be called on a two-dimensional container. If the functions are called on a container with other dimension an error occurs.
If the container has compile-constant dimensions, a static_assert will fail the build.
If the container has runtime-specific dimensions, a std::invalid_argument exception is thrown.
- …
=> Add row and col facade for 2 dim container

docs/source/developer/iterating_expression.rst
=> Fixed typos in internal documentation

include/xtensor/xcontainer.hpp, test/test_xarray.cpp
cc @JohanMabille 
this was causing issues in the benchmarking code because the `xstrided_container` constructor and destructor are protected. If we return derived_cast it seems fine.
What do you think?
=> Fix reshape return

include/xtensor/xmath.hpp, test/test_extended_xmath_reducers.cpp
=> Support ddof argument for xt::variance

benchmark/CMakeLists.txt, test/CMakeLists.txt
Currently xtensor adds `-march=native` to  `CMAKE_CXX_FLAGS` unconditionally. There are certain scenarios where users need to override `-march`. For example in a virtual machine, not all available CPU features must be exposed to the guest. Or in case of a targeted build, the user may want to execute tests on behalf of the target OS, not the host OS.
This PR makes the setting of `-march` dependent on whether `CMAKE_CXX_FLAGS` already has `-march` set. This allows users to override `-march`.
=> Set -march=native only if the user did not set another -march already

include/xtensor/xview.hpp
I noticed that I cause some warning in a GCC build with my implementation of `row` and `col`.
This pull request will fix them.
=> Fix warning -Wsign-conversion in xview

benchmark/CMakeLists.txt
This PR fixes a tiny spelling mistake in `benchmark/CMakeLists.txt`: The variable `xtensor_INCLUDE_DIR` should most likely be named `xtensor_INCLUDE_DIRS`.
=> benchmark/CMakeLists.txt: fixed a tiny spelling mistake

docs/source/_static/goatcounter.js, docs/source/conf.py
This will add GoatCounter data analytics to the documentation website.
See https://www.goatcounter.com
The data will be publicly available through this URL once merged: https://xtensor_readthedocs_io.goatcounter.com
=> Add GoatCounter analytics for the documentation

include/xtensor/xstorage.hpp, test/test_xarray.cpp, test/test_xtensor.cpp
Added  noexcept(std::is_nothrow_move_assignable<value_type>::value) to the svector move assign.
Added noexcept(std::is_nothrow_move_constructible<value_type>::value) to the svector move constructor.
Currently no tests have been added.
One could possibly add a 
`static_assert(std::is_nothrow_move_constructible<xt::xarray<double>>::value, "xarray should have a nothrow move constructor")` 
and
`static_assert(std::is_nothrow_move_assignable<xt::xarray<double>>::value, "xarray should have a nothrow move assign")`
as a "test", since this now evaluates to `true`.
But I personally do not like such a `static_assert` as a test, so I have not added it.
Closes #1917
=> Added noexcept in svector

CMakeLists.txt, include/xtensor/xmanipulation.hpp, include/xtensor/xrepeat.hpp, test/CMakeLists.txt, test/test_xmanipulation.cpp, test/test_xrepeat.cpp
I implemented repeat similar to numpy.repeat (Feature request   #1383)
At the moment, all tests are fulfilled, but I'm not quite sure if the expression `xrepeat` fulfill all requirements for a `xexpression`.  Therefore, this pull request more like a draft pull request (is this feature not activated on this repo or do I just not find it?).
It would be very nice if you can give me feedback, hints and may better approaches how I can improve this first implementation.
For me there are still some open questions:
- What must be documented?
- Which primitive types should be used?
- How can I test if my expression fulfill all requirements?
- Which header should be used in the files?
Best regards
=> Add implementation of repeat (similar to numpy)

include/xtensor/xpad.hpp, test/test_xpad.cpp
Previous initialization was problematic, as:
1. it is useless (value are overwritten in the shape init loop)
2. it may have the wrong type (signed vs unsigned shape element)
=> Fix initialization of out shape in xt::tile

include/xtensor/xexception.hpp, test/test_xarray.cpp
=> Fixed check_element_index behavior for 0-D expressions

include/xtensor/xmanipulation.hpp, include/xtensor/xrepeat.hpp, test/test_xrepeat.cpp
=> xrepeat now stores const_xclosure_t<E> instead of E

.github/PULL_REQUEST_TEMPLATE.md
=> Removed requirement related to versionning in PR template

include/xtensor/xslice.hpp, include/xtensor/xtensor_config.hpp, test/test_xview.cpp
My company are trying to build an `xt::view` in a situation where we don't know at compile time which indices we need to `xt::drop`. Our solution has been to pack the indices we need to remove into an `std::vector<size_t>` and pass that as an argument to `xt::drop`, but we've discovered that this crashes when the input vector is empty.
=> Fix segfault when using xt::drop() on an empty list of indices.

include/xtensor/xmath.hpp, test/test_xnan_functions.cpp
This is to clean my leftover in PR #1749. I am sorry for the omission. Unittest are included now.
Two thoughts after this PR:
1. `nanvar` and `nanstd` do not provide the template argument to specify the return value type. while in `numpy`, an `nan` operation on an array of `np.float32` always returns an array with the same dtype;
2. I found the following promotion in the file `test_xmath_result_type.cpp`:
```cpp
CHECK_RESULT_TYPE(sum(aint), long long);
CHECK_RESULT_TYPE(sum(afloat), double);
```
while there is no such promotion in the test of this PR
```cpp
CHECK_RESULT_TYPE(nansum(aint, {1, 2}), int);
CHECK_RESULT_TYPE(nansum(afloat, {1, 2}), float);
```
I checked `numpy` and there is also no such promotion in `np.sum`.
=> Fix return dtype of nanmean and add unittest

include/xtensor/xmath.hpp, test/test_extended_xmath_reducers.cpp
Fix #1935
I add an overload since the total number of overloads should be 6 (doubled from 3 after adding an extra argument `ddof`)
The warning message changes from:
```
/home/jun/Projects/xtensor/include/xtensor/xmath.hpp: In instantiation of ‘auto xt::detail::mean(E&&, X&&, const D&, EVS) [with T = void; E = xt::xfunction<xt::detail::lambda_adapt<xt::square_fct>, xt::xfunction<xt::math::abs_fun, xt::xfunction<xt::detail::minus, const xt::xarray_container<xt::uvector<double, std::allocator<double> >, (xt::layout_type)1, xt::svector<long unsigned int, 4ul, std::allocator<long unsigned int>, true>, xt::xtensor_expression_tag>&, xt::xstrided_view<xt::xarray_container<xt::uvector<double, std::allocator<double> >, (xt::layout_type)1, xt::svector<long unsigned int, 4ul, std::allocator<long …
```
=> Fix variance overload

include/xtensor/xfunction.hpp
For ubuntu 18.04 gcc 7.5, including flag -fsanitize=undefined throws errors in xfunction.hpp line 47.
Sample project to demonstrate at https://github.com/aclifton/xtensor-asan-tests
=> Sanitizer error fix for Ubuntu 18.04 gcc 7.5

include/xtensor/xmath.hpp, test/test_xreducer.cpp
Fixed bug when zero tensor size after moving in xt::mean leads to inf mean values
=> Fixed error with zero tensor size in xt::mean

include/xtensor/xfunction.hpp
#1640 Checklist
- [V] The title and commit message(s) are descriptive.
- [V] Small commits made to fix your PR have been squashed to avoid history pollution.
- [V] Tests have been added for new features or bug fixes.
- [V] API of new functions and classes are documented.
Commit e4f2bc5b596acf28aa25aa01752f6aa74a3222f1 fixed the initialize order, but somehow in 9c8aa63cb950555d0c3136c49a470b7adf81dc06 the order was reverted when reformatting the code. This commit fix it again.
=> Fix initialize order

include/xtensor/xtensor_forward.hpp
This a follow up based on https://github.com/xtensor-stack/xtensor/pull/2054/files#r433049338
=> Adding missing "a" to "in a shared expression".

include/xtensor/xchunked_array.hpp, test/CMakeLists.txt, test/test_xchunked_array.cpp
This is preliminary work towards a chunked array, similar to what [Zarr](https://zarr.readthedocs.io) can offer in Python, which can allow for bigger-than-memory arrays (stored on disk, in the cloud...) and parallel array processing.
```cpp
#include "xtensor/xchunked_array.hpp"
int main () {
using chunked_array = xchunked_array<xt::xarray<double>>;
chunked_array arr(
{10, 10, 10},  // shape
{2, 3, 4});  // chunk shape
arr(3, 9, 8);
}
```
```
Creating chunked array with shape 10 10 10, chunk shape 2 3 4
Accessing chunked array at 3 9 8
Dimension 0: chunk 1 at 1
Dimension 1: chunk 3 at 0
Dimension 2: chunk 2 at 0
```
=> Add xchunked_array

include/xtensor/xchunked_array.hpp, test/test_xchunked_array.cpp
Unfortunately this doesn't allow to do e.g. `arr = 3.;`:
```
main.cpp: In function 'int main()':
main.cpp:20:10: error: no match for 'operator=' (operand types are 'chunked_array {aka xt::xchunked_array<xt::xarray_container<xt::uvector<double, std::alloca
tor<double> >, (xt::layout_type)1, xt::svector<long unsigned int, 4, std::allocator<long unsigned int>, true>, xt::xtensor_expression_tag> >}' and 'double')
arr = 3.;
^~
In file included from main.cpp:1:0:
../include/xtensor/xchunked_array.hpp:82:25: note: candidate: xt::xchunked_array<chunk_type>& xt::xchunked_array<chunk_type>::operator=(const xt::xchunked_arr
ay<chunk_type>&) [with chunk_type = xt::xarray_container<xt::uvector<double, std::allocator<double> >, (xt::layout_type)1, xt::svector<long unsigned int, 4, s
td::allocator<long …
```
=> Inherit from xcontainer_semantic

include/xtensor/xchunked_array.hpp, test/test_xchunked_array.cpp
If an expression is assigned to a chunked array without specifying a chunk shape, the chunk shape is taken from the expression if the expression is chunked, otherwise the chunk shape is the expression's shape, which basically means no chunk (or one chunk). 
TODO: propagate chunk shape in expressions.
=> Copy constructor gets expression's chunk_shape if it is chunked

include/xtensor/xchunked_array.hpp, test/test_xchunked_array.cpp
Instantiation is now e.g. `xt::xchunked_array<xt::xarray<xt::xarray<double>>>` instead of `xt::xchunked_array<xt::xarray<double>>`.
=> Replace template parameter chunk_type with chunk_storage

include/xtensor/xaxis_slice_iterator.hpp, include/xtensor/xfile_array.hpp, include/xtensor/xmath.hpp, include/xtensor/xset_operation.hpp
There are two more compiler warnings for which my expertise is falling short. 
```
include/xtensor/xslice.hpp:1498:51: warning: implicit conversion changes signedness: 'std::ptrdiff_t'
(aka 'long') to 'unsigned long' [-Wsign-conversion]
m_indices[i] = m_raw_indices[i] < 0 ? static_cast<std::ptrdiff_t>(shape) + m_raw_indices[i] : m_raw_indices[i];
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~
/xtensor/xslice.hpp:919:23: note: in instantiation of member function
'xt::xdrop_slice<unsigned long>::normalize' requested here
slice.normalize(e.shape()[index]);
^
```
There seems to be a reason to cast already, but to the wrong type?
```
/xtensor/xaxis_slice_iterator.hpp:147:41: warning: implicit conversion changes signedness: 'const
xt::svector<long, 4, std::__1::allocator<long>, true>::value_type' (aka …
```
=> Fixing various compiler warnings

docs/source/api/xshape.rst, include/xtensor/xshape.hpp, test/test_xshape.cpp
Fixes #2154
@JohanMabille Let's do the xtl function as well, and use it here once the new xtl release is out.
=> Adding has_shape

docs/source/sfinae.rst, include/xtensor/xutils.hpp, test/test_sfinae.cpp
Fixes #2155
@JohanMabille Is it hard to have a variadic template such that one could use `xt::has_rank<T, 1, 2>` ?
=> Adding get_rank and has_fixed_rank

include/xtensor/xtensor_config.hpp
Fixed for the issue #2168 by adding `#include <iostream>` in xtensor_config.hpp
=> Added missing header

test/test_xoperation.cpp
shifting by more than register width is undefined behavior, not the perfect test
:-)
Fix #2174
=> Fix undefined behavior while testing shifts

include/xtensor/xchunk_store_manager.hpp, include/xtensor/xchunked_array.hpp, include/xtensor/xfile_array.hpp, test/test_xchunked_array.cpp
This allows to do an assignment such as:
```cpp
// a, b and c are xchunked_array<xchunk_store_manager<...>>
c = a + b;
```
chunk by chunk, and not using `semantic_base::operator=(e)`, which would create a temporary chunked array.
=> Fix xchunked_array assignment

include/xtensor/xchunk_store_manager.hpp, include/xtensor/xchunked_array.hpp, include/xtensor/zarray.hpp, include/xtensor/zarray_impl.hpp, test/test_zarray.cpp
@davidbrochart with this PR, you can write things like:
```cpp
xchunked_array<xarray<xarray<double>>> a(shape, chunk_shape);
zarray za(a);
shape_type res = za.as_chunked_array().chunk_shape();
```
This is not perfect yet since we cannot assign to a chunked_array with this wrapper (it will assign to the cache xarray of the wrapper instead of the wrapped chunked array) but we'll fix that later.
=> First implementation of zchunked_wrapper

xtensorConfig.cmake.in
Commit cf840966b27d18200cd423cf8ecb923cb0179e83 introduced the use of cmake macro `CHECK_CXX_COMPILER_FLAG `. This leads to an error when using this config from another cmake project:
```
CMake Error at /opt/xtensor/lib/cmake/xtensor/xtensorConfig.cmake:70 (CHECK_CXX_COMPILER_FLAG):
Unknown CMake command "CHECK_CXX_COMPILER_FLAG".
Call Stack (most recent call first):
CMakeLists.txt:47 (find_package)
```
This PR fixes this issue by including the cmake lib needed to be able to call this macro?
=> Fix generated cmake config to include missing required lib

include/xtensor/xstorage.hpp
This PR addresses a very minor problem: Inside a function there is a shadowing declaration from the higher context. This PR renames the local declaration to clarify the intended meaning.
=> xstorage.hpp: Renamed a shadowing variable inside a function

include/xtensor/xassign.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xgenerator.hpp
This is again a tiny change, to rename a local typedef that shadows a class typedef. Thanks for considering it!
=> xcontainer.hpp: Renamed a shadowing type name inside a function

CMakeLists.txt, test/CMakeLists.txt
This is a minor PR that improves the integration of testing and specifically of GTest. It brings better compatibility with FindGTest from (future) cmake.
Please let me know if it would need more motivation? :-)
=> CMake: Modernized GTest-integration

include/xtensor/xnpy.hpp
Commit 808ceb4a803909a309a00d72fbfd633d81843ea8 introduced an issue when `xnpy.hpp` is included in two different objects that are then linked together. The `host_endian_char` becomes exported in both objects, resulting in a `multiple definition` error when linking these objects together.
This patch fixes this issue by making it a static variable so that it's not exported.
=> xnpy.hpp: fix multiple definition of 'host_endian_char' variable when included in different linked objects

include/xtensor/xnpy.hpp
@serge-sans-paille Do you think it would be worth encapsulating the different const variables as static variables inside functions to avoid storage duplication?
=> Made global variable const to force internal linkage

include/xtensor/xbuilder.hpp, include/xtensor/xeval.hpp, include/xtensor/xexpression_traits.hpp, include/xtensor/xpad.hpp, include/xtensor/xstrided_view.hpp
This PR adds the construction of a `temporary_type` from a tag expression. This allows to use `xeval` for other expressions such as those used in `xtensor-sparse`.
=> Improve xeval

docs/source/compilers.rst, include/xtensor/xadapt.hpp, include/xtensor/xbroadcast.hpp, include/xtensor/xbuilder.hpp, include/xtensor/xgenerator.hpp, include/xtensor/xindex_view.hpp, include/xtensor/xmanipulation.hpp, include/xtensor/xmath.hpp, include/xtensor/xnorm.hpp, include/xtensor/xrandom.hpp, include/xtensor/xreducer.hpp, include/xtensor/xsort.hpp, include/xtensor/xstrided_view.hpp, include/xtensor/xtensor_config.hpp, test/test_xadapt.cpp, test/test_xbuilder.cpp, test/test_xeval.cpp, test/test_xreducer.cpp, test/test_xstrided_view.cpp
Proposition to drop support of Clang 3.* versions by removing patches specific to these compiler versions since they are not part of the [build matrix](https://github.com/xtensor-stack/xtensor/blob/master/.azure-pipelines/azure-pipelines-linux-clang.yml) anymore.
The changes made include:
- `OLD_CLANG`s pre processor definitions are removed
- Dedicated tests are removed
- `Reducer` macro is unified
- Documentation about Clang (compilers section) is updated
During refactoring, I noticed the `XTENSOR_NAN_REDUCER_FUNCTION` defined [here](https://github.com/xtensor-stack/xtensor/blob/2ed3b10afe9f5d16246aae4ddbfae6c35b2ff973/include/xtensor/xmath.hpp#L2419) is not used. The `XTENSOR_REDUCER_FUNCTION` is used instead (see [`nansum`](https://github.com/xtensor-stack/xtensor/blob/2ed3b10afe9f5d162 …
=> Drop support of 3.* Clang versions

include/xtensor/xhistogram.hpp, test/test_xhistogram.cpp
Fix #1546
Performance of numpy:
```
In [1]: import numpy as np
In [2]: x = np.arange(1e6)
In [3]: %timeit np.histogram(x, 100)
17.3 ms ± 1.44 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
Performance of this fix:
```
#include "xtensor/xtensor.hpp"
#include "xtensor/xhistogram.hpp"
#include "chrono"
int main()
{
xt::xtensor<double, 1> x = xt::arange(1000000);
auto start = std::chrono::high_resolution_clock::now();
xt::histogram(x, size_t(100));
auto end = std::chrono::high_resolution_clock::now();
std::cout << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count() << std::endl;
// output varies between 7 - 11 ms
// before this fix, output is > 40 ms
}
```
=> Improve histogram performance with equal bin sizes

.azure-pipelines/azure-pipelines-win.yml, environment-dev.yml, include/xtensor/xoperation.hpp, test/test_xmath_result_type.cpp
The binary operators operating on `std::complex` of different base types (e.g. `std::complex<float>` and `std::complex<double>`) are not working.
This PR provides overloading of operators for this case. A unit test of *plus* operator between mixed complex types is also implemented.
Do we need to implement tests for all binary operators?
=> Fix binary operators on complex

docs/source/compilers.rst, include/xtensor/xaccumulator.hpp, include/xtensor/xassign.hpp, include/xtensor/xmath.hpp, include/xtensor/xoptional.hpp, include/xtensor/xreducer.hpp, test/test_xmath_result_type.cpp, test/test_xnan_functions.cpp, test/test_xreducer.cpp
Fix the assignment of `xreducers` operating on optional arrays (incl. `xarray<xoptional<T>>`, `xarray_optional<T>` and `xoptional_assembly<T>`.
Change return policy of reducers and accumulators to non casting to the init type, even when init type is passed explicitely using the optional template parameter. Refactor accumulators accordingly.
PR also includes:
- disambiguish init and result types naming
- update and extend testing
Let me know if it should be good to explain the return type policy in the docs!
=> Fix reducers assignment

include/xtensor/xhistogram.hpp, test/test_xhistogram.cpp
Since `histogram_bin_edges` returns a `xtensor`, the two histogram overloads will not work if `data` is other containers like `pytensor`, `xarray`, etc.
=> Fix histogram compatibility with containers beyond xtensor

test/test_xreducer.cpp
This PR disables the optional reducer assignment tests when using TBB or OPENMP. It seems that we have a race condition and we don't want it to make unrelated PRs fail.
=> Disable optional reducer assignment test with TBB

include/xtensor/xchunked_array.hpp, test/test_xchunked_array.cpp
This allows to write:
```cpp
auto a = chunked_array<int>({4, 4}, {2, 2});
```
=> Support initialized list for chunked_array shapes

include/xtensor/xeval.hpp, test/test_xeval.cpp
Add `as_strided` free function to evaluate `xexpression`s that don't have data interface or don't have the expected layout.
The implementation is broadly inspired from [xtensor-blas utils](https://github.com/xtensor-stack/xtensor-blas/blob/master/include/xtensor-blas/xblas_utils.hpp) and may be useful in other contexts. This is the main reason of this PR.
Details:
- add docstrings
- add tests
`has_data_interface` has been used in SFINAE to discriminate `xexpression`s that hold data or not, instead of `is_container` which is used in `xt::eval`. Those 2 conditions may or may not be equivalent.
Let me know if it's preferable to switch to `is_container` @SylvainCorlay .
=> Add as_strided free function

docs/source/api/xrandom.rst, include/xtensor/xrandom.hpp, test/test_xrandom.cpp
Close #2213. This add an overload to `xt::random::choice` that takes as an extra argument an (unormalized) probability vector.
- I have added inline documentation but did not manage to see if it rendered properly since it appears to be broken #2242.
- There are currently no check that the weight vector is positive, although it is required, since I figured it would be unnecessarily costly. Is there a macro that could be relevant to use here `XTENSOR_ASSERT` maybe?
=> Implement xt::random::choice with weights vector

include/xtensor/xslice.hpp, test/test_xview.cpp
=> Fixed broadcasting with keep_slice that holds a single element

test/test_xoptional.cpp
It's currently not possible to xt::cast an array of optionals. This is an attempt to support that pattern.
An alternative implementation would be to add an explicit cast operator to optionals, I'm open to any suggestion!
=> Make xt::cast and xtl::optional compatible.

include/xtensor/xmath.hpp
one of the `xt::mean` implementation was missing the assert found in other `xt::mean` implementation.
=> Extra assert in mean computation wrt. ddof

include/xtensor/xexpression_traits.hpp, include/xtensor/xmath.hpp, include/xtensor/xoperation.hpp, test/test_xaccumulator.cpp, test/test_xmath_result_type.cpp, test/test_xreducer.cpp
Remove use of `xtl::big_promote_type_t` for `reducer`s and `accumulator`s init value type.
The result type is then only driven by the init value type and the expression value type, given the C++ binary operators rules.
This change is backward incompatible.
=> Remove reducer big_promote_type

docs/source/adaptor.rst, docs/source/container.rst, docs/source/developer/concepts.rst, docs/source/expression.rst, docs/source/external-structures.rst, docs/source/file_loading.rst, docs/source/getting_started.rst, docs/source/operator.rst, docs/source/quickref/basic.rst, docs/source/quickref/chunked_arrays.rst, docs/source/quickref/iterator.rst, docs/source/quickref/manipulation.rst, docs/source/related.rst, docs/source/scalar.rst, docs/source/view.rst
For everyone sake, I thought it would be easier to split #2248 in multiple PR.
Here we change all `#include` statements in the doc to use the format `#include <xtensor/...>`
=> Documentation improvement Part #C

include/xtensor/xchunked_array.hpp
The extension mechanism was mainly needed to store a JSON object, which is now done in zarray.
=> Remove chunked array extension mechanism

include/xtensor/xfunctor_view.hpp
=> Added missing shape_type in xfunctor_stepper

include/xtensor/xassign.hpp, include/xtensor/xcontainer.hpp, test/test_xmanipulation.cpp
Fix `simd_assign` trait in `xexpression_assigner_base<xtensor_expression_tag>::assign_data` method.
Also fix `xstrided_container` layout that is currently overriden by the `resize` method. Since there is no guarantee that the storage is contiguous, the `layout` property must not be overriden.
The current notion of storage `layout` mixes :
- the storage layout itself
- the data contiguity
- `layout_type::row_major` and `layout_type::column_major` *implies* the data are contiguous
- `layout_type::dynamic` *implies* the data are **not** contiguous
Maybe there is opportunity to distinguish those 2 notions to improve performances on `layout_type::dynamic` layout.
@SylvainCorlay @JohanMabille
=> Fix simd assign_data

test/test_xrandom.cpp
Currently a test for shuffle is disabled on MSVC and OS X, and unconditionally enabled on Linux:
https://github.com/xtensor-stack/xtensor/blob/be8fe0891b869946540505b39ba914096f3f0ceb/test/test_xrandom.cpp#L206
The same test also fails with Clang 11.0.1 on Linux. 
I'm under the impression that the test may be faulty, because it looks as if sub-arrays get shuffled which (according to the documentation of `shuffle`) is acceptable. But its well possible I did not fully grasp the tests idea.
In any case, this PR disables the test also for Clang on Linux.
=> test/test_xrandom.cpp: Disabled a failling shuffle test also for Clang

include/xtensor/xaxis_iterator.hpp, include/xtensor/xhistogram.hpp
fix more on `-Wunused-local-typedef` warning.
The second typedef is not used if `XTENSOR_ENABLE_ASSERT` is not defined.
=> fix more on -Wunused-local-typedef warning

docs/source/api/xhistogram.rst, include/xtensor/xhistogram.hpp, test/test_xhistogram.cpp
I think two more overloads would be required to make `histogram` work better with the fast equal-bin implementation. If you agree, I will add the unittest and the documentation.
=> Add two more overloads for histogram

cmake/FindTBB.cmake
=> Fixed FindTBB.cmake

include/xtensor/xbuilder.hpp, test/test_xbuilder.cpp
A follow up for #2306
If `linspace` only have one point, the only element should not be set to the `stop` value. There is an oversight in my previous implementation. However, there is also a bug in the original test, which failed to catch the bug :-)
=> Fix linespace with only one point

cmake/FindTBB.cmake
This does not affect `xtensor` now. But with the current version file, the version finding will not work since `tbb/version.h` actually points to `/oneapi/tbb/version.h`. You may need this in the future.
btw TBB 2021.1 breaks everything for me :-(
=> Use the correct version file for TBB since 2021.1

include/xtensor/xbuffer_adaptor.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xiterator.hpp, include/xtensor/xstorage.hpp
This fixes the issue introduced in #2292 AND the issue #2292 was working around. This should fix https://github.com/xtensor-stack/xtensor-blas/issues/185 and the runtime error from https://github.com/xtensor-stack/xtensor/issues/2321.
cc @adriendelsalle
=> Fixed layout issue in container classes

include/xtensor/xchunked_array.hpp
This avoids a segmentation fault when a `chunked_array` and its  `chunk_storage` have different shape types.
=> Fixed grid_shape return type

include/xtensor/xcontainer.hpp, include/xtensor/xexception.hpp, test/test_xarray.cpp, test/test_xtensor.cpp
Fixes #1903.
@emmenlau notice that you have to enable assertions (i.e. `#define XTENSOR_ENABLE_ASSERT`) to have an exception.
=> Added assertion in resize method

include/xtensor/xview.hpp
This fixes a performance issue. Not sure what kind of test to add for that. Also, this might not be the only place where updating the `m_strides_computed` was forgotten. It's just what we saw when we profiled the code.
=> Performance fix: set m_strides_computed = true after computing

include/xtensor/xsort.hpp, test/test_xsort.cpp
Fixes a bug where
```cpp
xt::xtensor<double, 2> A = {{1.4, 1.3, 1.2, 1.1}};
std::cout << xt::argsort(A) << std::endl;
```
result in unallocated output
=> argsort: catching zeros stride leading axis (bugfix)

include/xtensor/xaccessible.hpp, include/xtensor/xcontainer.hpp, include/xtensor/xdynamic_view.hpp, include/xtensor/xfunction.hpp, include/xtensor/xfunctor_view.hpp, include/xtensor/xmasked_view.hpp, include/xtensor/xoptional_assembly_base.hpp, include/xtensor/xscalar.hpp, test/test_xarray.cpp, test/test_xfunction.cpp, test/test_xview.cpp
Adding `front()` and `back()` convenience methods
Fixes https://github.com/xtensor-stack/xtensor/issues/2282
=> Adding `front()` and `back()` convenience methods

include/xtensor/xassign.hpp, test/CMakeLists.txt, test/test_xassign.cpp, test/test_xfixed.cpp
With this pr the following is compiling:
```C++
pyarray<int>    a1  { 0,  1,  2};
xt::xarray<int> a2  { 0,  2,  4};
xt::noalias(a1) += a2;
```
```C++
xt::xtensor_fixed<int, xt::xshape<2>> a1 = {2,3};
xt::xarray<int> a2{ 0,  2,  4};
xt::noalias(a1) += a2;
```
=> changed impl computed_assign st shapes of different types are supported

include/xtensor/xutils.hpp
- clang : 13.0.0
- libstdc++ : 112.1
- xtensor : 0.24.0
When I use xtensor with libstdc++ version 11 with _GLIBCXX_USE_CXX11_ABI = 0, there are compilation error as following:
```
xxx/include/xtensor/xutils.hpp:654:51: error: no template named 'has_trivial_default_constructor' in namespace 'std'; did you mean 'is_trivially_default_constructible'?
using xtrivially_default_constructible = std::has_trivial_default_constructor<T>;
~~~~~^
/usr/bin/../lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/type_traits:1151:12: note: 'is_trivially_default_constructible' declared here
struct is_trivially_default_constructible
^
1 error generated.
```
I found `has_trivial_default_constructor` had been removed since libstdc++ 7.
Please refer …
=> has_trivial_default_constructor has been removed from libstdc++ since version 7.

docs/source/indices.rst, include/xtensor/xcontainer.hpp, include/xtensor/xexception.hpp, include/xtensor/xstrides.hpp, test/test_xtensor.cpp
I had to move the `static_cast<std::ptrdiff_t>(...)`. If forgot why it is there in the first place, so I don't know if this changes anything
Fixes https://github.com/xtensor-stack/xtensor/issues/2486
=> Adding `xt::missing` to `operator()`

include/xtensor/xaccessible.hpp, include/xtensor/xstrides.hpp, test/test_xtensor.cpp
This was missing. I think this covers all operators now.
=> Adding `xt::missing` functionality to `.periodic(...)`, `.at(...)`, and `.in_bounds(...)`

docs/Doxyfile, docs/source/api/xarray_adaptor.rst, docs/source/api/xtensor_adaptor.rst, include/xtensor/xadapt.hpp, include/xtensor/xeval.hpp
=> Fixed the documentation of adapt functions

include/xtensor/xsort.hpp
Hopefully this avoids mysterious segmentation faults on Windows
=> Simplifying `argmin` and `argmax` where possible

test/test_extended_xsort.cpp
Build error induced by taking the value_type of a T& instead of T accomplished though std::decay of T&
closes #2505
=> Fixed build error in MSVC 2019 by decaying decltype to base type

include/xtensor/xmath.hpp, test/test_xmath.cpp
Added a 1D convolution function with a similar API as numpy and provide a couple small test to verify it's functionality.
Fixes #1928
=> Added xt::convolve

docs/source/external-structures.rst, include/xtensor/xarray.hpp, include/xtensor/xbuffer_adaptor.hpp, include/xtensor/xtensor.hpp, test/test_xadapt.cpp
Fixes https://github.com/xtensor-stack/xtensor/issues/2519
=> Adding `reset_data` to `xbuffer_adaptor` and `reset_buffer` to `*adaptor` to replace the pointer without any reallocation.

include/xtensor/xarray.hpp, include/xtensor/xfixed.hpp, include/xtensor/xtensor.hpp
Signed-off-by: Boris Fomitchev <bfomitchev@nvidia.com>
Fixes issue I reported earlier : https://github.com/xtensor-stack/xtensor/issues/2524
This appears to be EDG frontend bug.
=> Workaround for EDG C++ frontend bug

include/xtensor/xsort.hpp
Fix confirmed in https://github.com/tdegeus/FrictionQPotSpringBlock/pull/46 , so ready from my side!
=> Adding cast to deal with xtensor-python's signedness of shape

include/xtensor/xarray.hpp, include/xtensor/xtensor.hpp, include/xtensor/xutils.hpp
=> Adding missing `rank` to `xtensor_adaptor`

include/xtensor/xfunction.hpp
This pr adds the ability to have `xfunction` with values that are references.
For example:
```cpp
const int v = 5;
auto replace = [&v](int a) -> int& { return v; };  // before only `-> int` was possible
auto replace_vectorized = xt::vectorize(replace);
```
This is nice if we don't want to create temporary values for some complex types.
For example one of our use cases was to apply color lookup table to grayscale image:
```cpp
xtensor<uint8_t, 2> grayscale({100, 100});
LookupTable lookup_table; // this holds inside std::vector<Color> for ARGB colors lookup
auto colorise = [&lookup_table](uint8_t gray) -> Color& { return lookup_table.getMappedValue(gray); };
auto colorised = xt::vectorize(colorise)(grayscale);
for (Color& color : colorised) {
// now we can iterate colorised image without …
```
=> Enabling reference value types for xfunction.

test/CMakeLists.txt
xtensor finds the threads package. But `find(Threads)` fails with the error message:
```
FindThreads only works if either C or CXX language is enabled
```
The project needs to be defined first (enabling CXX language)
Fixed by debian patch
https://salsa.debian.org/science-team/xtensor/-/blob/master/debian/patches/test_findpackage_after_project.patch
Fixes #2498
=> find external packages (threads) after defining project

docs/source/quickref/builder.rst
the commit fixes a typo in builders documentation, in `hstack`, the second example uses `hastack` (mind the extra "a").
=> fix doc typo: "hastack" to "hstack"

docs/source/developer/concepts.rst
Fix a small typo in line 49, concepts.rst. As is shown in the real code, the correct function prototype is `const derived_type& derived_cast() const & noexcept;` while the original one in the doc is `const derived_type& derived_cast() & noexcept;`, which is obviously wrong since it's not a valid function overload.
=> fix a tiny typo in concepts.rst

test/test_xreducer.cpp
Partially fix #2328 for i386 architecture.
=> Use allclose in test_xreducer

include/xtensor/xmath.hpp, include/xtensor/xutils.hpp
Fix https://github.com/xtensor-stack/xtensor-r/issues/85
Solution discussed with @JohanMabille
=> Specialize get_strides_type for xbuffer_adaptor

docs/source/api/xshape.rst, docs/source/api/xsort.rst
Current use of `.. doxygengroup` breaks links for reference of style ``:cpp:func:`xt::func` ``.
With this fix, we can restore the links without changing all references.
@tdegeus
=> Fix missing namespace in doxygengroup

include/xtensor/xindex_view.hpp, test/test_xindex_view.cpp
=> Change xindex_view reference type to handle const data

include/xtensor/xshape.hpp
Fixes https://github.com/xtensor-stack/xtensor/issues/2559
=> Adding missing `defgroup` `xt_xshape`

include/xtensor/xiterator.hpp
Following discussion with @JohanMabille, the `to_end` brings the stepper past-end in **all** dimensions.
=> Fix xindexed_view::to_end

docs/source/compilers.rst, include/xtensor/xstrides.hpp, test/test_xsort.cpp
Works around an msvc optimizer bug which occurs when shape.size() == 0. 
Surrounding the problematic region to prevent illegal access that occurs on windows MSVC optimized builds (/O1, /O2).
- allows construction of 0-sized xarray and xtensors (e.g. xt::xtensor<size_t, 0>)
- also fixes xt::argmax() crashing 
Fixes #2551 
Fixes #2568 
Fixes #2596
=> fixes #2568. MSVC optimizations causing segmentation faults in optimized builds.

CMakeLists.txt, xtensor.pc.in
xternsor is header only library, so prefer arch-independed paths for pkgconfig and cmake.
See for reference: https://github.com/xtensor-stack/xtl/commit/d877d94836aff4d0f727acf3eaab8f4880ecb625
=> Install as arch-independent

include/xtensor/xnpy.hpp, test/test_xnpy.cpp
* fix `struct npy_file`'s Move Assignment.
* fix memory leak when moving to a npy_file with buffer.
=> fix npy_file move assignment

test/CMakeLists.txt
When `STATIC` keyword is missed from `add_library()` arguments, the library type (static/shared) can still be controlled via `-DBUILD_SHARED_LIBS` command line option.
While `-DBUILD_SHARED_LIBS=OFF` is the default value, it is common practice to set this `ON` while building packages for major Linux distributions. In order to specify that the library is meant to be static unconditionally, use `STATIC` keyword here.
=> Explicitly declare test_xtensor_core_lib as STATIC

.pre-commit-config.yaml, benchmark/benchmark_view_access.cpp, include/xtensor/xaccumulator.hpp, include/xtensor/xeval.hpp, include/xtensor/xfixed.hpp, include/xtensor/xfunction.hpp
Fixes https://github.com/xtensor-stack/xtensor/issues/2637 
Fixes https://github.com/xtensor-stack/xtensor/issues/2632 
Fixes https://github.com/xtensor-stack/xtensor/issues/2633
=> Manule style fixes

.clang-format, .pre-commit-config.yaml, include/xtensor/xarray.hpp, include/xtensor/xcomplex.hpp, include/xtensor/xdynamic_view.hpp, include/xtensor/xexception.hpp, include/xtensor/xfixed.hpp, include/xtensor/xio.hpp, include/xtensor/xiterator.hpp, include/xtensor/xmanipulation.hpp, include/xtensor/xmasked_view.hpp, include/xtensor/xmath.hpp, include/xtensor/xnorm.hpp, include/xtensor/xoptional.hpp, include/xtensor/xoptional_assembly_base.hpp, include/xtensor/xreducer.hpp, include/xtensor/xshape.hpp, include/xtensor/xstorage.hpp, include/xtensor/xstrides.hpp, include/xtensor/xtensor.hpp, include/xtensor/xutils.hpp, include/xtensor/xview.hpp, test/test_xindex_view.cpp, test/test_xmanipulation.cpp, test/test_xnpy.cpp, test/test_xreducer.cpp, test/test_xrepeat.cpp
This option is experimental, let's see if it works.
=> Align qualifiers using clang-format

include/xtensor/xcontainer.hpp, test/test_xadapt.cpp
The .fill() method of xcontainer doesn't check if the container is actually contiguous, and therefore makes mistakes for noncontiguous containers. This is a quick fix for that.
For instance, the following fills the first four values of `data` with zeros, instead of the ones that correspond to the first column.
```
auto data = std::vector<double>{1, 2, 3, 4, 5, 6, 7, 8};
auto adapter = xt::adapt(data.data(), 4, xt::no_ownership(), std::vector<size_t>{4, 1}, std::vector<size_t>{2, 1});
adapter.fill(0)
```
=> Fix a bug where .fill doesn't work for a xcontainer that is non-contiguous

docs/source/api/container_index.rst, docs/source/api/xadapt.rst, include/xtensor/xadapt.hpp, test/test_xadapt.cpp
Fixes https://github.com/xtensor-stack/xtensor/issues/2663
The name is up for discussion!
=> Adding aliases `xt::xtensor_pointer` and `xt::xarray_pointer`

docs/source/api/xarray_adaptor.rst
It seems that I introduced some duplicates in https://github.com/xtensor-stack/xtensor/pull/2665
=> Removing duplicates from documentation

include/xtensor/xpad.hpp, test/test_xpad.cpp
Fixes #2699. Added edge pad_mode and tests.
=> Added 'edge' pad mode for xt::pad

include/xtensor/xfunctor_view.hpp, include/xtensor/xiterator.hpp, include/xtensor/xstrided_view.hpp
This merge request fixes some issues with iterators.
```cpp
xarray<int> a = { {{0, 1, 2, 3},
{4, 5, 6, 7},
{8, 9, 10, 11}},
{{12, 13, 14, 15},
{16, 17, 18, 19},
{20, 21, 22, 23}} };
auto view = dynamic_view(a, { 1, keep(0, 2), range(1, 4) });
// shape: {1, 2, 3}
// old version
view.end(); // index {1, 2, 3}
std::prev(view.end()); // index {1, 2, 2}
// out of bounds access
*view.rbegin(); // index {1, 2, 2}
// new version
view.end(); // index {0, 1, 3}
std::prev(view.end()); // index {0, 1, 2}
// correct access
*view.rbegin(); // index {0, 1, 2}
```
=> Fixing some iterator issues

include/xtensor/xio.hpp
Static functions (different to static class/struct methods) are a language feature for prevent external linkage and avoid polluting the global namespace similar to using an anonymous namespace. For a C++20 module to wrap xtensor it is fine for a normal exported function to call a function with internal linkage, but not if it shares a template parameter with it ([see p1815r2](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1815r2.html)).
In order to export the useful API definitions `pretty_print` and `operator<<` from `xtensor/xio.hpp`, `recurser_run` needs to support external linkage.
=> Support external linkage for "recurser_run"

include/xtensor/xrepeat.hpp
The internal type of std::accumulate is determined by the init parameter.
Initializing with 0 (int) results in a "conversion from 'size_t' to 'type', possible loss of data" warning in MSVC.
Here is a [link](https://godbolt.org/z/8xaYsTjvj) showcasing the warning in Compiler Explorer.
=> Fix conversion warning in xrepeat

include/xtensor/xtensor_config.hpp
- [ x] The title and commit message(s) are descriptive.
- [ x] Small commits made to fix your PR have been squashed to avoid history pollution.
- [ x] Tests have been added for new features or bug fixes.
- [ x] API of new functions and classes are documented.
Updated to allow overriding of alignment when using XSIMD. If the user doesn't provide an overriding value then the default XSIMD value is used. This fixed linker issues when different default vectorization settings are used between libraries within the same project. The intel C++ compiler requests 16 alignment for AVX while MSVC defines it to 32 so it's nice to be able to pin the alignment at the higher of the two.
=> Update to use XTENSOR_DEFAULT_ALIGNMENT when using XSIMD

.github/workflows/ci.yml, CMakeLists.txt, README.md, benchmark/CMakeLists.txt, test/CMakeLists.txt
- [ x] The title and commit message(s) are descriptive.
- [x ] Small commits made to fix your PR have been squashed to avoid history pollution.
- [x ] Tests have been added for new features or bug fixes.
- [ x] API of new functions and classes are documented.
Fix #2743 
Tiny PR to silence warnings. No one should be using CMake 3.1 in this day and age
=> Bump cmake version and resolve build issues

.github/workflows/ci.yml, CMakeLists.txt, benchmark/CMakeLists.txt, include/xtensor/xstrided_view.hpp, test/CMakeLists.txt, test/test_xstrided_view.cpp
- [ x] The title and commit message(s) are descriptive.
- [ x] Small commits made to fix your PR have been squashed to avoid history pollution.
- [ x] Tests have been added for new features or bug fixes.
- [ x] API of new functions and classes are documented.
Fix #2417
@JohanMabille  @tdegeus this is failing the type check at test_xstrided_view.cpp(709). I was unable to cast the underlying `std::array` to unsigned using `std::make_unsigned` as I expected. Any help would be appreciated. I think apart from that it should be identical to the previous implementation as it only implements the check when given signed integers and preserves static lengths using `std::array<T,N>`
=> [WIP] Make reshape_view accept -1 as a wildcard dimension

.github/workflows/ci.yml, include/xtensor/xsort.hpp, test/test_xsort.cpp
Fixes https://github.com/xtensor-stack/xtensor/issues/2752
Todo: change to `constexpr` if C++17 support is enabled
=> Fixing bug in `argmin`/`argmax` called with `axis` on rank-1 container

test/test_xcomplex.cpp
Partially fix #2328 on x86 32-bit architecture.
=> Use L suffix for long double constants

test/test_xbuilder.cpp
On x86 architecture multiplying `3.f` on `0.3f` results into different values in compile time and runtime.
Partially fix #2328
=> Use 1/4 step for testing arange

include/xtensor/xindex_view.hpp
`#include <array>` for std::array
Namespace qualify `to_array` as `xt::to_array` to avoid ambiguous overload from adl of `std::array`. Note: This could, perhaps, be `std::to_array` instead.
=> Minor xindex_view to_array cleanup

CMakeLists.txt, include/xtensor/xbroadcast.hpp, include/xtensor/xfunction.hpp, include/xtensor/xgenerator.hpp, include/xtensor/xsemantic.hpp, include/xtensor/xutils.hpp
Currently the default behaviour of `xsemantic_base<D>::operator=(const xexpression<E>& e)` is to create a temporary copy of `e` to avoid any problems with overlapping memory. However, if the user doesn't use some obscure strides for the containers, a check if the pointers from `begin` and `end` elements don't overlap is sufficient. Based on our benchmarks, depending on the size of the containers brings huge speedups for some use cases (up to `90%` in case of views). This is also achievable with `noalias`, but it's hard to enforce its usage and adding a compilation flag `XTENSOR_FORCE_TEMPORARY_MEMORY_IN_ASSIGNMENTS` that allows changing this behaviour is highly beneficial. 
I'm also attaching the benchmark results we obtained: 
[xtensor_assign_benchmark_results.ods](https://github.com/xten …
=> Adding the ability to enable memory overlap check in assignment to avoid unneeded temporary memory allocation

include/xtensor/xmath.hpp, include/xtensor/xutils.hpp
GCC 13 may give warnings like:
```
/home/maik/scratch/schaap/everybeam/include/xtensor/xutils.hpp:33:6: error: "_MSC_VER" is not defined, evaluates to 0 [-Werror=undef]
33 | #if (_MSC_VER >= 1910)
|      ^~~~~~~~
In file included from /home/maik/scratch/schaap/everybeam/include/xtensor/xcontainer.hpp:25,
from /home/maik/scratch/schaap/everybeam/include/xtensor/xtensor.hpp:20:
/home/maik/scratch/schaap/everybeam/include/xtensor/xmath.hpp:1077:69: error: "GCC_VERSION" is not defined, evaluates to 0 [-Werror=undef]
1077 | #if (defined(_MSC_VER) && _MSC_VER < 1910) || (defined(__GNUC__) && GCC_VERSION < 49999)
|                                                                     ^~~~~~~~~~~
```
This PR avoids these warnings by 
- Adding a check if _MSC_VER is defined.
- Avoiding using …
=> Avoid warnings in compiler version checks

CMakeLists.txt, environment-dev.yml, include/xtensor/containers/xadapt.hpp, include/xtensor/containers/xscalar.hpp, include/xtensor/core/xassign.hpp, include/xtensor/core/xexpression.hpp, include/xtensor/core/xfunction.hpp, include/xtensor/core/xiterable.hpp, include/xtensor/core/xiterator.hpp, include/xtensor/core/xmath.hpp, include/xtensor/core/xoperation.hpp, include/xtensor/core/xshape.hpp, include/xtensor/generators/xbuilder.hpp, include/xtensor/io/xjson.hpp, include/xtensor/io/xnpy.hpp, include/xtensor/misc/xexpression_holder.hpp, include/xtensor/misc/xmanipulation.hpp, include/xtensor/misc/xpad.hpp, include/xtensor/reducers/xblockwise_reducer.hpp, include/xtensor/reducers/xnorm.hpp, include/xtensor/reducers/xreducer.hpp, include/xtensor/utils/xutils.hpp, include/xtensor/views/xdynamic_view.hpp, include/xtensor/views/xfunctor_view.hpp, include/xtensor/views/xslice.hpp, include/xtensor/views/xstrided_view.hpp, include/xtensor/views/xstrided_view_base.hpp, include/xtensor/views/xview.hpp, test/CMakeLists.txt
=> Upgraded to xtl 0.8.0 and C++17

.github/workflows/linux.yml, CMakeLists.txt, test/test_xfixed.cpp, test/test_xsimd.cpp
=> Migrated to more recent compilers

include/xtensor/utils/xutils.hpp, test/test_xutils.cpp
- [ x] The title and commit message(s) are descriptive.
- [x ] Small commits made to fix your PR have been squashed to avoid history pollution.
- [ x] Tests have been added for new features or bug fixes.
- [ x] API of new functions and classes are documented.
=> Implement apply with std 17

include/xtensor/containers/xfixed.hpp, include/xtensor/containers/xscalar.hpp, include/xtensor/containers/xstorage.hpp, include/xtensor/core/xexpression.hpp, include/xtensor/core/xshape.hpp, include/xtensor/generators/xbuilder.hpp, include/xtensor/generators/xgenerator.hpp, include/xtensor/generators/xrandom.hpp, include/xtensor/misc/xfft.hpp, include/xtensor/misc/xmanipulation.hpp, include/xtensor/misc/xset_operation.hpp, include/xtensor/misc/xsort.hpp, include/xtensor/misc/xtl_concepts.hpp, include/xtensor/utils/xtensor_simd.hpp, include/xtensor/utils/xutils.hpp, include/xtensor/views/xview.hpp
- [ X] The title and commit message(s) are descriptive.
- [ X] Small commits made to fix your PR have been squashed to avoid history pollution.
- [ X] Tests have been added for new features or bug fixes.
- [ X] API of new functions and classes are documented.
This PR C++20's concept and C++17's `if constexpr` to a moderatly large chunk of `xtensor`.
=> Adding concept to a part of the code

benchmark/benchmark_adapter.cpp, benchmark/benchmark_assign.cpp, benchmark/benchmark_builder.cpp, benchmark/benchmark_container.cpp, benchmark/benchmark_creation.cpp, benchmark/benchmark_increment_stepper.cpp, benchmark/benchmark_lambda_expressions.cpp, benchmark/benchmark_math.cpp, benchmark/benchmark_random.cpp, benchmark/benchmark_reducer.cpp, benchmark/benchmark_view_access.cpp, benchmark/benchmark_view_adapt.cpp, benchmark/benchmark_view_assignment.cpp, benchmark/benchmark_views.cpp, benchmark/benchmark_xshape.cpp, benchmark/main.cpp
-	Update include paths for the benchmarks
-	Comment one benchmark that do not longer compiles. Do not forget to repair it in the future.
=> fix: update benchmarks

include/xtensor/io/xio.hpp
While trying xcpp::display with xeus-cpp-lite, I see this
=> Enabling rich display for xeus-cpp-lite

include/xtensor/misc/xtl_concepts.hpp, include/xtensor/views/xaxis_iterator.hpp, include/xtensor/views/xaxis_slice_iterator.hpp, include/xtensor/views/xbroadcast.hpp, include/xtensor/views/xoffset_view.hpp, include/xtensor/views/xslice.hpp, include/xtensor/views/xstrided_view.hpp, include/xtensor/views/xstrided_view_base.hpp, include/xtensor/views/xview.hpp, include/xtensor/views/xview_utils.hpp
- [ X] The title and commit message(s) are descriptive.
- [ X] Small commits made to fix your PR have been squashed to avoid history pollution.
- [ X] Tests have been added for new features or bug fixes.
This PR C++20's concept and C++17's if constexpr to a moderatly large chunk of xtensor.
=> Adding concept to a part of the code (part 2)

CMakeLists.txt
Generate xtensor.hpp into ${CMAKE_CURRENT_BINARY_DIR} instead of top- level ${CMAKE_BINARY_DIR}.
Expose ${CMAKE_CURRENT_BINARY_DIR} via BUILD_INTERFACE so consumers can find the generated header at build time while keeping install paths unchanged.
=> cmake: write xtensor.hpp to local dir to keep global build dir clean

include/xtensor/containers/xfixed.hpp, include/xtensor/containers/xstorage.hpp, include/xtensor/core/xfunction.hpp
C++17 compiler is required now, so these lines are unnecessary.
=> Remove deprecated constexpr definitions
